const assert=require('node:assert/strict');
const vm=require('node:vm');
const {buildContext,functionSource}=require('./app_source');
const ctx={console,companionPhotoCapturePlan:()=>({label:'Mirror selfie',instruction:'Use a mirror',situation:{placeLabel:'Present work',withNames:[]}}),companionWeatherLabel:()=>''};
buildContext(vm,['buildCompanionPhotoPrompt','companionPhotoReferences'],ctx);
const c={age:43,basePhoto:'identity',appearance:'UNWANTED_FACE_BODY_DETAILS',photoLocations:[{id:'bed',label:'bedroom',description:'Oak headboard',photo:'bedroom-image'}],lifeProfile:{wardrobe:[{id:'gym_set_b',items:'rose shorts'}]}};
let prompt=ctx.buildCompanionPhotoPrompt(c,'Mirror selfie in bedroom wearing gym_set_b');
assert(prompt.includes('43 years old'));assert(!prompt.includes(c.appearance));assert(!prompt.includes('virtual human'));assert(!prompt.includes('gym_set_b'));assert(prompt.includes('rose shorts'));assert(prompt.includes('Image 2: Environment: bedroom'));
assert(ctx.buildCompanionPhotoPrompt(c,'Tea',{hasReference:false}).includes(c.appearance));
assert(!prompt.includes('Appearance emphasis: large breasts'));
c.photoLargeBreasts=true;
assert(ctx.buildCompanionPhotoPrompt(c,'Tea').includes('Appearance emphasis: large breasts'));
assert(ctx.buildCompanionPhotoPrompt(c,'Tea',{hasReference:false}).includes('Appearance emphasis: large breasts'));
assert(!ctx.buildCompanionPhotoPrompt(c,'Bedroom',{locationReferenceOnly:true}).includes('breasts'));
c.photoLargeBreasts=false;
assert(!ctx.buildCompanionPhotoPrompt(c,'Earlier gym photo',{historicalPhoto:true}).includes('Present work'));
assert(!ctx.buildCompanionPhotoPrompt(c,'Oak bedroom',{locationReferenceOnly:true}).includes('43 years old'));
assert.deepEqual(Array.from(ctx.companionPhotoReferences(c,'bedroom mirror')),['identity','bedroom-image']);
assert.deepEqual(Array.from(ctx.companionPhotoReferences(c,'at work')),['identity']);
assert.deepEqual(Array.from(ctx.companionPhotoReferences(c,'bedroom',{includeReference:false})),[]);
console.log('PASS identity reference precedence, age, wardrobe labels, historical continuity and location reference matching');
(async()=>{
 const saved=[];let fail=false;
 const runtime={console,companionSocialPhotoInFlight:new Set(),generateCompanionPhoto:async()=>{if(fail)throw new Error('Synthetic failure');return 'generated';},loadGeneratedImage:async()=> 'data:image/png;base64,c2F2ZWQ=',Image:function(){},saveState:async()=>saved.push(1),state:{},renderCompanionSocialPanel:()=>{}};
 vm.createContext(runtime);vm.runInContext(functionSource('resolveCompanionSocialPhoto'),runtime);
 const posts=Array.from({length:7},(_,i)=>({id:String(i),pending:true,scene:'Tea'}));
 const companion={id:'test',startingSocialPosts:posts,socialPosts:[],usage:{photosGenerated:0}};
 for(const post of posts)await runtime.resolveCompanionSocialPhoto(companion,post);
 assert.equal(posts.filter(p=>p.photo&&!p.pending).length,7);assert.equal(saved.length,7);assert.equal(companion.usage.photosGenerated,7);
 const bad={id:'bad',pending:true,scene:'Tea'};posts.push(bad);fail=true;await runtime.resolveCompanionSocialPhoto(companion,bad);
 assert.equal(bad.pending,false);assert.match(bad.generationError,/Synthetic failure/);
 console.log('PASS all seven starter photos imported and saved, pending cleared, failure remains visible');
})().catch(e=>{console.error(e);process.exitCode=1;});
