'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs');
const target=process.env.HORDE_SUPPORT_URL;
assert(target && new URL(target).hostname==='127.0.0.1', 'Set HORDE_SUPPORT_URL to the disposable vh2_browser_server.py fixture URL.');
const {chromium,launchOptions}=require('./browser_runtime').browserRuntime();
(async()=>{const browser=await chromium.launch(launchOptions);const page=await browser.newPage({viewport:{width:1440,height:1000}});const errors=[],requests=[];let fail=false,delay=false;const embeddingRequests=[];
page.on('pageerror',e=>errors.push(e.message));
await page.route('**/*',async route=>{const url=route.request().url();if(url.includes('/embedding-test/v1/embeddings')){const body=route.request().postDataJSON();embeddingRequests.push(body);return route.fulfill({json:{data:body.input.map((text,index)=>({index,embedding:[text.toLowerCase().includes('human')?1:.01,text.toLowerCase().includes('world')?1:.01,1]})).reverse()}});}if(url.includes('openrouter.ai')||url.includes('nano-gpt.com')){if(url.includes('/models'))return route.fulfill({json:{data:[{id:'deepseek/deepseek-chat',name:'DeepSeek Chat'},{id:'anthropic/claude-test',name:'Claude test',capabilities:{tool_calling:true,structured_output:true,vision:true},pricing:{prompt:4,completion:20,unit:'per_million_tokens'}}]}});if(url.includes('/chat/completions')){requests.push({url,body:route.request().postDataJSON(),headers:route.request().headers()});const last=route.request().postDataJSON();const runtime=JSON.parse(last.messages[0].content.match(/ACTIVE RUNTIME[^\n]*:\n(\{[^\n]+\})/)[1]);const self=/active LLM|running an llm/i.test(last.messages.at(-1).content);const reply=self?'Yes, I use '+runtime.activeModel+' through '+runtime.activeProvider+'. I use Horde Studio documentation as a retrieved knowledge base.':'Open Virtual Humans, author Identity, configure your conversation model, create a starter life and Start Life. <img src=x onerror=alert(1)>'; if(delay)await new Promise(r=>setTimeout(r,1000));return route.fulfill({status:fail?400:200,json:fail?{error:{message:'model not found'}}:{choices:[{message:{content:reply}}]}});}}
if(!url.startsWith(new URL(target).origin)&&!url.startsWith('data:'))return route.abort();return route.continue();});
await page.goto(target);await page.waitForFunction(()=>window.HordePip&&document.querySelector('#labs-guide-messages').textContent.includes('I’m Pip'),null,{timeout:45000});await page.waitForTimeout(2000);if(await page.locator('#close-modal-btn').isVisible())await page.click('#close-modal-btn');console.log('Booted');
await page.evaluate(()=>{if(typeof companionAgencyTimer!=='undefined')clearInterval(companionAgencyTimer);state.globalSettings.apiProvider='local';state.globalSettings.defaultModel='roleplay-do-not-change';state.apiKey='TEST_OPENROUTER_KEY';state.nanogptApiKey='TEST_NANO_KEY';});
await page.click('[data-view="manual"]');await page.fill('#manual-search','virtual human');assert(await page.locator('#manual-toc button').count()>10);await page.locator('#manual-toc button').first().click();assert((await page.locator('#manual-article h1').textContent()).length>3);
await page.fill('#manual-search','zzzznoresult');assert.match(await page.locator('#manual-search-count').textContent(),/^0/);await page.fill('#manual-search','');await page.click('#manual-index-btn');assert(await page.locator('#manual-index-list button').count()>300);await page.locator('#manual-index-dialog [data-close-manual-dialog]').click();
const imageTopic=await page.evaluate(()=>HordeHandbook.pages.find(p=>p.image).id);await page.evaluate(id=>HordeManual.open(id),imageTopic);await page.click('.manual-image-button');await page.waitForFunction(()=>document.querySelector('#manual-large-image').naturalWidth>0);await page.locator('#manual-image-dialog [data-close-manual-dialog]').click();
await page.screenshot({path:'/tmp/horde-manual-desktop.png'});
await page.click('[data-view="pip"]');await page.fill('#labs-guide-input','How do I set up a Virtual Human?');await page.click('#labs-guide-send-btn');assert.match(await page.locator('#labs-guide-messages').textContent(),/life/i);assert.equal(requests.length,0);assert(await page.locator('.pip-source-links button').count()>0);
await page.click('#pip-configure-btn');await page.selectOption('#pip-provider','openrouter');await page.fill('#pip-model','deepseek/exact-manual-id');await page.click('#pip-save-settings');await page.waitForFunction(()=>document.querySelector('#pip-settings-panel').classList.contains('hidden'));await page.fill('#labs-guide-input','How do I create a starter life for my virtual human?');await page.locator('#labs-guide-input').press('Enter');await page.waitForFunction(()=>document.querySelector('#labs-guide-status').textContent.startsWith('Answered by'));assert.equal(requests.length,1);assert.equal(requests[0].headers.authorization,'Bearer TEST_OPENROUTER_KEY');assert.equal(requests[0].body.model,'deepseek/exact-manual-id');assert.match(requests[0].body.messages[0].content,/RETRIEVED GUIDE EVIDENCE:/);assert.match(requests[0].body.messages[0].content,/persistent life/i);assert(!requests[0].body.messages[0].content.includes('TEST_OPENROUTER_KEY'));assert.equal(await page.locator('#labs-guide-messages img').count(),0);assert.equal(await page.evaluate(()=>state.globalSettings.defaultModel),'roleplay-do-not-change');
await page.fill('#labs-guide-input','And what next?');await page.click('#labs-guide-send-btn');await page.waitForFunction(()=>!document.querySelector('#labs-guide-send-btn').disabled);assert(requests[1].body.messages.length>=4);
// A real model request gets authoritative live identity, without the obsolete TinyBrain claims.
await page.fill('#labs-guide-input','are you running an llm?');await page.click('#labs-guide-send-btn');await page.waitForFunction(()=>!document.querySelector('#labs-guide-send-btn').disabled);
assert.match(await page.locator('#labs-guide-messages .assistant').last().textContent(),/deepseek\/exact-manual-id through OpenRouter/);
assert(!requests.at(-1).body.messages[0].content.includes('not from a tiny model'));
assert((await page.locator('#labs-guide-messages .assistant').last().locator('.pip-source-links').textContent()).includes('Pip'));
assert(!(await page.locator('#labs-guide-messages .assistant').last().locator('.pip-source-links').textContent()).includes('MCP'));
// Build and persist a genuine embedding index using a mocked embeddings API, then query it.
await page.evaluate(origin=>{state.globalSettings.embeddingBaseUrl=origin+'/embedding-test/v1';state.globalSettings.embeddingModel='fixture-embed';state.globalSettings.embeddingApiKey='EMBED_FIXTURE_ONLY';state.characters.push({id:'private-fixture',name:'PRIVATE_EXCLUDE',description:'PRIVATE_EXCLUDE'});},new URL(target).origin);
await page.click('#pip-configure-btn');await page.click('#pip-build-index');await page.waitForFunction(()=>document.querySelector('#pip-index-status').textContent.startsWith('Semantic index ready'));
assert(embeddingRequests.length>1);assert(embeddingRequests.every(r=>r.input.every(t=>!t.includes('PRIVATE_EXCLUDE')&&!t.includes('TEST_OPENROUTER_KEY'))));
await page.selectOption('#pip-knowledge-mode','semantic');await page.click('#pip-save-settings');await page.waitForFunction(()=>document.querySelector('#pip-settings-panel').classList.contains('hidden'));
await page.fill('#labs-guide-input','How do Worlds resolve travel?');await page.click('#labs-guide-send-btn');await page.waitForFunction(()=>!document.querySelector('#labs-guide-send-btn').disabled);
assert.match(requests.at(-1).body.messages[0].content,/semantic \+ full-text/);assert(embeddingRequests.at(-1).input.length===1);
fail=true;await page.fill('#labs-guide-input','How do Worlds work?');await page.click('#labs-guide-send-btn');await page.waitForFunction(()=>document.querySelector('#labs-guide-status').textContent.includes('model not found'));assert.match(await page.locator('#labs-guide-messages').textContent(),/World/);fail=false;
delay=true;await page.fill('#labs-guide-input','Help with Worlds');await page.click('#labs-guide-send-btn');await page.click('#pip-clear-chat-btn');await page.waitForTimeout(1300);assert.equal(await page.locator('#labs-guide-messages .labs-guide-message').count(),1);delay=false;
const nano=await page.evaluate(async()=>{const list=await getCompanionOutputModels('text',true,'nanogpt');return {list,ranked:rankCompanionTextModels(list)};});assert.equal(nano.list.length,2);assert.equal(nano.list[1].pricing.prompt,.000004);assert(nano.ranked.find(m=>m.id==='anthropic/claude-test').supportsTools);
await page.click('#pip-configure-btn');await page.selectOption('#pip-provider','nanogpt');await page.fill('#pip-model','nano-exact-id');await page.click('#pip-save-settings');await page.waitForFunction(()=>document.querySelector('#pip-settings-panel').classList.contains('hidden'));await page.fill('#labs-guide-input','Help me set up Worlds');await page.click('#labs-guide-send-btn');await page.waitForFunction(()=>document.querySelector('#labs-guide-status').textContent.startsWith('Answered by'));assert(requests.at(-1).url.includes('nano-gpt.com'));assert.equal(requests.at(-1).body.model,'nano-exact-id');
console.log('Provider and embedding checks passed');await page.reload();await page.waitForFunction(()=>document.querySelector('#labs-guide-messages').textContent.includes('I’m Pip'));await page.click('[data-view="pip"]');await page.click('#pip-configure-btn');assert.equal(await page.locator('#pip-provider').inputValue(),'nanogpt');assert.equal(await page.locator('#pip-model').inputValue(),'nano-exact-id');await page.waitForFunction(()=>HordePipKnowledge.info().indexed);assert.equal(await page.locator('#pip-knowledge-mode').inputValue(),'semantic');
await page.click('#pip-configure-btn');await page.screenshot({path:'/tmp/horde-pip-desktop.png'});await page.setViewportSize({width:390,height:844});await page.evaluate(id=>HordeManual.open(id),imageTopic);assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await page.screenshot({path:'/tmp/horde-manual-mobile.png'});
// Large catalogs must not truncate a valid family before users can search it.
const huge = await page.evaluate(() => rankCompanionTextModels([...Array.from({length:650},(_,i)=>({id:'deepseek/'+i,name:'DeepSeek '+i,supported_parameters:['tools']})),{id:'qwen/exact-last',name:'Qwen last'}]));
assert.equal(huge.length,651); assert(huge.some(m=>m.id==='qwen/exact-last'));
// The same exact-ID contract applies to the actual Virtual Human Studio.
await page.setViewportSize({width:1440,height:1000});
await page.evaluate(()=>{const c=normalizeCompanion({id:'support-nano-fixture',name:'Support Nano fixture',textProvider:'nanogpt'});state.companions.push(c);openCompanionStudio(c.id);switchView('companionStudio');activateCompanionStudioTab('cs-models');});
await page.fill('#cs-text-model-custom','qwen/exact-manual-model');
assert.equal(await page.evaluate(()=>getCompanion('support-nano-fixture').model),'qwen/exact-manual-model');
await page.evaluate(async()=>{await populateCompanionTextModelPicker(getCompanion('support-nano-fixture'),true);});
assert.equal(await page.locator('#cs-text-model-custom').inputValue(),'qwen/exact-manual-model');
// Deep links survive an application reload and do not require an API key.
const topic=await page.evaluate(()=>HordeHandbook.pages.find(p=>p.diagram==='person-life').id);
await page.evaluate(id=>HordeManual.open(id),topic);await page.reload();
await page.waitForFunction(()=>window.__hordeStartup?.readyMs && !document.querySelector('#manual-view').classList.contains('hidden'));
assert.equal(await page.locator('#manual-article h1').textContent(),'Understand the person and the life');
await page.mouse.move(1400,980); await page.keyboard.press('Escape');await page.screenshot({path:'/tmp/horde-manual-desktop.png'});
// Load every shipped screenshot and prepare the entire print artifact.
const imageStatus=await page.evaluate(async()=>Promise.all(HordeHandbook.pages.filter(p=>p.image).map(async p=>({id:p.id,status:(await fetch(p.image)).status}))));
assert(imageStatus.every(p=>p.status===200));
await page.evaluate(()=>{window.print=()=>window.__supportPrinted=true;});await page.click('#manual-print-btn');
await page.waitForFunction(()=>window.__supportPrinted===true);assert.equal(await page.locator('#manual-print section').count(),75);
await page.evaluate(()=>{state.globalSettings.pip={provider:'builtin',models:{}};HordePip.renderStatus();switchView('pip');});await page.click('#pip-clear-chat-btn');await page.click('#pip-configure-btn');await page.mouse.move(1400,980);await page.keyboard.press('Escape');await page.screenshot({path:'/tmp/horde-pip-settings.png'});
assert.deepEqual(errors,[]);console.log('PASS: manual search/index/screenshots/mobile; independent provider/exact ID/persistence; grounded requests/follow-ups; error fallback; cancellation; safe text rendering; NanoGPT metadata.');await browser.close();})().catch(e=>{console.error(e);process.exit(1);});
