'use strict';
const {spawn}=require('node:child_process'),assert=require('node:assert/strict');
const {chromium,launchOptions}=require('./browser_runtime').browserRuntime();
(async()=>{const server=spawn(process.env.HORDE_PYTHON_EXECUTABLE||'python3',['scratch/vh2_browser_server.py'],{stdio:['ignore','pipe','pipe']});let browser;
try{const port=await new Promise((resolve,reject)=>{server.stdout.once('data',d=>resolve(+String(d).trim()));server.stderr.on('data',d=>process.stderr.write(d));server.once('exit',c=>reject(Error('server '+c)));});const base=`http://127.0.0.1:${port}`;
 browser=await chromium.launch(launchOptions);const page=await browser.newPage({viewport:{width:1200,height:1000}}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.route('**/*',r=>r.request().url().startsWith(base)?r.continue():r.abort());await page.goto(base+'/index.html');await page.waitForFunction(()=>typeof companionAgencyTimer!=='undefined'&&!!companionAgencyTimer);
 await page.evaluate(async base=>{clearInterval(companionAgencyTimer);clearInterval(companionAlwaysOnTimer);mcpBridgeBase=()=>base;state.globalSettings.localBaseUrl=base+'/test';state.globalSettings.localApiKey='LOCAL_TEST_KEY';state.globalSettings.apiProvider='local';state.globalSettings.defaultModel='browser-fixture';state.globalSettings.companionAlwaysOnEnabled=false;
 const c=normalizeCompanion({id:'budget-browser',name:'Budget fixture',age:28,textProvider:'local',model:'browser-fixture',lifeProfile:{weeklySchedule:[],sleepPolicy:{enabled:false}}});state.companions=[c];state.activeCompanionId=c.id;state.companionTimelines={};state.companionThreads={};ensureCompanionTimelineStore(c.id);hideGlobalSettings();
 await mcpBridgeRequest('/vh2/dialogue-provider',{method:'POST',body:{scope:'horde:'+c.id,baseUrl:base+'/test',model:'browser-fixture',apiKey:'LOCAL_TEST_KEY',enabled:true,maxTokens:512,dailyLimit:2,temperature:.7}});
 await vh2CreateTimeline(c);switchView('companionChat');renderCompanionThread();await vh2Poll(c,getActiveCompanionTimeline(c.id),{force:true,throwOnError:true});},base);
 const notice=page.locator('#vh-text-budget-notice');await notice.getByText(/Legacy shared text cap: 0 \/ 2/).waitFor();assert(await notice.getByRole('button',{name:'Text request budgets',exact:true}).isVisible());
 await notice.getByRole('button',{name:'Text request budgets',exact:true}).click();const d=page.getByRole('dialog',{name:'Text request budgets',exact:true});await d.getByText(/The old shared cap is still enforced/).waitFor();assert.equal(await d.locator('[name=capped]').isChecked(),true);await d.locator('[name=capped]').uncheck();await d.locator('[name=background]').fill('1');await d.getByRole('button',{name:'Save text budgets'}).click();await d.getByText('Text budgets saved. No provider request was submitted or retried.',{exact:true}).waitFor();await d.getByRole('button',{name:'Close',exact:true}).click();await notice.getByText(/local daily cap off/).waitFor();
 const saved=await page.evaluate(()=>mcpBridgeRequest('/vh2/dialogue-provider?scope=horde%3Abudget-browser'));assert.equal(saved.budgetPolicy.dialogueDailyLimit,null);assert.equal(saved.budgetPolicy.backgroundDailyLimit,1);assert.equal(saved.usedToday,0);assert.equal(saved.budgets.dialogue.legacy,false);
 await page.route(base+'/vh2/dialogue-jobs?*',r=>r.fulfill({status:200,contentType:'application/json',body:JSON.stringify({jobs:[{id:'fixture',model:'fixture-model',status:'delivered',created_at:Date.now(),usage:{prompt_tokens:123,completion_tokens:7,total_tokens:130},promptPreview:[{role:'system',content:'Frozen fixture instructions [credential redacted]'}],promptTruncated:false}]})}));await notice.getByRole('button',{name:'Reply details',exact:true}).click();const details=page.getByRole('dialog',{name:'Reply details',exact:true});await details.getByText(/fixture-model · delivered/).click();await details.getByText('Provider-reported tokens: input 123 · output 7 · total 130',{exact:true}).waitFor();await details.getByText('Frozen prompt text (redacted preview)',{exact:true}).click();await details.getByText(/Frozen fixture instructions/).waitFor();await details.getByRole('button',{name:'Close',exact:true}).click();// Everyday chat keeps usage details tucked away; blockers remain visible.
 await page.evaluate(()=>{const c=getCompanion('budget-browser');document.getElementById('vh-text-budget-notice').remove();vh2RenderTextBudgetNotice(c);});
 assert.equal(await notice.evaluate(el=>el.open),false);
 await notice.locator('summary').click();assert(await notice.getByRole('button',{name:'Reply details',exact:true}).isVisible());
 await page.evaluate(()=>vh2RenderTextBudgetNotice(getCompanion('budget-browser')));assert.equal(await notice.evaluate(el=>el.open),true,'polling preserves user disclosure');
 await page.evaluate(()=>{const c=getCompanion('budget-browser'),t=getActiveCompanionTimeline(c.id);t.vh2.textProvider.budgets.dialogue.limit=1;t.vh2.textProvider.budgets.dialogue.used=1;document.getElementById('vh-text-budget-notice').open=false;vh2RenderTextBudgetNotice(c);});
 assert.equal(await notice.evaluate(el=>el.open),true);await notice.getByText('Chat request allowance reached — review limits',{exact:true}).waitFor();
 for(const [mode,expected] of [['waiting','Waiting for a reply: At dinner until 20:00'],['paused','Message saved · life is paused, so replies are waiting'],['queued','Preparing a reply…'],['leased','Preparing a reply…'],['submitted','Preparing a reply…'],['unknown','Reply outcome unknown — review before retrying'],['failed','Reply did not finish: Daily allowance reached'],['connected','Connected']]){
  await page.evaluate(mode=>{const c=getCompanion('budget-browser'),t=getActiveCompanionTimeline(c.id);t.messages=mode==='connected'?[]:[{role:'user',awaitingReply:true,attention:{reason:'At dinner until 20:00'}}];Object.assign(t.vh2,{running:mode!=='paused',error:'',outbox:[],lastSyncedAt:Date.now(),replyJob:['queued','leased','submitted','unknown','failed'].includes(mode)?{status:mode,reason:mode==='failed'?'Daily allowance reached':''}:null});vhRenderSystemStatus(c);},mode);
  assert.equal(await page.locator('#vh-chat-system > span').innerText(),expected);
 }
 await page.setViewportSize({width:390,height:844});await page.evaluate(()=>{document.getElementById('vh-text-budget-notice').open=false;});
 await page.locator('#vh-chat-more > summary').click();
 for(const selector of ['#companion-simulation-btn','#vh-chat-activity','#cc-persona-select'])assert(await page.locator(selector).isVisible(),selector+' remains accessible in More');
 await page.locator('#vh-chat-more .vh-person-tools > summary').click();assert(await page.getByRole('button',{name:'Providers & feeds',exact:true}).isVisible());
 await page.locator('#vh-chat-more > summary').focus();await page.keyboard.press('Escape');assert.equal(await page.locator('#vh-chat-more').evaluate(el=>el.open),false);
 const layout=await page.locator('#vh-chat-system').evaluate(el=>({width:el.getBoundingClientRect().width,scroll:el.scrollWidth,client:el.clientWidth}));assert(layout.width<=390&&layout.scroll<=layout.client+1,JSON.stringify(layout));
 const fs=require('node:fs');fs.mkdirSync('docs/vh2/creation-chat-20260920',{recursive:true});await page.screenshot({path:'docs/vh2/creation-chat-20260920/chat-mobile.png',fullPage:true});await page.setViewportSize({width:320,height:740});await page.locator('#vh-chat-more > summary').click();assert(await page.locator('#cc-persona-select').isVisible());const narrow=await page.locator('#vh-chat-more > div').evaluate(el=>({left:el.getBoundingClientRect().left,right:el.getBoundingClientRect().right,scroll:el.scrollWidth,client:el.clientWidth,body:document.documentElement.scrollWidth}));assert(narrow.left>=0&&narrow.right<=320&&narrow.scroll<=narrow.client+1&&narrow.body<=320,'320px menu overflow '+JSON.stringify(narrow));await page.screenshot({path:'docs/vh2/creation-chat-20260920/chat-menu-320.png',fullPage:true});await page.locator('#vh-chat-more > summary').focus();await page.keyboard.press('Escape');await page.setViewportSize({width:1440,height:1000});await page.screenshot({path:'docs/vh2/creation-chat-20260920/chat-desktop.png',fullPage:true});
 assert.deepEqual(errors,[]);console.log('PASS chat UX: compact usage, legacy/exhausted limit disclosure, explicit controls, token details, waiting/paused/generating/failure/unknown states, mobile sizing; no provider spend.');
}finally{if(browser)await browser.close();server.kill();}
})().catch(e=>{console.error(e);process.exitCode=1;});
