'use strict';
const assert=require('node:assert/strict'),pop=require('../vh2-population-engine');
const local=()=>({weekday:1,hour:10,minute:0}),normalize=p=>({...p});
function fixture(){return {id:'a',lifeProfile:{places:[{id:'cafe',label:'Cafe',kind:'cafe',encounterScope:'nearby'}],socialCircle:[],world:{people:[]}},lifeRuntime:{world:{placeId:'cafe',people:{new:{placeId:'cafe',availability:'available'}}}},vh2People:{actors:{new:{id:'new',placeId:'cafe',policy:{homePlaceId:'residence'}}}},humanDynamics:{stress:0},vh2Population:{enabled:true,openness:100,residents:[{id:'new',name:'Sam',placeId:'cafe',days:[1],start:0,end:1440,openness:100,introducedAt:null}],contacts:{},events:[],sequence:0}};}
let c=fixture();pop.advance(c,100000,'available',local,normalize);assert.deepEqual(pop.known(c),[]);assert.equal(c.lifeProfile.socialCircle.length,0);pop.advance(c,100000+15*60000,'available',local,normalize);assert.equal(c.lifeProfile.socialCircle.length,1);assert.equal(c.lifeProfile.socialCircle[0].closeness,0);assert.deepEqual(c.lifeProfile.socialCircle[0].contactWindows,[]);let saved=JSON.parse(JSON.stringify(c));pop.advance(c,2000000,'available',local,normalize);pop.advance(saved,2000000,'available',local,normalize);assert.deepEqual(c,saved);assert.equal(c.vh2Population.events.length,1);
for(const constraint of ['home','busy','guarded','travelling']){let x=fixture();if(constraint==='home')x.lifeProfile.places[0].kind='home';if(constraint==='guarded')x.vh2Population.residents[0].openness=0;if(constraint==='travelling')x.lifeRuntime.world.journey={};for(let i=0;i<24;i++)pop.advance(x,100000+i*60000,constraint==='busy'?'busy':'available',local,normalize);assert.equal(x.lifeProfile.socialCircle.length,0,constraint);}
let x=fixture();x.vh2Population.residents[0].openness=0;pop.advance(x,100000,'available',local,normalize);pop.advance(x,1000000,'available',local,normalize);const decision=x.vh2Population.residents[0].lastDecision;for(let i=0;i<50;i++)pop.advance(x,1000000+i*60000,'available',local,normalize);assert.equal(x.vh2Population.residents[0].lastDecision,decision,'no polling lottery');
console.log('Population: persistent introductions, privacy, mutual willingness, no instant friendship/contact, restart and no rerolls passed');
let outgoing=0,guarded=0;
for(let seed=0;seed<100;seed++)for(const openness of [20,80]){const x=fixture();x.id='seed'+seed;x.vh2Population.openness=openness;x.vh2Population.residents[0].openness=80;pop.advance(x,100000,'available',local,normalize);pop.advance(x,1000000,'available',local,normalize);if(x.lifeProfile.socialCircle.length){if(openness===80)outgoing++;else guarded++;}}
assert.ok(outgoing>guarded&&guarded>0&&outgoing<100,`variation and personality effect: ${outgoing}/${guarded}`);
console.log(`100 paired seeds: outgoing ${outgoing} introductions, guarded ${guarded}`);
