async function revealSummary(locator){const title=await locator.textContent();await locator.evaluate(el=>{let panel=el.parentElement;while(panel.parentElement?.id!=='vh2-chat-controls'&&panel.parentElement?.closest('details'))panel=panel.parentElement.closest('details');if(panel.parentElement?.id==='vh2-chat-controls')vhOpenWorkspace(panel.dataset.workspaceSection||'overview');vhAdvancedOpen=true;vhFilterWorkspace();});await locator.evaluate(el=>{el.parentElement.open=true;let parent=el.parentElement.parentElement.closest('details');while(parent){parent.open=true;parent=parent.parentElement.closest('details');}});}
'use strict';
const {spawn}=require('node:child_process'),assert=require('node:assert/strict');
const { chromium, launchOptions } = require('./browser_runtime').browserRuntime();
(async()=>{
 const server=spawn('python3',['scratch/vh2_browser_server.py'],{stdio:['ignore','pipe','pipe']});let browser,recoveryServer;
 try{
  const port=await new Promise((resolve,reject)=>{server.stdout.once('data',d=>resolve(Number(String(d).trim())));server.once('exit',c=>reject(Error('Server exit '+c)));server.stderr.on('data',d=>process.stderr.write(d));});
  const base=`http://127.0.0.1:${port}`;
  browser=await chromium.launch(launchOptions);
  const page=await browser.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));
  await page.route('**/*',route=>route.request().url().startsWith(base)?route.continue():route.abort());
  await page.goto(base+'/index.html');
  await page.waitForFunction(()=>typeof companionAgencyTimer!=='undefined'&&!!companionAgencyTimer);
  await page.evaluate(base=>{
   clearInterval(companionAgencyTimer);clearInterval(companionAlwaysOnTimer);mcpBridgeBase=()=>base;
   state.globalSettings.localBaseUrl=base+'/test';state.globalSettings.localApiKey='LOCAL_TEST_KEY';state.globalSettings.apiProvider='local';state.globalSettings.defaultModel='browser-fixture';
   const c=normalizeCompanion({id:'integrated-alex',name:'Alex',age:28,textProvider:'local',model:'browser-fixture',locationMode:'custom',timezoneOffsetMinutes:0,
    personality:'Quiet and curious',lifeProfile:{initializedAt:1788764400000,places:[{id:'home',label:'Home',kind:'home'},{id:'cafe',label:'Cafe',kind:'social',encounterScope:'nearby'}],weeklySchedule:[],sleepPolicy:{enabled:false},socialCircle:[{id:'jo',name:'Jo',closeness:100,contactWindows:[{days:[0,1,2,3,4,5,6],startMinute:0,endMinute:1440}]}],world:{transport:{enabled:true},people:[{personId:'jo',placeId:'home',days:[0,1,2,3,4,5,6],start:0,end:1440,activity:'relaxing'}]}}});
   state.companions=[c];state.companionTimelines={};state.companionThreads={};state.activeCompanionId=c.id;ensureCompanionTimelineStore(c.id);
   getCompanionThread(c.id).push(normalizeCompanionMessage({id:'old',role:'user',text:'Old timeline stays here',timestamp:Date.now()}));
   hideGlobalSettings();switchView('companionChat');renderCompanionThread();
  },base);
  await page.evaluate(()=>vhOpenWorkspace('overview'));
  await page.locator('[data-start-persistent]').click();
  await page.waitForFunction(()=>getActiveCompanionTimeline('integrated-alex')?.vh2?.running===true);
  const w=await page.evaluate(()=>getActiveCompanionTimeline('integrated-alex').vh2.worldId);
  assert(await page.locator('#companion-reset-timeline-btn').isDisabled());
  assert(await page.locator('#companion-fork-timeline-btn').isDisabled());
  const baseline=await page.evaluate(()=>getActiveCompanionTimeline('integrated-alex').runtime.humanDynamics.lastUpdated);
  await page.evaluate(()=>{renderCompanionThread();persistCompanionRuntime(getCompanion('integrated-alex'));});
  assert.equal(await page.evaluate(()=>getActiveCompanionTimeline('integrated-alex').runtime.humanDynamics.lastUpdated),baseline,'rendering never advances service-owned needs');
  // Lose one acknowledged POST. The durable outbox must replay the same receipt.
  let lost=false;
  await page.route('**/vh2/command',async route=>{const data=route.request().postDataJSON();if(data.type==='receive_message'&&!lost){lost=true;await route.fetch();await route.abort();}else await route.continue();});
  await page.evaluate(()=>switchView('companionChat'));
  await page.locator('#companion-composer-input').fill("Hello, I live in London. I'll text you in an hour.");
  await page.evaluate(()=>handleCompanionSend());
  await page.evaluate(()=>vh2Poll(getCompanion('integrated-alex')));
  let p=await (await fetch(base+'/vh2/projection?worldId='+w)).json();
  assert.equal(p.state.communication.messages.filter(m=>m.role==='user').length,1,'uncertain acknowledgement did not duplicate message');
  for(let i=0;i<12;i++){
   await fetch(base+'/test/tick',{method:'POST'});
   await new Promise(r=>setTimeout(r,1100));
   p=await (await fetch(base+'/vh2/projection?worldId='+w)).json();
   if(p.state.communication.messages.some(m=>m.role==='assistant'))break;
  }
  await page.evaluate(()=>vh2Poll(getCompanion('integrated-alex')));
  assert(p.state.communication.messages.some(m=>m.text==='Local mock model reply'),'attention automatically produced a reply');
  assert.match(await page.locator('#companion-messages').innerText(),/Local mock model reply/);
  assert.equal(await page.evaluate(()=>state.companionTimelines['integrated-alex'].sessions.find(t=>!t.vh2).messages[0].text),'Old timeline stays here');
  await page.reload();await page.waitForFunction(()=>typeof companionAgencyTimer!=='undefined'&&!!companionAgencyTimer);
  await page.evaluate(base=>{clearInterval(companionAgencyTimer);clearInterval(companionAlwaysOnTimer);mcpBridgeBase=()=>base;},base);
  assert.equal(await page.evaluate(()=>getActiveCompanionTimeline('integrated-alex').vh2.worldId),w);
  await page.evaluate(()=>vh2Poll(getCompanion('integrated-alex')));
  assert.equal(await page.evaluate(()=>getCompanionThread('integrated-alex').filter(m=>m.role==='companion').length),1);
  await page.evaluate(()=>{switchView('companionChat');renderCompanionThread();vhOpenWorkspace('inspector');});
  await page.evaluate(()=>vhOpenPanel('Text check-ins'));
  await page.getByRole('button',{name:'Dismiss expectation',exact:true}).click();
  await page.waitForFunction(()=>getActiveCompanionTimeline('integrated-alex').vh2.checkIns?.[0]?.status==='dismissed');
  await page.waitForFunction(()=>!vh2PollLocks.has(getActiveCompanionTimeline('integrated-alex').id));
  await page.evaluate(()=>vhOpenPanel('Experience and memory'));
  await page.locator('[data-experience-policy=learningRate]').fill('0.35');
  await page.getByRole('button',{name:'Save experience settings',exact:true}).click();
  await page.waitForFunction(()=>getActiveCompanionTimeline('integrated-alex').vh2.psychology.learningRate===.35);
  await page.waitForFunction(()=>!vh2PollLocks.has(getActiveCompanionTimeline('integrated-alex').id));
  await page.evaluate(()=>vhOpenPanel('Conversation emotions'));
  await page.locator('[data-conversation-policy=emotionalImpact]').fill('1.5');
  await page.locator('[data-conversation-policy=maxEmotionChange]').fill('2');
  await page.locator('[data-conversation-enabled]').uncheck();
  await page.getByRole('button',{name:'Save conversation emotions',exact:true}).click();
  await page.waitForFunction(()=>getActiveCompanionTimeline('integrated-alex').vh2.conversationAppraisal?.emotionalImpact===1.5&&!getActiveCompanionTimeline('integrated-alex').vh2.conversationAppraisal.enabled);
  await page.waitForFunction(()=>!vh2PollLocks.has(getActiveCompanionTimeline('integrated-alex').id));
  await page.evaluate(()=>vhOpenPanel('Relationship pace'));
  await page.locator('[data-relationship-policy=friendliness]').fill('85');
  await page.locator('[data-relationship-policy=guardedness]').fill('75');
  await page.getByRole('button',{name:'Save relationship pace',exact:true}).click();
  await page.waitForFunction(()=>getActiveCompanionTimeline('integrated-alex').vh2.relationshipLearning?.friendliness===85);
  await page.waitForFunction(()=>!vh2PollLocks.has(getActiveCompanionTimeline('integrated-alex').id));
  await fetch(base+'/test/kernel-version',{method:'POST'});
  await page.evaluate(()=>vh2Poll(getCompanion('integrated-alex')));
  await page.evaluate(()=>vhOpenWorkspace('recovery'));await page.getByRole('button',{name:'Upgrade timeline engine (creates backup)',exact:true}).click();
  await page.waitForFunction(()=>!!getActiveCompanionTimeline('integrated-alex').vh2.checkpointId&&!getActiveCompanionTimeline('integrated-alex').vh2.requiresMigration);
  assert.equal(await page.evaluate(()=>getActiveCompanionTimeline('integrated-alex').vh2.running),false);
  assert.equal(await page.evaluate(()=>getActiveCompanionTimeline('integrated-alex').vh2.psychology.learningRate),.35);
  const longRoundTrip=await page.evaluate(()=>{const c=getCompanion('integrated-alex'),t=getActiveCompanionTimeline(c.id);const copy=JSON.parse(JSON.stringify(t));copy.messages=[{id:'long-reply',role:'companion',text:'a'.repeat(7000),timestamp:Date.now()}];return normalizeCompanionTimeline(copy,c).messages[0].text.length;});
  assert.equal(await page.evaluate(()=>getActiveCompanionTimeline('integrated-alex').vh2.conversationAppraisal.maxEmotionChange),2);
  assert.equal(await page.evaluate(()=>getActiveCompanionTimeline('integrated-alex').vh2.relationshipLearning.guardedness),75);
  assert.equal(longRoundTrip,7000,'accepted service reply is not truncated by browser normalization');
  await page.evaluate(()=>{
    const c=getCompanion('integrated-alex');c.imageSource='local';c.imageModel='offline-photo-fixture';
    const canvas=document.createElement('canvas');canvas.width=2;canvas.height=2;canvas.getContext('2d').fillRect(0,0,2,2);window.photoFixture=canvas.toDataURL();canvas.getContext('2d').fillStyle='white';canvas.getContext('2d').fillRect(0,0,2,2);c.basePhoto=canvas.toDataURL();
    window.photoRequests=[];
    requestCompanionPhoto=async body=>{window.photoRequests.push(body);getCompanion('integrated-alex').currentLocationDetail='Wrong later location';return window.photoFixture;};
    renderCompanionThread();vhOpenWorkspace('inspector');
  });
  await page.evaluate(()=>vhOpenPanel('Photo capture preview'));
  await page.locator('[data-vh2-photo-scene]').fill('A relaxed close-up');
  await page.getByRole('button',{name:'Review current moment',exact:true}).click();
  await page.locator('[data-submit-render]').click();
  await page.waitForFunction(()=>getActiveCompanionTimeline('integrated-alex').vh2.photos?.[0]?.status==='delivered');await page.locator('#vh-photo-review [data-close]').click();await page.evaluate(()=>switchView('companionChat'));
  assert.equal(await page.evaluate(()=>window.photoRequests.length),1);
  assert.equal(await page.evaluate(()=>window.photoRequests[0].prompt.includes('Wrong later location')),false);
  assert.equal(await page.evaluate(()=>window.photoRequests[0].input_references.length),1);
  await page.waitForFunction(()=>[...document.querySelectorAll('#companion-messages img')].some(i=>i.src.includes('/vh2/photo-asset')&&i.naturalWidth===2));
  await page.evaluate(()=>{
    const c=getCompanion('integrated-alex');window.photoTimelineId=getActiveCompanionTimeline(c.id).id;
    c.photoStyle=Object.keys(COMPANION_PHOTO_STYLES).find(k=>k!==getActiveCompanionTimeline(c.id).vh2.photos[0].photoContext.style);
    requestCompanionPhoto=async body=>{window.photoRequests.push(body);const old=state.companionTimelines[c.id].sessions.find(t=>!t.vh2);activateCompanionTimeline(c.id,old.id);return window.photoFixture;};
  });
  await page.evaluate(()=>vh2GeneratePhoto(getCompanion('integrated-alex'),getActiveCompanionTimeline('integrated-alex'),'A second relaxed close-up','front_camera_selfie'));
  assert.equal(await page.evaluate(()=>window.photoRequests[1].input_references.length),2,'follow-up retains base identity and previous photo');
  assert.equal(await page.evaluate(()=>getActiveCompanionTimeline('integrated-alex').messages.some(m=>m.type==='photo')),false,'switching timelines cannot redirect photo delivery');
  await page.evaluate(async()=>{activateCompanionTimeline('integrated-alex',window.photoTimelineId);renderCompanionThread();await saveState();});
  assert.equal(await page.evaluate(()=>{const p=getActiveCompanionTimeline('integrated-alex').vh2.photos;return p[0].photoContext.style===p[1].photoContext.style;}),true);
  await page.reload();await page.waitForFunction(()=>typeof companionAgencyTimer!=='undefined'&&!!companionAgencyTimer);
  await page.evaluate(base=>{clearInterval(companionAgencyTimer);clearInterval(companionAlwaysOnTimer);mcpBridgeBase=()=>base;switchView('companionChat');renderCompanionThread();},base);
  await page.waitForFunction(()=>[...document.querySelectorAll('#companion-messages img')].some(i=>i.src.includes('/vh2/photo-asset')&&i.naturalWidth===2));
  assert.equal(await page.evaluate(()=>getCompanionThread('integrated-alex').filter(m=>m.type==='photo').length),2);
  const historyCount=await page.evaluate(()=>getCompanionThread('integrated-alex').length);
  await page.evaluate(async()=>{const c=getCompanion('integrated-alex'),t=getActiveCompanionTimeline(c.id);t.messages=[];delete t.vh2.transcriptBefore;await vh2LoadHistory(c,t);});
  assert.equal(await page.evaluate(()=>getCompanionThread('integrated-alex').length),historyCount,'service transcript recovers missing browser history');
  assert.equal(await page.evaluate(()=>getCompanionThread('integrated-alex').filter(m=>m.type==='photo').length),2);
  assert.equal(await page.evaluate(()=>getActiveCompanionTimeline('integrated-alex').vh2.transcriptBefore),null);
  await page.evaluate(async()=>{
    const canvas=document.createElement('canvas');canvas.width=canvas.height=2;canvas.getContext('2d').fillRect(0,0,2,2);
    requestCompanionPhoto=async body=>{window.galleryRequest=body;return canvas.toDataURL();};
    const c=getCompanion('integrated-alex');await vh2GeneratePhoto(c,getActiveCompanionTimeline(c.id),'A saved close-up','front_camera_selfie','gallery');
  });
  assert.equal(await page.evaluate(()=>getCompanionThread('integrated-alex').filter(m=>m.type==='photo').length),2,'gallery capture does not send a chat photo');
  assert.equal(await page.evaluate(()=>window.galleryRequest.prompt.includes('camera gallery')),true);
  await page.evaluate(()=>{const c=getCompanion('integrated-alex');companionSocialPanelVisibility.set(companionSocialPanelKey(c),true);renderCompanionSocialPanel(c);});
  const social=page.locator('#companion-social-content');
  const galleryId=await page.evaluate(()=>getActiveCompanionTimeline('integrated-alex').vh2.photos.find(p=>p.status==='stored').id);
  await page.evaluate(()=>vhOpenWorkspace('media'));const publishing=page.locator('.vh-media-publishing');
  await publishing.getByLabel('Photo to publish',{exact:true}).selectOption(galleryId);
  await publishing.getByLabel('Post caption',{exact:true}).fill('A saved moment');
  await publishing.getByRole('button',{name:'Publish to simulated profile',exact:true}).click();
  await page.waitForFunction(()=>getActiveCompanionTimeline('integrated-alex').vh2.socialPosts?.length===1);
  await page.evaluate(()=>{switchView('companionChat');renderCompanionSocialPanel(getCompanion('integrated-alex'));});
  await social.getByRole('button',{name:'♡ Like',exact:true}).click();
  await page.waitForFunction(()=>getActiveCompanionTimeline('integrated-alex').vh2.socialPosts[0].likedByPlayer);
  await social.getByLabel('Comment on post',{exact:true}).fill('Nice photo');
  await social.getByRole('button',{name:'Comment',exact:true}).click();
  await page.waitForFunction(()=>getActiveCompanionTimeline('integrated-alex').vh2.socialPosts[0].comments.length===1);
  await page.reload();await page.waitForFunction(()=>typeof companionAgencyTimer!=='undefined'&&!!companionAgencyTimer);
  await page.evaluate(base=>{clearInterval(companionAgencyTimer);clearInterval(companionAlwaysOnTimer);mcpBridgeBase=()=>base;switchView('companionChat');const c=getCompanion('integrated-alex');companionSocialPanelVisibility.set(companionSocialPanelKey(c),true);renderCompanionSocialPanel(c);},base);
  assert.equal(await social.locator('article').count(),1);
  assert.equal(await social.getByText('You: Nice photo',{exact:true}).count(),1);
  await page.evaluate(()=>vhOpenWorkspace('media'));await publishing.getByRole('button',{name:'Withdraw post',exact:true}).click();
  await page.waitForFunction(()=>getActiveCompanionTimeline('integrated-alex').vh2.socialPosts[0].status==='withdrawn');
  await page.waitForFunction(()=>document.querySelectorAll('#companion-social-content article').length===0);
  await page.evaluate(()=>vhOpenWorkspace('overview'));
  await revealSummary(page.locator('summary').filter({hasText:'Shared plans'}));
  await page.getByLabel('Shared plan description',{exact:true}).fill('Catch up over coffee');
  await page.getByRole('button',{name:'Propose shared plan',exact:true}).click();
  await page.waitForFunction(()=>getActiveCompanionTimeline('integrated-alex').vh2.plans?.length===1);
  assert.equal(await page.evaluate(()=>getActiveCompanionTimeline('integrated-alex').vh2.plans[0].status),'proposed');
  const planPanel=page.locator('details').filter({has:page.locator('summary').filter({hasText:'Shared plans'})}).last();
  if(!await planPanel.evaluate(el=>el.open))await revealSummary(page.locator('summary').filter({hasText:'Shared plans'}));
  await page.getByRole('button',{name:'Cancel plan',exact:true}).click();
  await page.waitForFunction(()=>getActiveCompanionTimeline('integrated-alex').vh2.plans[0].status==='cancelled');
  await revealSummary(page.locator('summary').filter({hasText:'Local people & introductions'}));
  await page.getByLabel('Enable introductions',{exact:true}).check();
  await page.getByLabel('Character willingness to approach (0–100)',{exact:true}).fill('65');
  await page.getByRole('button',{name:'Save introduction settings',exact:true}).click();
  await page.waitForFunction(()=>getActiveCompanionTimeline('integrated-alex').vh2.population?.openness===65);
  await page.waitForFunction(()=>!vh2PollLocks.has(getActiveCompanionTimeline('integrated-alex').id));
  await revealSummary(page.locator('summary').filter({hasText:'Local people & introductions'}));
  await page.getByLabel('Resident name',{exact:true}).fill('Sam');
  await page.getByRole('button',{name:'Add resident',exact:true}).click();
  await page.waitForFunction(()=>getActiveCompanionTimeline('integrated-alex').vh2.population?.residents.length===1);
  await page.waitForFunction(()=>!vh2PollLocks.has(getActiveCompanionTimeline('integrated-alex').id));
  await revealSummary(page.locator('summary').filter({hasText:'Local people & introductions'}));
  const populationPanel=page.locator('details').filter({has:page.locator('summary').filter({hasText:'Local people & introductions'})}).last();
  await populationPanel.getByRole('button',{name:'Remove',exact:true}).click();
  await page.waitForFunction(()=>getActiveCompanionTimeline('integrated-alex').vh2.population?.residents.length===0);
  await page.waitForFunction(()=>!vh2PollLocks.has(getActiveCompanionTimeline('integrated-alex').id));
  await revealSummary(page.locator('summary').filter({hasText:'Independent people & transport'}));
  await page.getByLabel('Starting simulated budget',{exact:true}).fill('75');
  await page.getByRole('button',{name:'Enable independent life',exact:true}).click();
  await page.waitForFunction(()=>getActiveCompanionTimeline('integrated-alex').vh2.people?.actors.jo?.balance===75);
  await page.waitForFunction(()=>!vh2PollLocks.has(getActiveCompanionTimeline('integrated-alex').id));
  await revealSummary(page.locator('summary').filter({hasText:'Friendships, contact & romantic progression'}));
  await page.getByLabel('Days before friendship',{exact:true}).fill('40');
  await page.getByRole('button',{name:'Save social progression',exact:true}).click();
  await page.waitForFunction(()=>getActiveCompanionTimeline('integrated-alex').vh2.socialBonds?.policy.friendDays===40);
  await page.waitForFunction(()=>!vh2PollLocks.has(getActiveCompanionTimeline('integrated-alex').id));
  await revealSummary(page.locator('summary').filter({hasText:'Friendships, contact & romantic progression'}));
  await page.getByLabel('Established age of this person',{exact:true}).fill('30');
  await page.getByLabel('Character potential interest (0–100)',{exact:true}).fill('60');
  await page.getByRole('button',{name:'Save romantic potential',exact:true}).click();
  await page.waitForFunction(()=>getActiveCompanionTimeline('integrated-alex').vh2.socialBonds?.pairs.jo.lifecycle?.policy.selfPotential===60);
  await page.waitForFunction(()=>!vh2PollLocks.has(getActiveCompanionTimeline('integrated-alex').id));
  await page.evaluate(()=>{vhOpenWorkspace('closet');vhOpenPanel('Gifts & money');});
  await revealSummary(page.locator('summary').filter({hasText:'Gift preferences & starting funds'}));
  await page.getByLabel('Enable gifts',{exact:true}).check();
  await page.getByLabel('Permission to receive money',{exact:true}).check();
  await page.getByLabel('Minimum relationship trust',{exact:true}).fill('-100');
  await page.getByLabel('Currency label (no conversion)',{exact:true}).fill('GBP');
  await page.getByRole('button',{name:'Save gift preferences',exact:true}).click();
  await page.waitForFunction(()=>getActiveCompanionTimeline('integrated-alex').vh2.gifts?.policy.cashAllowed&&getActiveCompanionTimeline('integrated-alex').vh2.gifts.currency==='GBP');
  await page.waitForFunction(()=>!vh2PollLocks.has(getActiveCompanionTimeline('integrated-alex').id));
  await page.evaluate(()=>vhOpenGiftSheet(getCompanion('integrated-alex')));await page.locator('[data-gift-choice=cash]').click();await page.locator('[data-send-gift] button').click();
  await page.waitForFunction(()=>getActiveCompanionTimeline('integrated-alex').vh2.gifts?.records.length===1);await page.locator('#cc-gift-close').click();
  assert.equal(await page.evaluate(()=>getActiveCompanionTimeline('integrated-alex').vh2.gifts.records[0].amountMinor),1000);
  await page.waitForFunction(()=>!vh2PollLocks.has(getActiveCompanionTimeline('integrated-alex').id));
  await revealSummary(page.locator('summary').filter({hasText:'Trips & temporary stays'}));
  await page.getByLabel('Trip name',{exact:true}).fill('A short visit');
  await page.getByLabel('Trip stop',{exact:true}).selectOption(await page.evaluate(()=>getActiveCompanionTimeline('integrated-alex').vh2.present.placeId));
  await page.getByRole('button',{name:'Plan trip',exact:true}).click();
  await page.waitForFunction(()=>!!getActiveCompanionTimeline('integrated-alex').vh2.travel?.activeId);
  await revealSummary(page.locator('summary').filter({hasText:'Trips & temporary stays'}));
  await page.getByRole('button',{name:'Cancel trip',exact:true}).click();
  await page.waitForFunction(()=>getActiveCompanionTimeline('integrated-alex').vh2.travel?.activeId===null);
  await revealSummary(page.locator('summary').filter({hasText:'Life expression & spontaneous plans'}));
  await page.locator('[data-agency-enabled]').check();
  await page.getByLabel('Interest in taking photos',{exact:true}).fill('72');
  await page.getByRole('button',{name:'Save life expression',exact:true}).click();
  await page.waitForFunction(()=>getActiveCompanionTimeline('integrated-alex').vh2.agency?.policy.captureInterest===72);
  assert.equal(await page.evaluate(()=>getActiveCompanionTimeline('integrated-alex').vh2.agency.policy.enabled),true);
  await page.evaluate(async()=>{const c=getCompanion('integrated-alex'),t=getActiveCompanionTimeline(c.id);generateCompanionPhoto=async()=> 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jRZkAAAAASUVORK5CYII=';await vh2Enqueue(t,'capture_photo',{scene:'A saved moment rendered later',captureType:'front_camera_selfie',destination:'gallery'});await vh2Poll(c,t);});
  await revealSummary(page.locator('summary').filter({hasText:'Photo capture preview'}));
  await page.getByRole('button',{name:'Render saved moment',exact:true}).click();await page.locator('[data-submit-render]').click();
  await page.waitForFunction(()=>getActiveCompanionTimeline('integrated-alex').vh2.photos?.filter(p=>['stored','delivered'].includes(p.status)).length===4);
  await page.locator('#vh-photo-review [data-close]').click();await page.evaluate(()=>vhOpenWorkspace('media'));await publishing.getByRole('button',{name:'Load earlier gallery photos',exact:true}).click();
  await page.waitForFunction(()=>getActiveCompanionTimeline('integrated-alex').vh2.libraryPhotos?.length>=3);
  await revealSummary(page.locator('summary').filter({hasText:'Autonomous exploration'}));
  await page.getByLabel('Custom Interest tags',{exact:true}).fill('art, parks');await page.getByLabel('Custom Interest tags',{exact:true}).press('Enter');
  await page.getByRole('button',{name:'Save exploration',exact:true}).click();
  await page.waitForFunction(()=>getActiveCompanionTimeline('integrated-alex').vh2.exploration.policy.interests.includes('art'));
  await revealSummary(page.locator('summary').filter({hasText:'World feeds & awareness'}));
  await page.getByLabel('World feed format',{exact:true}).selectOption('gtfs_rt');
  assert(await page.getByLabel('Realtime schedule source',{exact:true}).isVisible());
  assert.equal(await page.getByLabel('Refresh interval (minutes)',{exact:true}).inputValue(),'1');
  assert(!await page.getByLabel('Departure terminal / stop ID',{exact:true}).isVisible());
  await page.getByLabel('World feed format',{exact:true}).selectOption('aviationstack');
  assert(!await page.getByLabel('Public feed URL',{exact:true}).isVisible());
  assert(await page.getByLabel('Departure terminal / stop ID',{exact:true}).isVisible());
  await page.getByLabel('World feed format',{exact:true}).selectOption('flights_json');
  assert(await page.getByLabel('Departure terminal / stop ID',{exact:true}).isVisible());
  await page.getByLabel('World feed format',{exact:true}).selectOption('openliga');
  assert(await page.getByLabel('Sports score result type ID (league-defined)',{exact:true}).isVisible());
  await page.getByLabel('World feed format',{exact:true}).selectOption('rss');
  assert.equal(await page.getByLabel('Refresh interval (minutes)',{exact:true}).inputValue(),'60');
  await page.getByLabel('Public feed URL',{exact:true}).fill('https://example.org/feed');
  await page.getByRole('button',{name:'Add world feed',exact:true}).click();
  await page.waitForFunction(()=>getActiveCompanionTimeline('integrated-alex').vh2.signals?.sources.length===1);
  await revealSummary(page.locator('summary').filter({hasText:'Asset bible',exact:true}));
  await page.getByLabel('Reference label',{exact:true}).fill('Canonical face');
  await page.getByLabel('Custom Reference tags (face, profile, mirror_selfie…)',{exact:true}).fill('face');await page.getByLabel('Custom Reference tags (face, profile, mirror_selfie…)',{exact:true}).press('Enter');
  await page.getByLabel('Upload reference image',{exact:true}).setInputFiles({name:'face.png',mimeType:'image/png',buffer:Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jRZkAAAAASUVORK5CYII=','base64')});
  await page.evaluate(()=>{document.activeElement?.blur();vh2RenderControls(getCompanion('integrated-alex'));});
  await page.getByRole('button',{name:'Add reference for review',exact:true}).click();
  await page.waitForFunction(()=>getActiveCompanionTimeline('integrated-alex').vh2.bible?.entries.length===1);
  await revealSummary(page.locator('summary').filter({hasText:'Asset bible',exact:true}));
  await page.getByRole('button',{name:'Approve reference',exact:true}).click();
  await page.waitForFunction(()=>getActiveCompanionTimeline('integrated-alex').vh2.bible.entries[0].status==='approved');
  await revealSummary(page.locator('summary').filter({hasText:'Asset bible',exact:true}));
  await page.evaluate(()=>{window.__bibleViews=[];const original=generateCompanionPhoto;generateCompanionPhoto=async(c,scene,options)=>{if(options.photoContext?.referenceStudy){if(!options.bibleReferences?.length)throw Error('Missing approved seed reference');window.__bibleViews.push(options.photoContext.referenceStudy);}return original(c,scene,options);};});
  await page.getByRole('button',{name:'Generate missing identity views',exact:true}).click();
  await page.waitForFunction(()=>getActiveCompanionTimeline('integrated-alex').vh2.bible.entries.length===5);
  assert.equal(await page.evaluate(()=>getActiveCompanionTimeline('integrated-alex').vh2.bible.entries.filter(e=>e.status==='pending').length),4);
  assert.deepEqual(await page.evaluate(()=>window.__bibleViews),['front_face','three_quarter','profile','full_body']);
  await revealSummary(page.locator('summary').filter({hasText:'Finances & recurring costs',exact:true}));
  await page.getByLabel('Recurring daily expenses',{exact:true}).fill('15');
  await page.getByRole('button',{name:'Save finances',exact:true}).click();
  await page.waitForFunction(()=>getActiveCompanionTimeline('integrated-alex').vh2.finance.policy.dailyExpense===15);
  await revealSummary(page.locator('summary').filter({hasText:'Procedural closet & style profiles',exact:true}));
  await page.getByLabel('Style name',{exact:true}).fill('Everyday');
  await page.getByLabel('top options (separate with semicolons)',{exact:true}).fill('Blue tee; Green tee');
  await page.getByLabel('bottom options (separate with semicolons)',{exact:true}).fill('Jeans');
  await page.getByRole('button',{name:'Add style profile',exact:true}).click();
  await page.waitForFunction(()=>getActiveCompanionTimeline('integrated-alex').vh2.closet.styles.length===1);
  await revealSummary(page.locator('summary').filter({hasText:'Room zones & visual continuity',exact:true}));
  await page.getByLabel('Zone parent place',{exact:true}).selectOption('home');
  await page.getByLabel('Zone name',{exact:true}).fill('Reading corner');
  await page.getByLabel('Zone description',{exact:true}).fill('Blue sofa beside a tall lamp.');
  await page.getByRole('button',{name:'Add room zone',exact:true}).click();
  await page.waitForFunction(()=>getActiveCompanionTimeline('integrated-alex').vh2.visual.zones.length===1);
  await page.getByRole('button',{name:'Enter Reading corner',exact:true}).click();
  await page.waitForFunction(()=>!!getActiveCompanionTimeline('integrated-alex').vh2.visual.zoneId);
  assert.match(await page.evaluate(()=>buildCompanionPhotoPrompt(getCompanion('integrated-alex'),'A room',{photoContext:{zoneId:'test-zone',zoneDescription:'Blue sofa beside a tall lamp.'}})),/Current room zone: Blue sofa beside a tall lamp/);
  await revealSummary(page.locator('summary').filter({hasText:'Background images & routes',exact:true}));
  await page.evaluate(()=>{providerAuthHeaders=()=>({Authorization:'Bearer OFFLINE_IMAGE_KEY'});});
  await page.getByLabel('Enable background image generation (provider credits)',{exact:true}).check();
  await page.getByLabel('Background image model',{exact:true}).fill('fixture/image');
  assert.deepEqual(await page.getByLabel('Background image provider',{exact:true}).locator('option').evaluateAll(options=>options.map(o=>o.value)),['openrouter','gemini','magnific','higgsfield']);
  await page.getByRole('button',{name:'Save background rendering',exact:true}).click();
  await page.waitForFunction(()=>getActiveCompanionTimeline('integrated-alex').vh2.imageProvider?.enabled);
  await page.evaluate(async()=>{const c=getCompanion('integrated-alex'),t=getActiveCompanionTimeline(c.id);await vh2Enqueue(t,'capture_photo',{scene:'An offline background fixture',destination:'gallery'});await vh2Poll(c,t);});
  await page.waitForFunction(()=>getActiveCompanionTimeline('integrated-alex').vh2.photos.some(p=>p.scene==='An offline background fixture'&&p.status==='captured'));
  await page.evaluate(()=>vh2RenderControls(getCompanion('integrated-alex')));
  await page.evaluate(()=>vhOpenWorkspace('media'));
  const photoDetails=page.locator('details').filter({has:page.locator('summary').filter({hasText:'Photo capture preview',exact:true})}).last();
  if(!await photoDetails.evaluate(el=>el.open))await photoDetails.locator('summary').first().click();
  await page.getByRole('button',{name:'Render in background',exact:true}).last().click();
  // This harness disables Horde's agency timer above; refresh its read-only projection explicitly.
  for(let attempt=0;attempt<20;attempt++){
   await page.evaluate(()=>vh2Poll(getCompanion('integrated-alex')));
   if(await page.evaluate(()=>getActiveCompanionTimeline('integrated-alex').vh2.providerJobs?.some(j=>j.status==='succeeded')))break;
   await new Promise(resolve=>setTimeout(resolve,1000));
  }
  assert(await page.evaluate(()=>getActiveCompanionTimeline('integrated-alex').vh2.providerJobs?.some(j=>j.status==='succeeded')),'background image imported without browser rendering');
  await page.evaluate(()=>switchView('companionChat'));
  const profileDetails=page.locator('#cc-profile-details');
  if(!await profileDetails.evaluate(el=>el.open))await profileDetails.locator('summary').click();
  await page.locator('[data-vh2-profile-name]').fill('Sam');
  await page.locator('[data-vh2-profile-text]').fill('I live in London and enjoy music.');
  await page.locator('[data-vh2-profile-save]').click();
  await page.waitForFunction(()=>getActiveCompanionTimeline('integrated-alex').vh2.playerProfile?.name==='Sam');
  await page.evaluate(()=>{getCompanion('integrated-alex').photoDirection='Keep the framing playful and imperfect.';});
  await page.evaluate(()=>vhOpenWorkspace('recovery'));
  await page.getByRole('button',{name:'Apply Studio personality, chat & photo settings',exact:true}).click();
  await page.waitForFunction(async()=>{const t=getActiveCompanionTimeline('integrated-alex');if(t.vh2.outbox.length)return false;const p=await mcpBridgeRequest('/vh2/projection?worldId='+encodeURIComponent(t.vh2.worldId));return p.state.truth.companion.photoDirection==='Keep the framing playful and imperfect.';});
  await revealSummary(page.locator('summary').filter({hasText:'Personal preferences & boundaries',exact:true}));
  await page.getByLabel('Firm boundaries',{exact:true}).fill('Respect a refusal; no pressure.');
  await page.getByLabel('Openness in conversation',{exact:true}).fill('32');
  await page.getByRole('button',{name:'Save personal preferences',exact:true}).click();
  await page.waitForFunction(()=>getActiveCompanionTimeline('integrated-alex').vh2.personalPreferences?.openness===32);
  assert.equal(await page.evaluate(async()=>{const t=getActiveCompanionTimeline('integrated-alex');const p=await mcpBridgeRequest('/vh2/projection?worldId='+encodeURIComponent(t.vh2.worldId));return p.state.truth.companion.personalPreferences.boundaries;}),'Respect a refusal; no pressure.');
  await revealSummary(page.locator('summary').filter({hasText:'Scheduled transport',exact:true}));
  await page.getByLabel('Service name',{exact:true}).fill('Fixture train');
  await page.evaluate(()=>vh2RenderControls(getCompanion('integrated-alex')));
  assert.equal(await page.getByLabel('Service name',{exact:true}).inputValue(),'Fixture train','refresh preserves the focused draft');
  await page.getByLabel('Service destination',{exact:true}).selectOption('cafe');
  await page.getByRole('button',{name:'Save scheduled service',exact:true}).click();
  await page.waitForFunction(()=>getActiveCompanionTimeline('integrated-alex').vh2.transportServices.length===1);
  await revealSummary(page.locator('summary').filter({hasText:'Travel disruption recovery',exact:true}));
  await page.getByLabel('Find replacement routes automatically',{exact:true}).check();
  await page.getByLabel('Maximum replacement transport spending',{exact:true}).fill('35');
  await page.getByRole('button',{name:'Save travel recovery',exact:true}).click();
  await page.waitForFunction(()=>getActiveCompanionTimeline('integrated-alex').vh2.travel.recoveryPolicy.enabled&&getActiveCompanionTimeline('integrated-alex').vh2.travel.recoveryPolicy.maxSpend===35);
  await revealSummary(page.locator('summary').filter({hasText:'Supporting-person network',exact:true}));
  await page.getByLabel('Enable private supporting-person encounters',{exact:true}).check();
  await page.getByLabel('Allow small-group plans between established friends',{exact:true}).check();
  await page.getByRole('button',{name:'Save supporting-person network',exact:true}).click();
  await page.waitForFunction(()=>getActiveCompanionTimeline('integrated-alex').vh2.people?.network?.enabled);
  await revealSummary(page.locator('summary').filter({hasText:'Flight connection — Aviationstack',exact:true}));
  await page.getByLabel('Aviationstack API key',{exact:true}).fill('BROWSER_OFFLINE_FLIGHT_KEY');
  await page.getByLabel('Maximum flight API requests per day',{exact:true}).fill('2');
  await page.getByRole('button',{name:'Save flight connection',exact:true}).click();
  await page.waitForFunction(()=>getActiveCompanionTimeline('integrated-alex').vh2.flightProvider?.hasKey);
  assert.equal(await page.evaluate(()=>getActiveCompanionTimeline('integrated-alex').vh2.flightProvider.enabled),false);
  assert(!JSON.stringify(await page.evaluate(()=>getActiveCompanionTimeline('integrated-alex').vh2)).includes('BROWSER_OFFLINE_FLIGHT_KEY'));


  await revealSummary(page.locator('summary').filter({hasText:'Overnight visits & vacations',exact:true}));
  await page.getByLabel('Opportunity name',{exact:true}).fill('Visit home');
  await page.getByLabel('Accommodation is permitted',{exact:true}).check();
  await page.getByRole('button',{name:'Add overnight opportunity',exact:true}).click();
  await page.waitForFunction(()=>getActiveCompanionTimeline('integrated-alex').vh2.episodes.opportunities.length===1);
  await revealSummary(page.locator('summary').filter({hasText:'Build room, person, garment & pose references',exact:true}));
  await page.getByLabel('Study role',{exact:true}).selectOption('place');
  await page.getByLabel('Reference visual details',{exact:true}).fill('A blue room with a window on the left.');
  await page.evaluate(()=>{generateCompanionPhoto=async(c,scene,options)=>{if(options.photoContext?.assetStudy?.role!=='place')throw Error('Expected linked room study');if(options.bibleReferences?.length)throw Error('A new room must not receive unrelated identity refs');return 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jRZkAAAAASUVORK5CYII=';};});
  await page.getByRole('button',{name:'Generate reference for review',exact:true}).click();
  await page.waitForFunction(()=>getActiveCompanionTimeline('integrated-alex').vh2.bible.entries.some(e=>e.role==='place'&&e.status==='pending'));
  await revealSummary(page.locator('summary').filter({hasText:'Timeline backup & recovery'}));
  if(await page.evaluate(()=>getActiveCompanionTimeline('integrated-alex').vh2.running))await page.locator('[data-vh2-pause]').click();
  await page.waitForFunction(()=>!getActiveCompanionTimeline('integrated-alex').vh2.running);
  await revealSummary(page.locator('summary').filter({hasText:'Bring prior conversation into VH2',exact:true}));
  await page.getByLabel('Prior human archive',{exact:true}).setInputFiles('scratch/fixtures/vh2/portable-v3.json');
  await page.waitForFunction(()=>document.querySelector('[aria-label="Prior conversation"]')?.options.length===2);
  await page.getByLabel('Confirm historical player mapping',{exact:true}).check();
  await page.getByRole('button',{name:'Import reviewed conversation',exact:true}).click();
  await page.waitForFunction(()=>getActiveCompanionTimeline('integrated-alex').vh2.legacyHistory?.count===1);
  const backupPanel=page.locator('details').filter({has:page.locator('summary').filter({hasText:'Timeline backup & recovery',exact:true})}).last();
  if(!await backupPanel.evaluate(el=>el.open))await backupPanel.locator('summary').first().click();
  const [backup]=await Promise.all([page.waitForEvent('download'),page.getByRole('button',{name:'Download VH2 timeline backup',exact:true}).click()]);await backup.saveAs('/tmp/vh2-browser-backup.vh2.gz');
  recoveryServer=spawn('python3',['scratch/vh2_browser_server.py'],{stdio:['ignore','pipe','pipe']});
  const recoveryPort=await new Promise((resolve,reject)=>{recoveryServer.stdout.once('data',d=>resolve(Number(String(d).trim())));recoveryServer.once('exit',c=>reject(Error('Recovery server exit '+c)));});
  const recoveryBase=`http://127.0.0.1:${recoveryPort}`,recovery=await browser.newPage();recovery.on('pageerror',e=>errors.push(e.message));
  await recovery.route('**/*',route=>route.request().url().startsWith(recoveryBase)?route.continue():route.abort());
  await recovery.goto(recoveryBase+'/index.html');await recovery.waitForFunction(()=>typeof companionAgencyTimer!=='undefined'&&!!companionAgencyTimer);
  await recovery.evaluate(base=>{clearInterval(companionAgencyTimer);clearInterval(companionAlwaysOnTimer);mcpBridgeBase=()=>base;const c=normalizeCompanion({id:'recovery-placeholder',name:'Recovery'});state.companions=[c];state.activeCompanionId=c.id;ensureCompanionTimelineStore(c.id);hideGlobalSettings();switchView('companionChat');renderCompanionThread();},recoveryBase);
  await recovery.evaluate(()=>vhOpenWorkspace('recovery'));
  await revealSummary(recovery.locator('summary').filter({hasText:'Timeline backup & recovery'}));
  await recovery.getByLabel('Restore a VH2 timeline archive',{exact:true}).setInputFiles('/tmp/vh2-browser-backup.vh2.gz');
  await recovery.waitForFunction(id=>getActiveCompanionTimeline('integrated-alex')?.vh2?.worldId===id,w);
  await recovery.waitForFunction(()=>getActiveCompanionTimeline('integrated-alex').vh2?.photos?.length>=3);
  assert.equal(await recovery.evaluate(()=>getActiveCompanionTimeline('integrated-alex').vh2.running),false);
  assert.equal(await recovery.evaluate(()=>getActiveCompanionTimeline('integrated-alex').vh2.bible.entries.length),6);
  assert.equal(await recovery.evaluate(()=>getActiveCompanionTimeline('integrated-alex').vh2.signals.sources.length),1);
  assert.equal(await recovery.evaluate(()=>getActiveCompanionTimeline('integrated-alex').vh2.autoReplies),false);
  assert.equal(await recovery.evaluate(()=>getActiveCompanionTimeline('integrated-alex').vh2.finance.policy.dailyExpense),15);
  assert.equal(await recovery.evaluate(()=>getActiveCompanionTimeline('integrated-alex').vh2.closet.styles.length),1);
  assert.equal(await recovery.evaluate(()=>getActiveCompanionTimeline('integrated-alex').vh2.playerProfile.name),'Sam');
  assert.equal(await recovery.evaluate(()=>getActiveCompanionTimeline('integrated-alex').vh2.personalPreferences.openness),32);
  assert.equal(await recovery.evaluate(()=>getActiveCompanionTimeline('integrated-alex').vh2.legacyHistory.count),1);
  assert.equal(await recovery.evaluate(()=>getActiveCompanionTimeline('integrated-alex').vh2.transportServices.length),1);
  assert.equal(await recovery.evaluate(()=>getActiveCompanionTimeline('integrated-alex').vh2.travel.recoveryPolicy.maxSpend),35);
  assert.equal(await recovery.evaluate(()=>getActiveCompanionTimeline('integrated-alex').vh2.people.network.enabled),true);
  assert.equal(await recovery.evaluate(()=>getActiveCompanionTimeline('integrated-alex').vh2.people.network.policy.groupPlansEnabled),true);
  assert.equal(await recovery.evaluate(()=>getActiveCompanionTimeline('integrated-alex').vh2.flightProvider.hasKey),false);
  assert.equal(await recovery.evaluate(()=>getActiveCompanionTimeline('integrated-alex').vh2.episodes.opportunities.length),1);
  assert.equal(await recovery.evaluate(()=>getActiveCompanionTimeline('integrated-alex').vh2.imageProvider.enabled===true),false);
  await recovery.evaluate(()=>switchView('companions'));
  const recoveredCard=recovery.locator('.vh-card').filter({hasText:'Alex'});
  assert.match(await recoveredCard.innerText(),/Life paused/);
  await recoveredCard.getByRole('button',{name:'Review VH2 setup',exact:true}).click();
  assert.equal(await recovery.locator('#vh-workspace-view').isVisible(),true);assert.equal(await recovery.locator('#vh-workspace-title').innerText(),'Providers & feeds');
  assert.deepEqual(errors,[]);
  const [workspace]=await Promise.all([page.waitForEvent('download'),page.evaluate(()=>exportFullBackup())]);
  await workspace.saveAs('/tmp/vh2-studio-workspace.json');
  const workspaceData=JSON.parse(require('node:fs').readFileSync('/tmp/vh2-studio-workspace.json','utf8'));
  assert.equal(workspaceData.vh2ServiceArchives.length,1,'Studio backup includes the linked service timeline');
  assert(workspaceData.companions[0].basePhoto.startsWith('data:image/'),'browser reference source included');
  assert(!JSON.stringify(workspaceData.globalSettings).includes('LOCAL_TEST_KEY'),'credentials excluded');
  const decoded=JSON.parse(require('node:zlib').gunzipSync(Buffer.from(workspaceData.vh2ServiceArchives[0],'base64')));
  assert(decoded,'embedded timeline is a readable compressed archive');
  console.log('PASS existing Horde UI: mocked chat/photos, frozen-moment rendering, social/history, life expression policy, population authoring/removal, independent life, social progression and money gifts, shared plans, autonomous exploration controls, feed setup, reviewed multi-view bible generation, backup download and paused restore into a separate service');
 }finally{if(browser)await browser.close();server.kill();if(recoveryServer)recoveryServer.kill();}
})().catch(e=>{console.error(e);process.exitCode=1;});
