'use strict';
const assert=require('node:assert/strict'),kernel=require('../vh2-kernel-worker'),plans=require('../vh2-plans-engine'),bonds=require('../vh2-social-bonds'),core=require('../vh-simulation-core');
const MIN=60000,START=Date.UTC(2026,8,11,17);
function fixture(seed='social'){
 const places=[{id:'home',label:'Alex home',kind:'home',encounterScope:'nearby'},{id:'jo_home',label:'Jo home',kind:'home',encounterScope:'nearby'},{id:'lee_home',label:'Lee home',kind:'home',encounterScope:'nearby'},{id:'park',label:'Community park',kind:'social',encounterScope:'nearby'}];
 const travelLegs=places.flatMap(a=>places.filter(b=>b.id!==a.id).map(b=>({id:a.id+'_'+b.id,from:a.id,to:b.id,mode:'WALK',minutes:5,cost:0,source:'fixture'})));
 const socialCircle=['jo','lee'].map(id=>({id,name:id==='jo'?'Jo':'Lee',age:25,closeness:100,trust:20,tension:0,contactWindows:[{days:[0,1,2,3,4,5,6],startMinute:0,endMinute:1440}]}));
 let c=kernel.run({create:true,name:'Alex',entityId:seed,now:START,profile:{age:24,timezoneOffsetMinutes:0,lifeProfile:{places,socialCircle,travelLegs,weeklySchedule:[],sleepPolicy:{enabled:false},activityOptions:[],world:{transport:{enabled:true,goalTravel:true,modes:['WALK'],budget:100},people:[]}}}}).companion;
 c.lifeRuntime.world.placeId='home';c.lifeRuntime.world.balance=100;c.lifeProfile.weeklySchedule=[];c.humanDynamics.energy=90;c.humanDynamics.hunger=20;c.humanDynamics.stress=0;c.humanDynamics.socialNeed=80;c.vh2Health.policy.enabled=false;
 c.vh2Geography.enabled=true;c.vh2Travel.residenceId='home';c.vh2Decision.policy.temperature=1;c.vh2Decision.policy.exploration=0;
 for(const id of ['jo','lee'])c.vh2People.actors[id]={id,policy:{homePlaceId:id+'_home',foodPlaceIds:[id+'_home'],leisurePlaceIds:['park'],paidPlaceIds:[],modes:['WALK'],ownsCar:false,ownsBicycle:false,curiosity:10,conscientiousness:70,temperature:1,sleepStart:23,sleepEnd:7,mealCost:2,incomePerHour:0,dailyExpense:0},placeId:id+'_home',balance:100,energy:90,hunger:20,stress:0,boredom:80,socialNeed:80,lastAt:START,sequence:0,started:false,action:null,journey:null,pending:null,remaining:[],visits:{},health:{policy:{enabled:false}}};
 c.vh2People.network={enabled:false,pairs:{},events:[],lastAt:START};plans.ensure(c);return c;
}
function advance(c,minutes,from=START,step=1){for(let t=from+step*MIN;t<=from+minutes*MIN;t+=step*MIN)c=kernel.run({companion:c,now:t}).companion;return c;}
function propose(c,id,extra={}){return plans.command(c,{type:'propose_plan',planId:id,personId:'jo',personIds:['jo','lee'],placeId:'park',label:'Meet at the park',startsAt:START+15*MIN,endsAt:START+70*MIN,durationMinutes:15,...extra},START);}
// A declined guest does not cancel two willing participants. Every actual attendee earns evidence.
let c=fixture();let p=propose(c,'partial');p.responses.lee={at:START,decision:'decline'};p.responses.jo={at:START,decision:'accept'};c=advance(c,75);p=c.vh2Plans.plans.find(p=>p.id==='partial');assert.equal(p.status,'completed');assert.ok(p.attendance.jo.minutes>=5);assert.equal(p.attendance.lee,undefined);assert.equal(c.vh2SocialBonds.pairs.lee.self.meetings,0);assert.equal(c.vh2SocialBonds.pairs.jo.self.meetings,1);
// Strong group fixture executes real travel; additional guests get individual credit.
c=fixture('group-evidence');p=propose(c,'group');for(const id of [c.id,'jo','lee'])p.responses[id]={at:START,decision:'accept'};c=advance(c,75);p=c.vh2Plans.plans.find(p=>p.id==='group');assert.equal(p.status,'completed');assert.equal(c.vh2SocialBonds.pairs.jo.self.meetings,1);assert.equal(c.vh2SocialBonds.pairs.lee.self.meetings,1);assert.ok(c.vh2People.events.some(e=>e.kind==='person_departed'));assert.ok(c.lifeRuntime.world.events.some(e=>e.kind==='arrival')||c.vh2Travel.events.some(e=>e.kind==='arrived'||e.kind==='stay_started'));
// Leaving has individual consequences; other accepted guests remain committed.
c=fixture('leave');p=propose(c,'leave',{activityKind:'hosted_event',hostId:c.id,placeId:'home',durationMinutes:30});for(const id of [c.id,'jo','lee'])p.responses[id]={at:START,decision:'accept'};c=advance(c,30);p=c.vh2Plans.plans.find(p=>p.id==='leave');plans.leave(c,p,'jo',START+30*MIN,'Preferred to head home.');assert.equal(plans.committed(c,p,'jo'),false);assert.equal(plans.committed(c,p,'lee'),true);c=advance(c,45,START+30*MIN);p=c.vh2Plans.plans.find(p=>p.id==='leave');assert.ok(p.attendance.jo.minutes>0);assert.ok(p.attendance.lee.minutes>=p.attendance.jo.minutes);assert.ok(c.vh2SocialBonds.pairs.jo.self.meetings>0);
// A remote call reserves both participants at their respective locations.
c=fixture('call');p=propose(c,'call',{personIds:['jo'],modality:'call',placeId:'',startsAt:START+15*MIN,endsAt:START+40*MIN,durationMinutes:12});p.responses[c.id]={at:START,decision:'accept'};p.responses.jo={at:START,decision:'accept'};c=advance(c,45);p=c.vh2Plans.plans.find(p=>p.id==='call');assert.equal(p.status,'completed');assert.ok(p.attendance.jo.minutes>=10);assert.ok(c.vh2People.events.some(e=>e.action==='call'));assert.equal(c.vh2People.events.some(e=>e.kind==='person_departed'&&e.at>=p.attendance.jo.arrivedAt&&e.at<p.completedAt&&e.personId==='jo'),false);
// Contact windows belong to the recipient's clock. Calls cannot bypass sleep or work.
function remoteCall(seed,windowStart=13*60){const x=fixture(seed);x.vh2Travel.places.jo_home={timeZone:'America/New_York'};x.lifeProfile.socialCircle.find(p=>p.id==='jo').contactWindows=[{days:[5],startMinute:windowStart,endMinute:windowStart+60}];const plan=propose(x,seed,{personIds:['jo'],initiatorId:'jo',modality:'call',placeId:'',startsAt:START+15*MIN,endsAt:START+35*MIN,durationMinutes:12});return [x,plan];}
[c,p]=remoteCall('recipient-clock');p.responses[c.id]={at:START,decision:'accept'};plans.before(c,START,core);assert.equal(p.status,'accepted','13:00 Eastern contact window is open at 17:00 UTC');
[c,p]=remoteCall('closed-recipient-clock',17*60);plans.before(c,START,core);assert.equal(p.status,'proposed','17:00 recipient window is closed even though main clock says17:00');assert.deepEqual(p.responses,{});
[c,p]=remoteCall('recipient-work');c.lifeProfile.world.people=[{personId:'jo',placeId:'jo_home',days:[5],start:13*60,end:14*60,activity:'Remote work',flexibility:'fixed'}];plans.before(c,START,core);assert.equal(p.status,'declined');assert.match(p.responses.jo.reason,/obligation/);
[c,p]=remoteCall('main-work');c.lifeProfile.weeklySchedule=[{id:'work',days:[5],startMinute:17*60,endMinute:18*60,availability:'busy',flexibility:'fixed',placeId:'home'}];plans.before(c,START,core);assert.equal(p.status,'declined');assert.match(p.responses[c.id].reason,/fixed commitment/);
[c,p]=remoteCall('recipient-sleep');c.vh2People.actors.jo.action={kind:'sleep',endsAt:START+60*MIN};plans.before(c,START,core);assert.equal(p.status,'proposed');assert.deepEqual(p.responses,{});
[c,p]=remoteCall('main-sleep');c.humanDynamics.sleep={...c.humanDynamics.sleep,stage:'asleep'};plans.before(c,START,core);assert.equal(p.status,'proposed');assert.deepEqual(p.responses,{});
// Known adult ages, host access, two fresh decisions and actual private co-presence are required.
c=fixture('private');plans.ensure(c).privateVisitPermissions=[{personId:'jo',personAge:25,enabled:true,selfWillingness:100,otherWillingness:100,allowIntimacy:true}];p=propose(c,'private',{personIds:['jo'],activityKind:'private_visit',hostId:'jo',placeId:'jo_home',durationMinutes:10});c=advance(c,80);p=c.vh2Plans.plans.find(p=>p.id==='private');assert.equal(p.status,'completed');assert.equal(p.privateOutcome.kind,'mutual_private_intimacy');assert.ok(Object.values(p.intimacyResponses).every(r=>r.decision==='accept'));assert.ok(p.returnGoalId);assert.ok(c.lifeRuntime.activities.goals.some(g=>g.id===p.returnGoalId&&g.requiredPlaceId==='home'));
c=fixture('minor');c.lifeProfile.socialCircle[0].age=17;plans.ensure(c).privateVisitPermissions=[{personId:'jo',personAge:25,enabled:true,selfWillingness:100,otherWillingness:100,allowIntimacy:true}];p=propose(c,'minor',{personIds:['jo'],activityKind:'private_visit',hostId:'jo',placeId:'jo_home'});c=advance(c,30);p=c.vh2Plans.plans.find(p=>p.id==='minor');assert.notEqual(p.status,'completed');assert.equal(p.privateOutcome,undefined);
// Withdrawal during private time cannot be turned into a completed intimate outcome.
c=fixture('withdrawal');plans.ensure(c).privateVisitPermissions=[{personId:'jo',personAge:25,enabled:true,selfWillingness:100,otherWillingness:100,allowIntimacy:true}];propose(c,'withdrawal',{personIds:['jo'],activityKind:'private_visit',hostId:'jo',placeId:'jo_home',durationMinutes:20});let withdrawalAt;
for(let m=1;m<=65;m++){c=advance(c,1,START+(m-1)*MIN);p=c.vh2Plans.plans.find(p=>p.id==='withdrawal');if(p.status==='active'&&p.attendance[c.id]?.minutes>=5){withdrawalAt=START+m*MIN;plans.leave(c,p,c.id,withdrawalAt,'Changed their mind.');break;}}
assert.ok(withdrawalAt);c=advance(c,10,withdrawalAt);p=c.vh2Plans.plans.find(p=>p.id==='withdrawal');assert.equal(p.privateOutcome,undefined);
// Restart is exact; main/peer membership determines conflicts.
c=fixture('restart');propose(c,'restart');c=advance(c,20);const copy=structuredClone(c);assert.deepEqual(advance(c,20,START+20*MIN),advance(copy,20,START+20*MIN));
c=fixture();c.vh2Plans.plans.push({id:'unrelated',scope:'peers',people:['jo','lee'],status:'accepted',startsAt:START,endsAt:START+60*MIN});assert.equal(plans.conflicts(c,c.id,START,START+MIN),false);assert.equal(plans.conflicts(c,'lee',START,START+MIN),true);
// Invitations emerge from either participant's social need, not a required user message.
const outcomes=[];for(let seed=0;seed<12;seed++){let x=fixture('auto-'+seed);x.humanDynamics.socialNeed=0;Object.assign(plans.ensure(x).policy,{enabled:true,hostedEvents:true,socialNeedThreshold:50});x=advance(x,180);outcomes.push({seed,plans:x.vh2Plans.plans.map(p=>({initiator:p.initiatorId,kind:p.activityKind,status:p.status,mode:p.modality}))});}
assert.ok(outcomes.some(x=>x.plans.some(p=>p.initiator==='jo'||p.initiator==='lee')));assert.ok(outcomes.some(x=>x.plans.some(p=>p.mode==='call')));assert.ok(outcomes.some(x=>x.plans.some(p=>p.kind==='hosted_event')));assert.ok(new Set(outcomes.map(x=>JSON.stringify(x.plans))).size>1);
// A noticed public event becomes one coordinated outing, not a parallel solo visit.
c=fixture('event');Object.assign(plans.ensure(c).policy,{enabled:true,hostedEvents:true});c.vh2Signals={signals:[],events:[],known:[{id:'game',type:'calendar_event',eventStatus:'listed',title:'Home football match',placeId:'park',startsAt:START+60*MIN,endsAt:START+150*MIN,expiresAt:START+180*MIN,requiresTicket:true,accessConfirmed:true}]};c=advance(c,180);const outing=c.vh2Plans.plans.find(p=>p.sourceSignalId==='game');assert.ok(outing);assert.equal(outing.activityKind,'event_outing');assert.ok(Object.keys(outing.attendance).length>=2);assert.ok(!c.lifeRuntime.activities.goals.some(g=>g.sourceSignalId==='game'&&g.id!==outing.goalId&&g.status==='active'));
// A host can invite an established friend unknown to the main character. Real attendance
// permits introduction; a later private visit is independently decided and stays non-graphic.
let chain;
for(let seed=0;seed<24&&!chain;seed++){
 let x=fixture('party-stranger-'+seed);x.humanDynamics.socialNeed=0;Object.assign(plans.ensure(x).policy,{enabled:true,hostedEvents:true,privateVisits:true,privateVisitInterest:100,maxGuests:5});
 x.vh2Plans.privateVisitPermissions=['jo','lee'].map(personId=>({personId,personAge:25,enabled:false,selfWillingness:0,otherWillingness:0,allowIntimacy:false}));
 x.lifeProfile.places.push({id:'sam_home',label:'Sam home',kind:'home',encounterScope:'nearby'});for(const p of x.lifeProfile.places.filter(p=>p.id!=='sam_home'))for(const [from,to] of [[p.id,'sam_home'],['sam_home',p.id]])x.lifeProfile.travelLegs.push({from,to,mode:'WALK',minutes:5,cost:0,source:'fixture'});
 x.vh2People.actors.sam={...structuredClone(x.vh2People.actors.jo),id:'sam',placeId:'sam_home',policy:{...x.vh2People.actors.jo.policy,homePlaceId:'sam_home',privateVisitInterest:100},socialNeed:0};
 x.vh2Population={enabled:true,openness:100,residents:[{id:'sam',name:'Sam',age:25,placeId:'park',days:[0,1,2,3,4,5,6],start:0,end:1440,openness:100,sharedDescription:'Enjoys local events.'}],contacts:{},events:[],sequence:0};
 x.vh2People.network.pairs[JSON.stringify(['jo','sam'])]={people:['jo','sam'],sides:[{stage:'friend'},{stage:'friend'}]};
 x=advance(x,240);if(process.env.VH_AUDIT_DEBUG)console.log(JSON.stringify({seed,introduced:x.vh2Population.residents[0].introducedAt,plans:x.vh2Plans.plans.map(p=>({id:p.id,kind:p.activityKind,who:p.personId,people:p.people,status:p.status,attendance:p.attendance,responses:p.responses,privateConsidered:p.privateConsidered}))}));const visit=x.vh2Plans.plans.find(p=>p.activityKind==='private_visit'&&p.personId==='sam'&&p.status==='completed');if(visit)chain={x,visit,seed};
}
assert.ok(chain,'At least one seeded host -> stranger introduction -> separately accepted private visit chain must execute');assert.ok(chain.x.vh2Population.residents[0].introducedAt);assert.equal(chain.visit.privateOutcome.kind,'private_time');assert.ok(chain.visit.parentPlanId);assert.ok(chain.x.vh2Plans.plans.find(p=>p.id===chain.visit.parentPlanId).departures[chain.x.id]);assert.ok(chain.visit.returnGoalId);assert.ok(chain.x.lifeRuntime.activities.goals.some(g=>g.id===chain.visit.returnGoalId&&g.status==='completed'),'Return-home intention executes through normal routing');
console.log('PASS real group/call/private-visit participation, partial refusal, early departure, per-attendee bonds, routes, adult/privacy gates, return intentions, restart and 12-seed invitations');
console.log(JSON.stringify({invitationRuns:outcomes,connectedPartySeed:chain.seed}));
module.exports={fixture,advance,propose,START,MIN};
