'use strict';
const assert=require('node:assert/strict'),routing=require('../vh2-transport-engine'),travel=require('../vh2-travel-engine'),episodes=require('../vh2-episodes-engine');
const now=Date.parse('2026-09-10T09:00:00Z'),MIN=60000;
function fixture(seed=1){return {id:'traveller:'+seed,humanDynamics:{energy:80,hunger:10,stress:10},lifeProfile:{places:[{id:'home',kind:'home',label:'Home'},{id:'away',kind:'home',label:'Away'}],world:{transport:{enabled:true,transit:true,budget:1000}},travelLegs:[{from:'home',to:'away',mode:'TRANSIT',minutes:120,cost:30},{from:'away',to:'home',mode:'TRANSIT',minutes:120,cost:30}],weeklySchedule:[]},lifeRuntime:{world:{placeId:'home',balance:1000},activities:{}}};}
const c=fixture();c.lifeProfile.travelLegs=[];routing.ensure(c).services=[{id:'train',label:'Train',from:'home',to:'away',kind:'train',departsAt:now+10*MIN,arrivesAt:now+30*MIN,boardingMinutes:5,cost:20,status:'scheduled',source:'fixture'}];
assert.equal(travel.itinerary(c,[{placeId:'away',stayMinutes:0}],now)[0][0].serviceId,'train');
assert.equal(travel.itinerary(c,[{placeId:'away',stayMinutes:0}],now+6*MIN),null,'missed boarding window unavailable');
const r=travel.ensure(c);r.activeId='trip';r.trips.push({id:'trip',label:'Test',status:'planned',startsAt:now,legSequence:0,stops:[{placeId:'away',stayMinutes:0}]});
travel.tick(c,now,{});assert.equal(r.trips[0].status,'waiting');assert.equal(c.lifeRuntime.world.balance,1000);assert.equal(c.lifeRuntime.world.placeId,'home');travel.tick(c,now+10*MIN,{});assert.equal(c.lifeRuntime.world.balance,980);assert.equal(c.lifeRuntime.world.journey.arrivesAt,now+30*MIN);travel.tick(c,now+11*MIN,{});assert.equal(c.lifeRuntime.world.balance,980);
const cancelled=fixture();cancelled.lifeProfile.travelLegs=[];routing.ensure(cancelled).services=[{...c.vh2Transport.services[0]}];const tr=travel.ensure(cancelled);tr.activeId='cancel';tr.trips=[{id:'cancel',label:'Test',status:'planned',startsAt:now,legSequence:0,stops:[{placeId:'away',stayMinutes:0}]}];travel.tick(cancelled,now,{});cancelled.vh2Transport.services[0].status='cancelled';travel.tick(cancelled,now+MIN,{});assert.equal(tr.trips[0].status,'blocked');assert.equal(cancelled.lifeRuntime.world.balance,1000);
const local=(c,at)=>{const d=new Date(at);return {weekday:d.getUTCDay(),hour:d.getUTCHours(),minute:d.getUTCMinutes()};};
const seconds=fixture();seconds.lifeProfile.travelLegs=[];routing.ensure(seconds).services=[{...c.vh2Transport.services[0],departsAt:now+10*MIN+30000}];
const sr=travel.ensure(seconds);sr.activeId='seconds';sr.trips=[{id:'seconds',label:'Seconds',status:'planned',startsAt:now,legSequence:0,stops:[{placeId:'away',stayMinutes:0}]}];travel.tick(seconds,now,{});travel.tick(seconds,now+11*MIN,{});assert.equal(sr.trips[0].status,'travelling');assert.equal(seconds.lifeRuntime.world.journey.departedAt,now+10*MIN+30000);assert.equal(seconds.lifeRuntime.world.balance,980);
const outcomes=new Set();
for(let seed=0;seed<100;seed++){
 const x=fixture(seed),e=episodes.ensure(x);e.policy={...episodes.DEFAULTS,enabled:true,threshold:40};e.opportunities=[{id:'visit',label:'Visit hometown',enabled:true,stayAllowed:true,placeId:'away',availableFrom:now,availableUntil:now+7*86400000,minNights:1,maxNights:2,nightlyCost:30,interest:50}];episodes.advance(x,now,local,'available');outcomes.add(e.decisions[0]?.selected||'stay');
 const poor=fixture(seed),pe=episodes.ensure(poor);pe.policy={...e.policy,threshold:-100};pe.opportunities=e.opportunities;poor.lifeRuntime.world.balance=20;episodes.advance(poor,now,local,'available');assert.ok(!poor.vh2Travel?.activeId);
 const denied=fixture(seed),de=episodes.ensure(denied);de.policy={...e.policy,threshold:-100};de.opportunities=[{...e.opportunities[0],stayAllowed:false}];episodes.advance(denied,now,local,'available');assert.ok(!denied.vh2Travel?.activeId);
}
assert.equal(outcomes.size,2,'different seeds produce a visit or staying home');
const busy=fixture(),be=episodes.ensure(busy);be.policy={...episodes.DEFAULTS,enabled:true,threshold:-100};be.opportunities=[{id:'visit',label:'Visit',enabled:true,stayAllowed:true,placeId:'away',availableFrom:now,availableUntil:now+7*86400000,minNights:1,maxNights:1,nightlyCost:0,interest:100}];busy.lifeProfile.weeklySchedule=[{days:[4],startMinute:600,endMinute:601}];episodes.advance(busy,now,local,'available');assert.ok(!busy.vh2Travel?.activeId,'one-minute commitment prevents conflicting vacation');
console.log('PASS timetables, boarding deadlines, terminal waiting, single fares, cancellation, 100 overnight seeds, money, permission and commitments.');
