'use strict';
const assert=require('node:assert/strict'),{fixture,local,start,MIN}=require('./vh2_people_audit'),people=require('../vh2-people-engine'),net=require('../vh2-network-engine');
function sample(){const c=fixture(),a=c.vh2People.actors.sam;c.lifeProfile.socialCircle=[{id:'sam',name:'Sam'},{id:'jo',name:'Jo'},{id:'lee',name:'Lee'}];c.lifeRuntime.world.placeId='home';c.humanDynamics={sleep:{stage:'awake'}};a.policy.leisurePlaceIds=['home','park'];a.policy.temperature=1;for(const id of ['jo','lee'])c.vh2People.actors[id]={...structuredClone(a),id};c.vh2People.network={enabled:true,lastAt:start,pairs:{},events:[],policy:{groupPlansEnabled:true},dispositions:{}};return c;}
function matured(c){const n=net.ensure(c);for(const [a,b] of [['jo','lee'],['jo','sam'],['lee','sam']])n.pairs[JSON.stringify([a,b])]={people:[a,b],meetings:10,minutes:100,warmth:10,lastAt:start,lastPlaceId:'park',sides:[a,b].map(()=>({warmth:10,trust:5,strain:0,meetings:10,firstAt:start-8*86400000,lastAt:start,stage:'friend'}))};return c;}
// Each side has its own appraisal: guarded stress does not become the other's affection.
let c=sample();c.lifeProfile.travelLegs=[];for(const a of Object.values(c.vh2People.actors)){a.policy.leisurePlaceIds=['home'];a.started=true;a.action={kind:'leisure',endsAt:start+120*MIN};}c.vh2People.actors.sam.stress=90;c.vh2People.actors.jo.stress=0;c.vh2People.network.dispositions={sam:{sensitivity:100,openness:10},jo:{openness:100}};people.advance(c,start+120*MIN,local);const pair=c.vh2People.network.pairs[JSON.stringify(['jo','sam'])];assert(pair?.sides);assert.notEqual(pair.sides[0].warmth,pair.sides[1].warmth);
// No instant friends -> no spontaneous invitations.
c=sample();people.advance(c,start+12*60*MIN,local);assert.equal(net.peerPlans(c).length,0);
// Established friends can form plans, then physically travel to meet.
let found;
for(let seed=0;seed<8&&!found;seed++){c=matured(sample());c.id='group-'+seed;for(const id of Object.keys(c.vh2People.actors))c.vh2People.network.dispositions[id]={sociability:100};people.advance(c,start+12*60*MIN,local);if(net.peerPlans(c).some(p=>p.status==='completed'))found=c;}
assert(found,'At least one feasible meeting completes');assert(found.vh2People.events.some(e=>e.kind==='person_departed'),'Actual route traversal must occur');assert(net.peerPlans(found).some(p=>p.people.length===3),'Mutual friends may join as a third member');
// Co-location is insufficient: a specific shared meeting needs participation evidence.
c=sample();c.vh2People.network.plans=[{id:'fixture',people:['jo','sam'],placeId:'park',startsAt:start+20*MIN,endsAt:start+50*MIN,createdAt:start,status:'accepted',sharedMinutes:0}];c.lifeProfile.travelLegs=[];people.advance(c,start+60*MIN,local);assert.equal(net.peerPlans(c)[0].status,'missed');assert.equal(net.peerPlans(c)[0].sharedMinutes,0);assert.equal(c.lifeRuntime.world.placeId,'home');
// One large advance and minute stepping resolve the same private relationships and plans.
const bulk=matured(sample()),stepped=structuredClone(bulk);people.advance(bulk,start+1440*MIN,local);for(let t=start;t<=start+1440*MIN;t+=MIN)people.advance(stepped,t,local);assert.deepEqual(bulk,stepped);
// Only a physically witnessed meeting enters character context.
c=sample();let n=net.ensure(c);n.plans=[{id:'seen',people:['jo','sam'],placeId:'park',startsAt:start,endsAt:start+30*MIN,status:'active'}];for(const a of Object.values(c.vh2People.actors)){a.placeId='park';a.action={kind:'peer_meeting',peerPlanId:'seen'};}net.observe(c,start);assert.equal(n.observed.length,0);c.lifeRuntime.world.placeId='park';net.observe(c,start);assert.equal(n.observed.length,1);net.observe(c,start+MIN);assert.equal(n.observed.length,1);
console.log('Directional NPC appraisals, earned friendship, three-person plans, physical travel, missed meetings, witness boundaries and batching passed.');
