'use strict';
const {spawn}=require('node:child_process'),assert=require('node:assert/strict');
const {chromium,launchOptions}=require('./browser_runtime').browserRuntime();
(async()=>{const server=spawn(process.env.HORDE_PYTHON_EXECUTABLE||'python3',['scratch/vh2_browser_server.py'],{stdio:['ignore','pipe','pipe']});let browser;
try{const port=await new Promise((resolve,reject)=>{server.stdout.once('data',d=>resolve(+String(d).trim()));server.stderr.on('data',d=>process.stderr.write(d));server.once('exit',c=>reject(Error('server '+c)));});const base=`http://127.0.0.1:${port}`;
 browser=await chromium.launch(launchOptions);const page=await browser.newPage({viewport:{width:1200,height:1000}}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.route('**/*',r=>r.request().url().startsWith(base)?r.continue():r.abort());await page.goto(base+'/index.html');await page.waitForFunction(()=>typeof companionAgencyTimer!=='undefined'&&!!companionAgencyTimer);
 await page.evaluate(async base=>{clearInterval(companionAgencyTimer);clearInterval(companionAlwaysOnTimer);mcpBridgeBase=()=>base;state.globalSettings.localBaseUrl=base+'/test';state.globalSettings.localApiKey='LOCAL_TEST_KEY';state.globalSettings.apiProvider='local';state.globalSettings.defaultModel='browser-fixture';state.globalSettings.companionAlwaysOnEnabled=false;
 const c=normalizeCompanion({id:'budget-browser',name:'Budget fixture',age:28,textProvider:'local',model:'browser-fixture',lifeProfile:{weeklySchedule:[],sleepPolicy:{enabled:false}}});state.companions=[c];state.activeCompanionId=c.id;state.companionTimelines={};state.companionThreads={};ensureCompanionTimelineStore(c.id);hideGlobalSettings();
 await mcpBridgeRequest('/vh2/dialogue-provider',{method:'POST',body:{scope:'horde:'+c.id,baseUrl:base+'/test',model:'browser-fixture',apiKey:'LOCAL_TEST_KEY',enabled:true,maxTokens:512,dailyLimit:2,temperature:.7}});
 await vh2CreateTimeline(c);switchView('companionChat');renderCompanionThread();await vh2Poll(c,getActiveCompanionTimeline(c.id),{force:true,throwOnError:true});},base);
 assert.equal(await page.locator('#vh-text-budget-notice').count(),0,'chat has no text usage footer');
 const saved=await page.evaluate(()=>mcpBridgeRequest('/vh2/dialogue-provider?scope=horde%3Abudget-browser'));assert.equal(saved.textLimitsEnforced,false);assert.equal(saved.dailyLimit,undefined);assert.equal(saved.budgetPolicy,undefined);assert.equal(saved.usedToday,0);assert.equal(saved.budgets.dialogue.limit,null);assert.equal(saved.budgets.background.limit,null);
 // Reproduce the reported state with the real service: attention becomes ready
 // while automatic replies are off, then the same saved turn continues once.
 const worldId=await page.evaluate(()=>getActiveCompanionTimeline('budget-browser').vh2.worldId);
 await page.evaluate(async()=>{const c=getCompanion('budget-browser'),t=getActiveCompanionTimeline(c.id);await vhUiCommand(t,'configure_auto_replies',{enabled:false});switchView('companionChat');renderCompanionThread();});
 await page.locator('#companion-composer-input').fill('Reply recovery fixture');await page.evaluate(()=>handleCompanionSend());
 let readyProjection;
 for(let i=0;i<12;i++){await fetch(base+'/test/tick',{method:'POST'});await page.evaluate(()=>vh2Poll(getCompanion('budget-browser'),getActiveCompanionTimeline('budget-browser'),{force:true}));readyProjection=await (await fetch(base+'/vh2/projection?worldId='+encodeURIComponent(worldId))).json();if(readyProjection.state.communication.messages.some(m=>m.role==='user'&&m.attention?.stage==='ready'))break;}
 assert.equal(readyProjection.state.integration.autoReplies,false);assert.equal(readyProjection.state.communication.replyJob??null,null);assert(readyProjection.state.communication.messages.some(m=>m.role==='user'&&m.attention?.stage==='ready'));
 await page.getByText('Reply ready · automatic replies are off',{exact:true}).waitFor();await page.getByRole('button',{name:'Enable replies · may use credits',exact:true}).click();
 await page.waitForFunction(()=>getActiveCompanionTimeline('budget-browser').vh2.autoReplies===true);
 for(let i=0;i<12;i++){await new Promise(resolve=>setTimeout(resolve,1100));await page.evaluate(()=>vh2Poll(getCompanion('budget-browser'),getActiveCompanionTimeline('budget-browser'),{force:true}));const projection=await (await fetch(base+'/vh2/projection?worldId='+encodeURIComponent(worldId))).json();if(projection.state.communication.messages.some(m=>m.role==='assistant'))break;}
 const recovered=await (await fetch(base+'/vh2/projection?worldId='+encodeURIComponent(worldId))).json();assert.equal(recovered.state.communication.messages.filter(m=>m.role==='user').length,1,'recovery keeps one saved user turn');assert.equal(recovered.state.communication.messages.filter(m=>m.role==='assistant').length,1,'recovery generates exactly one reply');
 await page.route(base+'/vh2/dialogue-jobs?*',r=>r.fulfill({status:200,contentType:'application/json',body:JSON.stringify({jobs:[{id:'fixture',model:'fixture-model',status:'delivered',created_at:Date.now(),usage:{prompt_tokens:123,completion_tokens:7,total_tokens:130},promptPreview:[{role:'system',content:'Frozen fixture instructions [credential redacted]'}],promptTruncated:false}]})}));
 await page.evaluate(()=>vhOpenLifeStatus(getCompanion('budget-browser')));const life=page.getByRole('dialog',{name:'Life status',exact:true});const usage=life.locator('details').filter({hasText:'Text usage & reply attempts'}).first();assert.equal(await usage.evaluate(el=>el.open),false);await usage.locator('summary').click();await usage.getByRole('button',{name:'Reply details',exact:true}).click();const details=page.getByRole('dialog',{name:'Reply details',exact:true});await details.getByText(/fixture-model · delivered/).click();await details.getByText('Provider-reported tokens: input 123 · output 7 · total 130',{exact:true}).waitFor();await details.getByText('Frozen prompt text (redacted preview)',{exact:true}).click();await details.getByText(/Frozen fixture instructions/).waitFor();await details.getByRole('button',{name:'Close',exact:true}).click();
 await page.evaluate(async()=>{const c=getCompanion('budget-browser');renderCompanionThread();await vh2Poll(c,getActiveCompanionTimeline(c.id),{force:true,readOnly:true});});
 assert.equal(await page.locator('#vh-text-budget-notice').count(),0,'render and poll keep footer absent');
 await page.evaluate(()=>{const c=getCompanion('budget-browser'),t=getActiveCompanionTimeline(c.id);t.vh2.textProvider={configured:true,budgets:{dialogue:{legacy:true,limit:1,used:1}}};vhOpenLifeStatus(c);});
 const oldUsage=page.getByRole('dialog',{name:'Life status',exact:true}).locator('details').filter({hasText:'Text usage & reply attempts'}).first();assert.equal(await oldUsage.evaluate(el=>el.open),false);await oldUsage.locator('summary').click();await oldUsage.getByText(/older VH2 service/).waitFor();await page.getByRole('dialog',{name:'Life status',exact:true}).getByRole('button',{name:'Close',exact:true}).click();
 for(const [mode,expected] of [['waiting','Waiting for a reply: At dinner until 20:00'],['ready','Reply ready · starting the text model…'],['auto-off','Reply ready · automatic replies are off'],['worker-error','Reply service needs attention: Dialogue worker unavailable; queued work remains saved.'],['paused','Message saved · life is paused, so replies are waiting'],['queued','Preparing a reply…'],['leased','Preparing a reply…'],['submitted','Preparing a reply…'],['unknown','Reply outcome unknown — review before retrying'],['failed','Reply did not finish: Daily allowance reached'],['connected','Connected']]){
  await page.evaluate(mode=>{const c=getCompanion('budget-browser'),t=getActiveCompanionTimeline(c.id),ready=['ready','auto-off','worker-error'].includes(mode);t.messages=mode==='connected'?[]:[{role:'user',awaitingReply:true,attention:{stage:ready?'ready':'deferred',reason:ready?'Attention is available; begin responding.':'At dinner until 20:00'}}];Object.assign(t.vh2,{running:mode!=='paused',autoReplies:mode!=='auto-off',dialogueError:mode==='worker-error'?'Dialogue worker unavailable; queued work remains saved.':'',error:'',outbox:[],lastSyncedAt:Date.now(),replyJob:['queued','leased','submitted','unknown','failed'].includes(mode)?{status:mode,reason:mode==='failed'?'Daily allowance reached':''}:null});vhRenderSystemStatus(c);},mode);
  assert.equal(await page.locator('#vh-chat-system > span').innerText(),expected);
  if(mode==='auto-off')assert(await page.getByRole('button',{name:'Enable replies · may use credits',exact:true}).isVisible());
 }
 await page.evaluate(()=>vhOpenWorkspace('connections'));
 await page.getByLabel('Automatic replies',{exact:true}).waitFor();assert(await page.getByLabel('Automatic replies',{exact:true}).isChecked());
 await page.evaluate(()=>switchView('companionChat'));await page.evaluate(()=>renderCompanionThread());
 await page.setViewportSize({width:390,height:844});assert.equal(await page.locator('#vh-text-budget-notice').count(),0,'mobile chat has no text usage footer');
 await page.locator('#vh-chat-more > summary').click();
 for(const selector of ['#companion-simulation-btn','#vh-chat-activity','#cc-persona-select'])assert(await page.locator(selector).isVisible(),selector+' remains accessible in More');
 await page.locator('#vh-chat-more .vh-person-tools > summary').click();assert(await page.getByRole('button',{name:'Providers & feeds',exact:true}).isVisible());
 await page.locator('#vh-chat-more > summary').focus();await page.keyboard.press('Escape');assert.equal(await page.locator('#vh-chat-more').evaluate(el=>el.open),false);
 const layout=await page.locator('#vh-chat-system').evaluate(el=>({width:el.getBoundingClientRect().width,scroll:el.scrollWidth,client:el.clientWidth}));assert(layout.width<=390&&layout.scroll<=layout.client+1,JSON.stringify(layout));
 const fs=require('node:fs');fs.mkdirSync('docs/vh2/creation-chat-20260920',{recursive:true});await page.screenshot({path:'docs/vh2/creation-chat-20260920/chat-mobile.png',fullPage:true});await page.setViewportSize({width:320,height:740});await page.locator('#vh-chat-more > summary').click();assert(await page.locator('#cc-persona-select').isVisible());const narrow=await page.locator('#vh-chat-more > div').evaluate(el=>({left:el.getBoundingClientRect().left,right:el.getBoundingClientRect().right,scroll:el.scrollWidth,client:el.clientWidth,body:document.documentElement.scrollWidth}));assert(narrow.left>=0&&narrow.right<=320&&narrow.scroll<=narrow.client+1&&narrow.body<=320,'320px menu overflow '+JSON.stringify(narrow));await page.screenshot({path:'docs/vh2/creation-chat-20260920/chat-menu-320.png',fullPage:true});await page.locator('#vh-chat-more > summary').focus();await page.keyboard.press('Escape');await page.setViewportSize({width:1440,height:1000});await page.screenshot({path:'docs/vh2/creation-chat-20260920/chat-desktop.png',fullPage:true});
 assert.deepEqual(errors,[]);console.log('PASS chat UX: no footer, Life status diagnostics, old-server disclosure, token details, waiting/paused/generating/failure/unknown states, mobile sizing; no provider spend.');
}finally{if(browser)await browser.close();server.kill();}
})().catch(e=>{console.error(e);process.exitCode=1;});
