'use strict';
const assert=require('node:assert/strict'),travel=require('../vh2-travel-engine');
const now=1789030800000,MIN=60000;
function fixture(){const c={id:'x',lifeProfile:{places:[{id:'home',kind:'home'},{id:'station',kind:'transit'},{id:'away',kind:'home'}],world:{transport:{transit:true}},travelLegs:[]},lifeRuntime:{world:{placeId:'station',balance:50},activities:{}},vh2Transport:{services:[{id:'replacement',label:'Train',from:'station',to:'away',kind:'train',status:'scheduled',departsAt:now+10*MIN,arrivesAt:now+30*MIN,boardingMinutes:2,cost:10}]}};const r=travel.ensure(c);r.recoveryPolicy.enabled=true;r.activeId='trip';r.trips=[{id:'trip',label:'Trip',status:'blocked',stopIndex:1,legSequence:2,stops:[{placeId:'station',stayMinutes:0,stayCost:20},{placeId:'away',stayMinutes:10,stayCost:15}],paidStays:[0],legs:[],lastLeg:{to:'station'}}];return c;}
let c=fixture(),r=c.vh2Travel,t=r.trips[0],original=JSON.stringify(t.stops);travel.tick(c,now,{});assert.equal(t.status,'waiting');assert.equal(c.lifeRuntime.world.balance,50);assert.equal(JSON.stringify(t.stops),original);assert.deepEqual(t.paidStays,[0]);travel.tick(c,now+10*MIN,{});assert.equal(c.lifeRuntime.world.balance,40);assert.equal(t.legSequence,3);travel.tick(c,now+11*MIN,{});assert.equal(c.lifeRuntime.world.balance,40);
c=fixture();c.lifeRuntime.world.balance=20;travel.tick(c,now,{});assert.equal(c.vh2Travel.trips[0].status,'blocked','replacement must leave money for unpaid stays');assert.equal(c.lifeRuntime.world.balance,20);
c=fixture();c.vh2Travel.recoveryPolicy.maxSpend=5;travel.tick(c,now,{});assert.equal(c.vh2Travel.trips[0].status,'blocked');
c=fixture();c.vh2Travel.recoveryPolicy.maxWaitMinutes=3;travel.tick(c,now,{});assert.equal(c.vh2Travel.trips[0].status,'blocked');
c=fixture();c.vh2Travel.recoveryPolicy.maxWaitMinutes=3;c.lifeProfile.travelLegs=[{from:'station',to:'away',mode:'WALK',minutes:45,cost:0}];travel.tick(c,now,{});assert.equal(c.lifeRuntime.world.journey.mode,'WALK','search an alternative when the fastest service has an excessive wait');
c=fixture();c.vh2Transport.services=[];c.vh2Travel.recoveryPolicy.maxAttempts=2;for(let i=0;i<30;i++)travel.tick(c,now+i*MIN,{});assert.equal(c.vh2Travel.trips[0].recovery.attempts,2);assert.equal(c.lifeRuntime.world.placeId,'station');
c=fixture();travel.tick(c,now,{availability:'asleep'});assert.equal(c.vh2Travel.trips[0].status,'blocked');assert(!c.vh2Travel.trips[0].recovery);
c=fixture();c.lifeRuntime.world.journey={to:'station'};travel.tick(c,now,{});assert.equal(c.vh2Travel.trips[0].status,'blocked');
c=fixture();c.vh2Travel.recoveryPolicy.enabled=false;travel.tick(c,now,{});assert.equal(c.vh2Travel.trips[0].status,'blocked');c.vh2Travel.trips[0].recoveryRequested=true;travel.tick(c,now+MIN,{});assert.equal(c.vh2Travel.trips[0].status,'waiting');
c=fixture();c.vh2Travel.trips[0].stops[1].eventEndsAt=now+20*MIN;travel.tick(c,now,{});assert.equal(c.vh2Travel.trips[0].status,'blocked','do not arrive after the event ended');
c=fixture();c.vh2Travel.trips[0].stopIndex=0;c.vh2Travel.trips[0].recoveryTargetIndex=1;travel.tick(c,now,{});assert.equal(c.vh2Travel.trips[0].stopIndex,1);assert.deepEqual(c.vh2Travel.trips[0].paidStays,[0]);
console.log('PASS replacement routes, paid-history preservation, budget/stay reserves, wait/attempt limits, attention, event deadlines and manual requests.');
