'use strict';
const assert=require('node:assert/strict'),b=require('../vh2-social-bonds'),l=require('../vh2-relationship-lifecycle');
const DAY=86400000;
function make(){const c={id:'alex',age:30,lifeProfile:{socialCircle:[{id:'sam',name:'Sam',role:'acquaintance',closeness:0,trust:0,contactWindows:[]}]},lifeRuntime:{world:{people:{sam:{stress:0}}}},humanDynamics:{stress:0},vh2Plans:{plans:[]}};b.ensure(c,DAY);c.vh2SocialBonds.pairs.sam.lifecycle={status:'none',contactExchangedAt:null,events:[],policy:{enabled:true,personAge:30,selfPotential:100,otherPotential:100}};return c;}
function meet(c,index,stress=0){const at=(1+index*7)*DAY;c.humanDynamics.stress=stress;c.lifeRuntime.world.people.sam.stress=stress;c.vh2Plans.plans.push({id:'m'+index,personId:'sam',status:'completed',completedAt:at,durationMinutes:30});b.advance(c,at);}
const c=make();for(let i=0;i<3;i++)meet(c,i);assert.ok(c.lifeProfile.socialCircle[0].contactWindows.length);assert.equal(c.vh2SocialBonds.pairs.sam.lifecycle.status,'none','contact is not dating');for(let i=3;i<10;i++)meet(c,i);assert.equal(c.vh2SocialBonds.pairs.sam.lifecycle.status,'dating');for(let i=10;i<20;i++)meet(c,i);assert.equal(c.vh2SocialBonds.pairs.sam.lifecycle.status,'partner');
const saved=JSON.parse(JSON.stringify(c));b.advance(c,134*DAY);b.advance(saved,134*DAY);assert.deepEqual(c,saved);
for(let i=20;i<120;i++)meet(c,i,100);assert.equal(c.vh2SocialBonds.pairs.sam.lifecycle.status,'separated');assert.equal(c.vh2SocialBonds.pairs.sam.self.stage,'estranged');assert.equal(l.visibleEvents(c).filter(e=>e.transition==='separated').length,1);
for(const scenario of ['minor','family','one_sided','disabled','already_partner']){const x=make();const p=x.vh2SocialBonds.pairs.sam.lifecycle.policy;if(scenario==='minor')p.personAge=17;if(scenario==='family')x.lifeProfile.socialCircle[0].role='family';if(scenario==='one_sided')p.otherPotential=0;if(scenario==='disabled')p.enabled=false;if(scenario==='already_partner')x.lifeProfile.socialCircle.push({id:'pat',name:'Pat',role:'partner',closeness:80,trust:80});for(let i=0;i<25;i++)meet(x,i);assert.equal(x.vh2SocialBonds.pairs.sam.lifecycle.status,'none',scenario);}
assert.ok(!JSON.stringify(b.known(c)).includes('otherPotential'),'private compatibility is not character knowledge');
console.log('Relationship lifecycle: contact, mutual dating/partnership, estrangement/separation, explicit eligibility, exclusivity and replay passed');
