'use strict';
const {spawn}=require('node:child_process'),assert=require('node:assert/strict'),fs=require('node:fs');
const {chromium,launchOptions}=require('./browser_runtime').browserRuntime();

(async()=>{const server=spawn(process.env.HORDE_PYTHON_EXECUTABLE||'python3',['scratch/vh2_browser_server.py'],{stdio:['ignore','pipe','pipe']});let browser;
try{
 const port=await new Promise((resolve,reject)=>{server.stdout.once('data',data=>resolve(+String(data).trim()));server.stderr.on('data',data=>process.stderr.write(data));server.once('exit',code=>reject(Error('server '+code)));});
 const base=`http://127.0.0.1:${port}`;browser=await chromium.launch(launchOptions);const page=await browser.newPage({viewport:{width:1440,height:1000}}),errors=[],calls=[];let mode='success';
 page.on('pageerror',error=>errors.push(error.message));
 page.on('dialog',dialog=>dialog.dismiss());
 await page.route('**/*',async route=>{const url=route.request().url();if(url!==base+'/test/chat/completions')return url.startsWith(base)?route.continue():route.abort();const body=route.request().postDataJSON();let data={};try{data=JSON.parse(body.messages[1].content);}catch{}if(!data.field)return route.fulfill({status:200,contentType:'application/json',body:JSON.stringify({choices:[{finish_reason:'stop',message:{content:'Background fixture reply'}}]})});calls.push({field:data.field,body,data});if(mode==='slow')await new Promise(resolve=>setTimeout(resolve,350));if(mode==='fail-second'&&data.field==='pronouns')return route.fulfill({status:503,body:'fixture outage'});if(mode==='rate-limit')return route.fulfill({status:429,body:'fixture rate limit'});const content=mode==='structured'?'```json\n{"bad":true}\n```':({'name':'Stress Name',pronouns:'they/them',personality:'Patient under pressure but unwilling to fake agreement.',appearance:'Copper hair, brown eyes and a weathered green coat.',backstory:'A complete authored history that remains fictional.',occupation:'Night archivist.',socialWorld:'One old friend lives across town.'}[data.field]||'Reviewed '+data.field);return route.fulfill({status:200,contentType:'application/json',body:JSON.stringify({choices:[{finish_reason:'stop',message:{content}}]})});});
 await page.goto(base+'/index.html');await page.waitForFunction(()=>typeof companionAgencyTimer!=='undefined'&&!!companionAgencyTimer);await page.addStyleTag({content:'*,*::before,*::after{animation:none!important;transition:none!important;scroll-behavior:auto!important}'});
 const lifeArchetypeContract=await page.evaluate(()=>companionFocusedLifePrompt(['activityOptions']));assert.match(lifeArchetypeContract,/heightened, obsessive, erratic, unsettling/);assert.match(lifeArchetypeContract,/do not sanitize them into agreeable normality/);assert.match(lifeArchetypeContract,/unsupported actions already happened/);
 await page.evaluate(base=>{clearInterval(companionAgencyTimer);clearInterval(companionAlwaysOnTimer);mcpBridgeBase=()=>base;state.globalSettings.localBaseUrl=base+'/test';state.globalSettings.localApiKey='LOCAL_STRESS_KEY';state.globalSettings.apiProvider='local';state.globalSettings.defaultModel='stress-fixture';const companion=normalizeCompanion({id:'builder-stress',name:'Existing Name',age:34,pronouns:'she/her',personality:'Deliberate and observant.',textProvider:'local',model:'stress-fixture'});state.companions=[companion];state.activeCompanionId=companion.id;state.companionTimelines={};state.companionThreads={};ensureCompanionTimelineStore(companion.id);hideGlobalSettings();openCompanionStudio(companion.id);switchView('companionStudio');activateCompanionStudioTab('cs-identity');},base);
 const wholeHumanGuard=await page.evaluate(async()=>{const original=fetch;let calls=0;fetch=async()=>{calls++;throw Error('Network should not be reached');};try{await buildCompanionLifeWithAI(getCompanion('builder-stress'),{wholeLife:true,model:'stress-fixture'});return {calls,error:''};}catch(error){return {calls,error:error.message};}finally{fetch=original;}});assert.equal(wholeHumanGuard.calls,0,'Whole-human generation is blocked before any provider call');assert.match(wholeHumanGuard.error,/Whole-human AI generation is disabled/);
 const wholeCompletionGuard=await page.evaluate(async()=>{const original=fetch;let calls=0;fetch=async()=>{calls++;throw Error('Network should not be reached');};try{await completeCompanionLifeDraftSections(getCompanion('builder-stress'),{},{wholeLife:true,model:'stress-fixture'});return {calls,error:''};}catch(error){return {calls,error:error.message};}finally{fetch=original;}});assert.equal(wholeCompletionGuard.calls,0,'Legacy whole-life completion is blocked before any provider call');assert.match(wholeCompletionGuard.error,/Whole-human AI generation is disabled/);
 const open=async()=>{await page.evaluate(()=>{document.querySelectorAll('dialog[open]').forEach(dialog=>dialog.close());activateCompanionStudioTab('cs-identity');vhOpenPageBuilder('cs-identity');});const dialog=page.locator('dialog[open]');await dialog.waitFor();return dialog;};
 const row=(dialog,label)=>dialog.locator('section.form-section').filter({has:page.getByText(new RegExp('^(Draft|Replace) '+label+'$'))});
 const select=async(dialog,labels)=>{for(const check of await dialog.locator('section.form-section>.vh-choice-row:first-child input').all())await check.uncheck();for(const label of labels)await row(dialog,label).locator('input').first().check();};

 let dialog=await open();assert.equal(calls.length,0,'Opening the builder spends no credits');assert.equal(await dialog.locator('section.form-section').count(),8);assert.equal(await dialog.getByRole('button',{name:'Select fields to draft',exact:true}).isDisabled(),true);assert.match(await dialog.locator('[data-vh-request-count]').innerText(),/exact number/);assert.equal(await dialog.locator('.vh-builder-field-help').count(),8,'Each choice explains its meaning in context');
 await select(dialog,['Name','Pronouns','Personality']);assert.equal(await dialog.getByRole('button',{name:'Draft 3 selected fields',exact:true}).isEnabled(),true);assert.match(await dialog.locator('[data-vh-request-count]').innerText(),/3 separate text requests/);await dialog.getByRole('button',{name:'Close',exact:true}).click();

 calls.length=0;dialog=await open();await select(dialog,['Personality']);await dialog.locator('label').filter({hasText:/What should this page express/}).locator('textarea').fill('A heightened yandere archetype: possessive, obsessive, unnervingly polite when jealous, and capable of making bad choices. Preserve the discomfort instead of making her agreeable.');await dialog.getByRole('button',{name:'Draft 1 selected field',exact:true}).click();await row(dialog,'Personality').getByText('Ready to review.',{exact:true}).waitFor();assert.match(calls[0].body.messages[0].content,/obsessive, erratic, unsettling/);assert.match(calls[0].body.messages[0].content,/do not sanitize it into agreeable normality/);assert.match(calls[0].data.direction,/yandere archetype/);await dialog.getByRole('button',{name:'Close',exact:true}).click();

 mode='fail-second';calls.length=0;dialog=await open();await select(dialog,['Name','Pronouns','Personality']);await dialog.getByRole('button',{name:'Draft 3 selected fields',exact:true}).click();await dialog.getByText(/Remaining selected fields were not sent/).waitFor();assert.deepEqual(calls.map(call=>call.field),['name','pronouns'],'A failed request stops the remaining batch');assert.equal(await row(dialog,'Personality').locator('[role=status]').isHidden(),true,'Unsent rows stay quiet instead of showing redundant status blocks');assert.match(await row(dialog,'Pronouns').innerText(),/HTTP 503/);
 mode='success';await row(dialog,'Pronouns').getByRole('button',{name:'Retry this field'}).click();await row(dialog,'Pronouns').getByText('Ready to review.',{exact:true}).waitFor();assert.deepEqual(calls.map(call=>call.field),['name','pronouns','pronouns'],'Retry sends only the failed field');await dialog.getByRole('button',{name:'Apply selected drafts to editor'}).click();await dialog.getByText(/Nothing is saved yet/).waitFor();assert.equal(await page.locator('#cs-name').inputValue(),'Stress Name');assert.equal(await page.locator('#cs-pronouns').inputValue(),'they/them');assert.match(await page.locator('#cs-name-limit').innerText(),/^11 \/ 100/,'Applying a draft refreshes the field counter');await dialog.getByRole('button',{name:'Close',exact:true}).click();

 mode='slow';calls.length=0;dialog=await open();await select(dialog,['Appearance','Background']);await page.evaluate(()=>{const button=[...document.querySelectorAll('dialog[open] button')].find(node=>node.textContent==='Draft 2 selected fields');button.click();button.click();});await dialog.getByText('Review the finished fields. Failed fields can be retried individually.',{exact:true}).waitFor();assert.deepEqual(calls.map(call=>call.field),['appearance','backstory'],'A rapid double activation cannot duplicate paid requests');await dialog.getByRole('button',{name:'Close',exact:true}).click();

 calls.length=0;dialog=await open();await select(dialog,['Occupation','Social world']);await dialog.getByRole('button',{name:'Draft 2 selected fields',exact:true}).click();await page.waitForTimeout(60);await page.evaluate(()=>{const input=document.getElementById('cs-occupation');input.value='User edit during generation';input.dispatchEvent(new Event('input',{bubbles:true}));});await dialog.getByText(/Remaining selected fields were not sent/).waitFor();assert.deepEqual(calls.map(call=>call.field),['occupation'],'A stale editor stops later requests');assert.equal(await page.locator('#cs-occupation').inputValue(),'User edit during generation');await dialog.getByRole('button',{name:'Close',exact:true}).click();await page.locator('#cs-occupation').fill('');

 calls.length=0;dialog=await open();await select(dialog,['Appearance','Background','Occupation']);await dialog.getByRole('button',{name:'Draft 3 selected fields',exact:true}).click();await page.waitForTimeout(60);await dialog.getByRole('button',{name:'Stop generating'}).click();await dialog.getByText('Stopped. Finished drafts are kept for review.',{exact:true}).waitFor();assert.equal(calls.length,1,'Stop prevents later selected requests');await dialog.getByRole('button',{name:'Close',exact:true}).click();

 mode='rate-limit';calls.length=0;dialog=await open();await select(dialog,['Appearance','Background','Occupation']);await dialog.getByRole('button',{name:'Draft 3 selected fields',exact:true}).click();await dialog.getByText(/rate or credit limit/).first().waitFor();await dialog.getByText(/Remaining selected fields were not sent/).waitFor();assert.equal(calls.length,1,'A rate or credit error stops the batch');await dialog.getByRole('button',{name:'Close',exact:true}).click();

 mode='structured';calls.length=0;dialog=await open();await select(dialog,['Appearance','Background']);await dialog.getByRole('button',{name:'Draft 2 selected fields',exact:true}).click();await dialog.getByText(/structured output/).first().waitFor();assert.equal(calls.length,1,'Invalid model output stops later requests');await dialog.getByRole('button',{name:'Close',exact:true}).click();

 mode='success';calls.length=0;dialog=await open();await select(dialog,['Appearance']);await dialog.locator('label').filter({hasText:/What should this page express/}).locator('textarea').evaluate(textarea=>textarea.value='x'.repeat(4001));await dialog.getByRole('button',{name:'Draft 1 selected field',exact:true}).click();await dialog.getByText(/Directions exceed 4,000/).waitFor();assert.equal(calls.length,0,'Oversized directions are rejected before transmission');await dialog.getByRole('button',{name:'Close',exact:true}).click();

 await page.evaluate(()=>{const companion=getCompanion('builder-stress');companion.textProvider='openrouter';state.apiKey='';});dialog=await open();await select(dialog,['Appearance']);assert.equal(await dialog.getByRole('button',{name:'Connect AI',exact:true}).isVisible(),true);assert.equal(await dialog.getByRole('button',{name:'Draft 1 selected field',exact:true}).isDisabled(),true,'Disconnected providers cannot start requests');assert.equal(calls.length,0);await dialog.getByRole('button',{name:'Close',exact:true}).click();await page.evaluate(()=>{getCompanion('builder-stress').textProvider='local';});

 dialog=await open();await select(dialog,['Name','Pronouns','Personality','Behavior examples','Appearance','Background','Occupation','Social world']);const out='docs/vh2/ai-builder-audit-20260920';fs.mkdirSync(out,{recursive:true});await page.screenshot({path:out+'/desktop-selection.png',fullPage:true});await page.setViewportSize({width:390,height:844});const geometry=await dialog.evaluate(element=>({scrollWidth:element.scrollWidth,clientWidth:element.clientWidth,rect:element.getBoundingClientRect().toJSON(),body:document.documentElement.scrollWidth,viewport:innerWidth}));assert(geometry.scrollWidth<=geometry.clientWidth+1&&geometry.body<=geometry.viewport+1,'Builder has no mobile horizontal overflow: '+JSON.stringify(geometry));await page.screenshot({path:out+'/mobile-selection.png',fullPage:true});assert.equal(await dialog.getByRole('button',{name:'Draft 8 selected fields',exact:true}).isVisible(),true);await dialog.getByRole('button',{name:'Close',exact:true}).click();

 assert(calls.every(call=>!JSON.stringify(call.body).includes('LOCAL_STRESS_KEY')),'Secrets never enter request bodies');assert(calls.every(call=>call.body.messages.length===2&&!call.body.tools),'Requests stay bounded text-only calls');assert.deepEqual(errors,[]);fs.writeFileSync(out+'/stress-results.json',JSON.stringify({passed:true,scenarios:['whole-human generation blocked before provider','legacy whole-life completion blocked before provider','no-call open','exact request count','identity archetype preservation contract','life/action archetype preservation contract','stop batch on provider failure','isolated retry','apply refreshes counters','double activation','stale-edit stop','manual cancellation','rate-limit stop','invalid-output stop','oversized-direction preflight','disconnected-provider preflight','mobile overflow','secret-free payloads'],requestCount:calls.length,geometry},null,2));console.log('PASS AI builder stress audit: 18 adversarial credit-safety, archetype-preservation, state-integrity, failure, accessibility and responsive scenarios.');
}finally{await browser?.close();server.kill();}
})().catch(error=>{console.error(error);process.exitCode=1;});
