'use strict';
const {spawn}=require('node:child_process'),assert=require('node:assert/strict'),fs=require('node:fs');
const {chromium,launchOptions}=require('./browser_runtime').browserRuntime();
(async()=>{const server=spawn(process.env.HORDE_PYTHON_EXECUTABLE||'python3',['scratch/vh2_browser_server.py'],{stdio:['ignore','pipe','pipe']});let browser;
try{
 const port=await new Promise((resolve,reject)=>{server.stdout.once('data',d=>resolve(+String(d).trim()));server.stderr.on('data',d=>process.stderr.write(d));server.once('exit',c=>reject(Error('server '+c)));});const base=`http://127.0.0.1:${port}`;
 browser=await chromium.launch(launchOptions);const page=await browser.newPage({viewport:{width:1280,height:900}}),errors=[],calls=[];
 page.on('pageerror',e=>errors.push(e.message));
 await page.route('**/*',async r=>{const url=r.request().url();if(url===base+'/test/chat/completions'){const body=r.request().postDataJSON();let data={};try{data=JSON.parse(body.messages[1].content);}catch{}if(data.field)calls.push(data.field);return r.fulfill({status:200,contentType:'application/json',body:JSON.stringify({choices:[{finish_reason:'stop',message:{content:data.field?'An isolated fantasy archivist who distrusts visitors and guards forgotten stories.':'Local mock model reply'}}]})});}return url.startsWith(base)?r.continue():r.abort();});
 await page.goto(base+'/index.html');await page.waitForFunction(()=>typeof companionAgencyTimer!=='undefined'&&!!companionAgencyTimer);
 await page.addStyleTag({content:'*,*::before,*::after{animation:none!important;transition:none!important;scroll-behavior:auto!important}'});
 await page.evaluate(base=>{clearInterval(companionAgencyTimer);clearInterval(companionAlwaysOnTimer);mcpBridgeBase=()=>base;state.globalSettings.localBaseUrl=base+'/test';state.globalSettings.localApiKey='LOCAL_TEST_KEY';state.globalSettings.apiProvider='local';state.globalSettings.defaultModel='browser-fixture';state.companions=[];state.companionTimelines={};state.companionThreads={};hideGlobalSettings();switchView('companions');},base);
 await page.locator('#create-new-companion-btn').click();await page.locator('#tab-cs-overview').waitFor({state:'visible'});
 assert.equal(await page.locator('.vh-system-card').count(),7,'Creator begins with the complete system map');
 assert.equal(await page.locator('[data-start-brief],#tab-cs-builder').count(),0,'No whole-human brief generator is exposed');
 assert(await page.locator('[data-page-authoring]').isVisible(),'System map opens direct authoring');
 assert(await page.locator('[data-opening]').isVisible(),'System map exposes conversation start without hunting through the form');
 assert(await page.locator('#delete-companion-btn').isVisible(),'Delete human is visible in the editor header');
 assert.deepEqual(await page.locator('.vh-tab-group-label').allTextContents(),['Architecture','Person','Life & agency','Media','Runtime'],'Dense tools have a stable information architecture');
 const creatorScroller=page.locator('#companion-studio-view .studio-content-wrap');
 const sectionNavTop=await page.locator('#companion-studio-view .studio-tabs').evaluate(el=>el.getBoundingClientRect().top);
 assert(await creatorScroller.evaluate(el=>el.scrollHeight>el.clientHeight),'Creator owns a scrollable content region');
 await creatorScroller.evaluate(el=>{el.scrollTop=Math.min(360,el.scrollHeight-el.clientHeight);});
 assert(await creatorScroller.evaluate(el=>el.scrollTop)>0,'Creator content scrolls');
 assert(Math.abs(await page.locator('#companion-studio-view .studio-tabs').evaluate(el=>el.getBoundingClientRect().top)-sectionNavTop)<1,'Section navigation stays pinned while the editor scrolls');
 await page.locator('[data-page-authoring]').click();await page.locator('#tab-cs-identity').waitFor({state:'visible'});
 assert(await page.locator('[data-vh-page-builder="cs-identity"]').isVisible(),'AI remains available at page scope');
 await page.evaluate(()=>activateCompanionStudioTab('cs-overview'));
 await page.locator('[data-opening]').click();await page.locator('#tab-cs-mind').waitFor({state:'visible'});
 assert.equal(await page.locator('#tab-cs-mind .vh-authoring-subnav button').count(),9,'Dense psychology remains complete but gains local navigation');
 assert(await page.locator('#cs-opening-mode').isVisible(),'Conversation initiator is directly reachable');
 await page.locator('#tab-cs-mind [data-authoring-jump=mind]').click();
 const innerLibrary=page.locator('#cs-mind-library-results');await innerLibrary.evaluate(el=>{el.scrollTop=el.scrollHeight;});
 const outerBefore=await creatorScroller.evaluate(el=>el.scrollTop);await innerLibrary.hover();await page.mouse.wheel(0,700);await page.waitForTimeout(50);
 assert(await creatorScroller.evaluate(el=>el.scrollTop)>outerBefore,'Scrolling at the end of the trait library continues through the creator');
 await page.evaluate(()=>activateCompanionStudioTab('cs-overview'));
 await page.locator('.vh-system-card').filter({hasText:'Identity & history'}).click();await page.locator('#tab-cs-identity').waitFor({state:'visible'});
 assert(await page.locator('#cs-personality').isVisible(),'Personality is visible');
 assert(await page.locator('#cs-age').isVisible(),'Age is visible');
 assert(await page.locator('#cs-appearance').isVisible(),'Appearance is visible');
 assert.equal(await page.locator('#cs-backstory').isVisible(),true,'Background remains immediately available');
 await page.locator('#cs-name').fill('Iri the Archivist');
 await page.locator('[data-vh-field-builder="personality"]').click();let dialog=page.locator('dialog[open]');await dialog.waitFor();
 const selected=()=>dialog.locator('section > label:first-child input:checked');
 assert.equal(await selected().count(),1,'Field action selects exactly one field');assert.match(await selected().locator('..').innerText(),/personality|brief/i);
 assert.equal(calls.length,0,'Opening field dialog does not generate');
 assert.equal(await dialog.locator('details input:not([type=checkbox])').isVisible(),false,'Inherited model override is collapsed');
 assert.equal(await dialog.locator('details').filter({has:page.getByText(/Advanced/, {exact:false})}).count()>0,true,'Advanced connection controls exist');
 await dialog.getByRole('button',{name:/Draft 1 selected field/}).click();await dialog.getByText('Ready to review.',{exact:true}).waitFor();assert.deepEqual(calls,['personality']);
 await dialog.getByRole('button',{name:'Apply selected drafts to editor'}).click();await dialog.getByRole('button',{name:'Close',exact:true}).click();
 const authored=await page.locator('#cs-personality').inputValue();assert(authored.includes('fantasy archivist'));
 await page.locator('[data-vh-page-builder="cs-identity"]').click();dialog=page.locator('dialog[open]');assert.equal(await selected().count(),0,'Page action requires explicit choices');assert.match(await dialog.innerText(),/0 (?:selected )?(?:field|request)|(?:field|request)s? selected: 0|select.*field/i);assert.equal(calls.length,1);
 const pageChoices=dialog.locator('section > label:first-child input');for(let i=0;i<4;i++)await pageChoices.nth(i).check();const callsBeforeConfirmation=calls.length;
 await dialog.getByRole('button',{name:/Draft 4 selected fields/}).click();assert.equal(calls.length,callsBeforeConfirmation,'Four paid field requests require explicit confirmation');
 assert(await dialog.getByRole('button',{name:'Confirm 4 paid requests',exact:true}).isVisible(),'Confirmation names the exact paid request count');
 await dialog.getByRole('button',{name:'Close',exact:true}).click();
 assert.equal(await page.evaluate(()=>VH_AI_HELPERS.some(h=>h.id==='world')),false,'Whole world option retired');
	 await page.getByRole('button',{name:'Back to Virtual Humans 2.0'}).click();await page.locator('#companions-view').waitFor({state:'visible'});
	 const authoredCard=page.locator('.vh-card').filter({hasText:'Iri the Archivist'});
	 assert.equal(await authoredCard.count(),1,'Authored human has one library card');
	 assert(await authoredCard.locator('[data-vh-edit]').isVisible(),'Library exposes one clear Edit human action per human');
	 assert(await authoredCard.locator('[data-vh-delete]').isVisible(),'Library exposes a visible Delete action per human');
	 assert.equal(await page.locator('[data-vh-life]').count(),0,'Life is not a competing library destination');
	 await authoredCard.locator('[data-vh-chat]').click();await page.waitForFunction(()=>state.view==='companionChat');
 assert.equal(await page.locator('#vh-primary-chat [data-mode=life]').innerText(),'Live human','Chat exposes the evolving timeline with an explicit name');
 assert.equal(await page.locator('#vh-primary-chat [data-mode=studio]').innerText(),'Edit human');
 await page.locator('#vh-primary-chat [data-mode=life]').click();await page.waitForFunction(()=>state.view==='vhWorkspace');
 assert.equal(await page.locator('#vh-workspace-title').innerText(),'Start a persistent life','A human without a live timeline opens intentional onboarding');
 assert(await page.locator('#vh-workspace-view').evaluate(el=>el.classList.contains('is-unstarted')),'Pre-life workspace is visibly distinct');
 assert.equal(await page.locator('#vh-workspace-nav').isVisible(),false,'Unavailable live sections are not presented as working navigation');
 assert.equal(await page.locator('.vh-workspace-search').isVisible(),false,'Unavailable live settings are not searchable');
 assert.equal(await page.locator('[data-start-persistent]').isVisible(),true,'Persistent life has one explicit start action');
 await page.locator('#vh-primary-life [data-mode=studio]').click();await page.waitForFunction(()=>state.view==='companionStudio');
 await page.locator('#vh-primary-studio [data-mode=chat]').click();await page.waitForFunction(()=>state.view==='companionChat');
 // A fictional UTC night is a legitimate waiting state, never a connection failure.
 await page.clock.setFixedTime(new Date('2026-09-20T04:00:00Z'));
 await page.evaluate(()=>{const c=getCompanion(state.activeCompanionId);c.locationMode='custom';c.timezoneOffsetMinutes=0;c.timezone='UTC';c.sleepArchetype='normal';renderCompanionThread();});
 assert.deepEqual(await page.evaluate(()=>companionChatExperience(state.activeCompanionId)),await page.evaluate(()=>companionExperiencePreset('realistic')),'New characters preserve realistic timing');
 await page.locator('#companion-composer-input').fill('Hello. What stories do you guard?');await page.locator('#companion-send-btn').click();
 await page.waitForFunction(()=>document.getElementById('companion-chat-view').innerText.includes('asleep'));
 const night=await page.evaluate(()=>({text:document.getElementById('companion-chat-view').innerText,reply:getCompanionThread(state.activeCompanionId).some(m=>m.role==='companion'),message:getCompanionThread(state.activeCompanionId).find(m=>m.role==='user')}));
 assert.equal(night.reply,false,'No reply while asleep');assert.equal(night.message.awaitingReply,true,'Sleeping message remains queued');assert.doesNotMatch(night.text,/connection failed|provider error|retry reply/i,'Waiting is not shown as provider failure');
 // Advance fictional time through natural attention checks without changing experience flags.
 let simulated=Date.parse('2026-09-20T12:00:00Z');
 for(let step=0;step<24;step++){
  await page.clock.setFixedTime(new Date(simulated));await page.evaluate(now=>processCompanionAgency(now),simulated);
  const result=await page.evaluate(()=>{const messages=getCompanionThread(state.activeCompanionId);return {reply:messages.some(m=>m.role==='companion'&&m.text.includes('Local mock model reply')),next:messages.find(m=>m.role==='user'&&m.awaitingReply)?.attention?.nextCheckAt};});
  if(result.reply)break;simulated=Math.max(simulated+60000,Number(result.next)||0);
 }
 assert.match(await page.locator('#companion-messages').innerText(),/Local mock model reply/,'Awake character replies through normal attention progression');
 assert.equal(await page.evaluate(()=>companionChatExperience(state.activeCompanionId).realTimeLife),true,'Reply did not enable instant timing');
 await page.locator('#vh-chat-more > summary').click();await page.locator('#companion-immersion-menu > summary').click();await page.locator('[data-companion-immersion-preset=instant]').click();
 await page.waitForFunction(()=>companionChatExperience(state.activeCompanionId).realTimeLife===false);
 const id=await page.evaluate(()=>state.activeCompanionId);assert.equal(await page.locator('dialog[open]').count(),0,'Chat opens without mandatory life-setup dialog');
 await page.reload();await page.waitForFunction(()=>typeof companionAgencyTimer!=='undefined'&&!!companionAgencyTimer);
 await page.evaluate(id=>{clearInterval(companionAgencyTimer);clearInterval(companionAlwaysOnTimer);openCompanionStudio(id);switchView('companionStudio');activateCompanionStudioTab('cs-identity');},id);
 assert.equal(await page.locator('#cs-name').inputValue(),'Iri the Archivist');assert.equal(await page.locator('#cs-personality').inputValue(),authored,'Saved AI brief survives reload');
 await page.addStyleTag({content:'*,*::before,*::after{animation:none!important;transition:none!important;scroll-behavior:auto!important}'});
 const out='docs/vh2/creation-ux-20260920';fs.mkdirSync(out,{recursive:true});await page.screenshot({path:out+'/desktop-creator.png',fullPage:true});
 await page.setViewportSize({width:390,height:844});assert(await page.locator('#cs-name').isVisible());assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'No mobile horizontal overflow');
 await page.screenshot({path:out+'/mobile-creator.png',fullPage:true});await page.locator('#tab-cs-identity .vh-authoring-group').first().screenshot({path:out+'/mobile-core.png'});
 const beforeDelete=await page.evaluate(()=>state.companions.length);page.once('dialog',dialog=>dialog.accept());await page.locator('#delete-companion-btn').click();await page.locator('#companions-view').waitFor({state:'visible'});
 assert.equal(await page.evaluate(()=>state.companions.length),beforeDelete-1,'Delete human removes the isolated test human after confirmation');
 assert.equal(await page.evaluate(id=>state.companions.some(companion=>companion.id===id),id),false,'Deleted human no longer exists');
 assert.deepEqual(errors,[]);console.log('PASS VH creation journey: complete system map, organized dense authoring, working scroll, scoped AI, explicit page selection, saved chat entry, night waiting, natural awake reply, explicit instant opt-in, reload, mobile.');
}finally{if(browser)await browser.close();server.kill();}
})().catch(e=>{console.error(e);process.exitCode=1;});
