'use strict';
const {spawn}=require('node:child_process'),assert=require('node:assert/strict');
const {chromium,launchOptions}=require('./browser_runtime').browserRuntime();
(async()=>{const server=spawn('python3',['scratch/vh2_browser_server.py'],{stdio:['ignore','pipe','pipe']});let browser;
try{
 const port=await new Promise((resolve,reject)=>{server.stdout.once('data',d=>resolve(+String(d).trim()));server.stderr.on('data',d=>process.stderr.write(d));server.once('exit',c=>reject(Error('server '+c)));}),base=`http://127.0.0.1:${port}`;
 browser=await chromium.launch(launchOptions);const page=await browser.newPage({viewport:{width:1280,height:1000}}),errors=[];page.on('pageerror',e=>errors.push(e.message));page.setDefaultTimeout(10000);await page.route('**/*',r=>r.request().url().startsWith(base)?r.continue():r.abort());await page.goto(base+'/index.html');await page.waitForFunction(()=>typeof companionAgencyTimer!=='undefined'&&!!companionAgencyTimer);
 await page.evaluate(base=>{clearInterval(companionAgencyTimer);clearInterval(companionAlwaysOnTimer);mcpBridgeBase=()=>base;Object.assign(state.globalSettings,{localBaseUrl:base+'/test',localApiKey:'LOCAL_TEST_KEY',apiProvider:'local',defaultModel:'browser-fixture'});const c=normalizeCompanion({id:'feedback-alex',name:'Alex',age:28,personality:'Curious',textProvider:'local',model:'browser-fixture',lifeProfile:{initializedAt:Date.now(),places:[{id:'home',label:'Home',kind:'home'}],socialCircle:[],weeklySchedule:[]}});state.companions=[c];state.activeCompanionId=c.id;state.companionTimelines={};state.companionThreads={};ensureCompanionTimelineStore(c.id);hideGlobalSettings();},base);
 await page.evaluate(()=>vh2CreateTimeline(getCompanion('feedback-alex')));await page.waitForFunction(()=>!!getActiveCompanionTimeline('feedback-alex')?.vh2?.worldId);
 await page.evaluate(async()=>{const t=getActiveCompanionTimeline('feedback-alex');await vhUiCommand(t,'upsert_place',{place:{id:'placeholder',label:'Placeholder',kind:'other'}});await vhUiCommand(t,'save_place_zone',{placeId:'placeholder',zoneId:'test-room',label:'Draft room',description:'Old description'});await vhOpenPlace(getCompanion('feedback-alex'),'placeholder');});
 let dialog=page.getByRole('dialog',{name:'Placeholder',exact:true});await dialog.getByRole('button',{name:'Edit room',exact:true}).click();let room=page.getByRole('dialog',{name:'Edit room',exact:true});await room.getByRole('button',{name:'Remove room',exact:true}).click();await page.waitForFunction(()=>!getActiveCompanionTimeline('feedback-alex').vh2.visual.zones.some(z=>z.id==='test-room'));
 dialog=page.getByRole('dialog',{name:'Placeholder',exact:true});await dialog.getByRole('button',{name:'Remove this place and its rooms',exact:true}).click();await page.waitForFunction(()=>!getActiveCompanionTimeline('feedback-alex').vh2.travelPlaces.some(p=>p.id==='placeholder'));
 const currentPlace=await page.evaluate(()=>{const c=getCompanion('feedback-alex'),t=getActiveCompanionTimeline(c.id),p=t.vh2.travelPlaces.find(p=>p.id===t.vh2.present.placeId);if(!p)throw Error('No current place');vhOpenPlace(c,p.id);return {id:p.id,label:p.label};});dialog=page.getByRole('dialog',{name:currentPlace.label,exact:true});await dialog.getByRole('button',{name:'Remove this place and its rooms',exact:true}).click();await dialog.getByRole('status').filter({hasText:'still used'}).waitFor();await dialog.getByRole('button',{name:'Close',exact:true}).click();
 await page.evaluate(placeId=>vhRoutineEditor(getCompanion('feedback-alex'),'weeklySchedule',{id:'dinner',activity:'Dinner',startMinute:420,endMinute:1200,days:[1],placeId,availability:'busy',flexibility:'fixed'}),currentPlace.id);dialog=page.getByRole('dialog',{name:'Edit commitment',exact:true});assert.match(await dialog.innerText(),/780 minutes/);await dialog.getByLabel('Conversation availability').selectOption('available');await dialog.getByRole('button',{name:'Save commitment',exact:true}).click();await page.waitForFunction(()=>getActiveCompanionTimeline('feedback-alex').vh2.setupProfile.weeklySchedule.some(r=>r.id==='dinner'&&r.availability==='available'));
 await page.evaluate(()=>vhRoutineEditor(getCompanion('feedback-alex'),'activityOptions'));dialog=page.getByRole('dialog',{name:'Add activity',exact:true});assert.match(await dialog.innerText(),/do not make it last for the entire window/);await dialog.getByLabel('Name',{exact:true}).fill('Read');await dialog.getByLabel('Duration each time',{exact:false}).fill('25');await dialog.getByRole('button',{name:'Save activity',exact:true}).click();await page.waitForFunction(()=>getActiveCompanionTimeline('feedback-alex').vh2.setupProfile.activityOptions.some(r=>r.label==='Read'&&r.durationMinutes===25));
 await page.evaluate(()=>vhOpenLifeStatus(getCompanion('feedback-alex')));dialog=page.getByRole('dialog',{name:'Life status',exact:true});await dialog.getByRole('button',{name:'Pause life',exact:true}).click();await dialog.getByRole('button',{name:'Resume life',exact:true}).waitFor();assert.match(await dialog.innerText(),/attention timers are paused/);await dialog.getByRole('button',{name:'Resume life',exact:true}).click();await dialog.getByRole('button',{name:'Pause life',exact:true}).waitFor();await dialog.getByRole('button',{name:'Restart life service state…',exact:true}).click();await page.getByRole('dialog',{name:'Reboot current life',exact:true}).getByRole('button',{name:'Reboot life — keep history',exact:true}).waitFor();
 await page.evaluate(()=>{document.querySelectorAll('dialog[open]').forEach(d=>d.close());vhOpenWorkspace('possessions','feedback-alex');vhOpenPanel('Gifts & money');});
 const openGifts=async()=>{await page.locator('#vh2-gifts-panel > details > summary').filter({hasText:'Gift preferences & starting funds'}).click();};await openGifts();
 const giftLabels=['Enable gifts','Permission to receive mailed gifts','Permission to receive money'],expected=[];
 for(const label of giftLabels){const checkbox=page.getByRole('checkbox',{name:label,exact:true});assert(await checkbox.isVisible(),label+' should be visible');const box=await checkbox.boundingBox();assert(box.width>=14&&box.height>=14,label+' has a visible hit area');const style=await checkbox.evaluate(el=>({appearance:getComputedStyle(el).appearance,opacity:getComputedStyle(el).opacity}));assert.notEqual(style.appearance,'none',label+' renders a native checkbox');assert.notEqual(style.opacity,'0');expected.push(!await checkbox.isChecked());await checkbox.focus();await checkbox.press('Space');assert.equal(await checkbox.isChecked(),expected.at(-1),label+' responds to keyboard');}
 await page.getByRole('button',{name:'Save gift preferences',exact:true}).click();await page.waitForFunction(values=>{const p=getActiveCompanionTimeline('feedback-alex').vh2.gifts.policy;return p.enabled===values[0]&&p.mailAllowed===values[1]&&p.cashAllowed===values[2];},expected);
 await page.reload();await page.waitForFunction(()=>typeof companionAgencyTimer!=='undefined'&&!!getCompanion('feedback-alex'));
 await page.evaluate(async base=>{clearInterval(companionAgencyTimer);clearInterval(companionAlwaysOnTimer);mcpBridgeBase=()=>base;const c=getCompanion('feedback-alex');await vh2Poll(c,getActiveCompanionTimeline(c.id),{force:true,throwOnError:true});vhOpenWorkspace('possessions',c.id);vhOpenPanel('Gifts & money');},base);await openGifts();
 for(let i=0;i<giftLabels.length;i++){const checkbox=page.getByRole('checkbox',{name:giftLabels[i],exact:true});assert(await checkbox.isVisible());assert.equal(await checkbox.isChecked(),expected[i],giftLabels[i]+' persists after reload');}
 assert.deepEqual(errors,[]);console.log('PASS browser: remove room/place, referenced-place error, 13-hour schedule explanation, edit availability, activity duration, pause/resume, discoverable restart, gifts/mail/money checkbox visibility + keyboard toggle + save/reload.');
}finally{if(browser)await browser.close();server.kill();}})().catch(e=>{console.error(e);process.exitCode=1;});
