const assert=require('node:assert/strict');
const world=require('../vh-world-engine'),voice=require('../vh-conversation-engine');
global.VHConversationEngine=voice;global.VHActivityEngine=require('../vh-activity-engine');const core=require('../vh-simulation-core');
const minute=60000,day=86400000,base=Date.UTC(2026,8,8),at=m=>base+m*minute;
function person(){return {id:'a',humanDynamics:{energy:80,stress:0},relationshipDynamics:{trust:50,comfort:20},commitments:[],continuityRuntime:{conversation:{status:'paused',topic:'weekend plans'}},lifeProfile:{world:world.config({transport:{enabled:false},gifts:{enabled:true,mailAllowed:true,deliveryHours:0,openingMinutes:3},items:[{id:'shirt',name:'Blue shirt',category:'top',owned:false}],people:[]}),places:[{id:'home',kind:'home',label:'Home'},{id:'gym',label:'Gym'}],weeklySchedule:[],travelLegs:[],socialCircle:[]},lifeRuntime:{world:world.runtime(),environment:{weatherCode:0}}};}
const local=(c,t)=>{const d=new Date(t);return {dateKey:d.toISOString().slice(0,10),weekday:d.getUTCDay(),hour:d.getUTCHours(),minute:d.getUTCMinutes()};};
let location='gym';const baseline=()=>({placeId:location,availability:'available'});
const p=person();world.offerGift(p,{id:'parcel',kind:'item',itemId:'shirt',value:10},at(0));world.advance(p,at(1),local,baseline);
assert.equal(p.lifeRuntime.world.gifts[0].status,'delivered');assert(!p.lifeRuntime.world.inventory.includes('shirt'));
location='home';world.advance(p,at(2),local,baseline);assert.equal(p.lifeRuntime.world.gifts[0].status,'collected');world.advance(p,at(4),local,baseline);assert(!p.lifeRuntime.world.inventory.includes('shirt'));
world.advance(p,at(5),local,baseline);assert(p.lifeRuntime.world.inventory.includes('shirt'));assert(world.pendingFollowup(p,at(5)));
const pending=world.pendingFollowup(p,at(5));assert(!world.acknowledge(p,{id:pending.id,evidence:'I opened it'},'unrelated reply',at(5)));assert.equal(pending.status,'pending');assert(world.acknowledge(p,{id:pending.id,evidence:'I opened the blue shirt'},'I opened the blue shirt just now',at(5)));assert.equal(pending.status,'addressed');
const count=p.lifeRuntime.world.events.length;world.advance(p,at(5),local,baseline);assert.equal(p.lifeRuntime.world.events.length,count);
const transport=person();const walk={mode:'WALK',minutes:10,cost:0},ride={mode:'RIDESHARE',minutes:12,cost:5};assert(world.routeScore(transport,walk)<world.routeScore(transport,ride));transport.humanDynamics.energy=10;transport.lifeRuntime.environment.weatherCode=63;assert(world.routeScore(transport,walk)>world.routeScore(transport,ride));
const disrupted=person();disrupted.lifeProfile.world.transport.enabled=true;disrupted.lifeProfile.weeklySchedule=[{id:'appointment',placeId:'gym',activity:'attend the gym session',days:[2],startMinute:480,endMinute:500}];world.advance(disrupted,at(480),local,baseline);world.advance(disrupted,at(511),local,baseline);assert(disrupted.lifeRuntime.world.events.some(e=>e.kind==='recovery_action'));assert.equal(disrupted.lifeRuntime.world.recoveries[0].status,'decided');assert(disrupted.lifeRuntime.world.events.some(e=>e.kind==='missed'));
const long=person();long.commitments=[{id:'promise',status:'pending',dueAt:at(60),text:'call'}];world.advance(long,at(0),local,baseline);world.advance(long,base+10*day,local,baseline);assert.equal(long.commitments[0].status,'missed');assert(long.lifeRuntime.world.events.some(e=>e.kind==='reconciliation'));const reloaded=JSON.parse(JSON.stringify(long));reloaded.lifeRuntime.world=world.runtime(reloaded.lifeRuntime.world);world.advance(reloaded,base+10*day,local,baseline);assert.deepEqual(reloaded.lifeRuntime.world,long.lifeRuntime.world);
const npc=person();npc.lifeProfile.socialCircle=[{id:'friend',name:'Jo'}];npc.lifeProfile.world.people=[{personId:'friend',placeId:'home',days:[2],start:0,end:60,activity:'writing',goal:'finish a draft',goalMinutes:5}];world.advance(npc,at(0),local,baseline);world.advance(npc,at(6),local,baseline);assert(npc.lifeRuntime.world.people.friend.goalCompleted);assert(npc.lifeRuntime.world.events.some(e=>e.personId==='friend'));
const relation=person();relation.lifeProfile.world.frame=world.config({frame:{mode:'dating',minComfort:10,requestMinutes:0}}).frame;relation.relationshipDynamics={trust:0,comfort:-20,resentment:60};world.requestConnection(relation,at(0));world.advance(relation,at(1),local,baseline);assert.equal(relation.lifeRuntime.world.connection.state,'declined');
let memory={};const message={id:'london',role:'user',text:"I'm from London",timestamp:at(1),readAt:at(1),playerPersonaId:'p1'};voice.learnPlayerFacts(memory,[message],'p1',at(1));memory=core.normalizeCompanionContinuityRuntime?core.normalizeCompanionContinuityRuntime(memory):JSON.parse(JSON.stringify(memory));assert.match(voice.playerFactsBrief(memory,'p1'),/London/);assert.equal(voice.playerFactsBrief(memory,'p2'),'');voice.learnPlayerFacts(memory,[message],'p2',at(2));assert.equal(voice.playerFactsBrief(memory,'p2'),'');
voice.learnPlayerFacts(memory,[{...message,id:'correction',text:"I'm from Manchester",timestamp:at(3),readAt:at(3)}],'p1',at(3));assert.match(voice.playerFactsBrief(memory,'p1'),/Manchester/);assert.doesNotMatch(voice.playerFactsBrief(memory,'p1'),/London/);
voice.learnPlayerFacts(memory,[{...message,id:'quote',text:'She said "I live in Paris"',timestamp:at(4),readAt:at(4)}],'p1',at(4));assert.doesNotMatch(voice.playerFactsBrief(memory,'p1'),/Paris/);
console.log('PASS physical delivery, evidence-based follow-through, transport context, recovery, absence, supporting goals, relationship gates and persona-scoped facts');
const executable=person();executable.locationMode='custom';executable.timezoneOffsetMinutes=0;
executable.lifeProfile=core.normalizeCompanionLifeProfile({...executable.lifeProfile,initializedAt:1,weeklySchedule:[{id:'miss',placeId:'gym',activity:'attend the appointment',days:[2],startMinute:480,endMinute:500}],world:{...executable.lifeProfile.world,transport:{...executable.lifeProfile.world.transport,enabled:true}}});
executable.lifeRuntime=core.normalizeCompanionLifeRuntime({});executable.continuityRuntime=core.normalizeCompanionContinuityRuntime(executable.continuityRuntime);
core.advanceCompanionWorld(executable,at(480));core.advanceCompanionWorld(executable,at(511));
assert(executable.lifeRuntime.activities.goals.some(g=>g.id.startsWith('world:recovery-action:')),'recovery decision must create an executable activity through the shared kernel');
console.log('PASS recovery decision creates a real activity through the shared simulation kernel');
// Replying occupies real time: it can delay departure and cause a late arrival.
function journeyDuringChat(until){const c=person();c.lifeProfile.world.transport.enabled=true;c.lifeProfile.world.transport.delayChance=0;c.lifeProfile.weeklySchedule=[{id:'class',placeId:'gym',activity:'class',days:[2],startMinute:480,endMinute:500}];c.lifeProfile.travelLegs=[{from:'home',to:'gym',mode:'WALK',minutes:10,cost:0}];c.lifeRuntime.activities={conversationUntil:at(until)};return c;}
const texting=journeyDuringChat(475);world.advance(texting,at(469),local,baseline);world.advance(texting,at(486),local,baseline);
const arrival=texting.lifeRuntime.world.events.find(e=>e.kind==='arrival');assert.equal(arrival.lateMinutes,5);assert(texting.lifeRuntime.world.events.some(e=>e.kind==='departure_wait'));
const missedChat=journeyDuringChat(510);world.advance(missedChat,at(469),local,baseline);world.advance(missedChat,at(501),local,baseline);assert(missedChat.lifeRuntime.world.events.some(e=>e.kind==='missed'));assert(!missedChat.lifeRuntime.world.journey);
console.log('PASS attention delays departure, produces an actual late arrival, and records missed windows without teleporting');
