const assert=require('node:assert/strict');
const engine=require('../virtual_humans/engine/vh-conversation-engine');
const activities=require('../virtual_humans/engine/vh-activity-engine');
const now=100000;
function person(){const state=activities.normalize();const goal=activities.addGoal(state,'focus','project',now-1000,'a chapter');goal.status='active';goal.steps[0].progressMs=250;
 return {humanDynamics:{energy:70,socialNeed:60,cooldownUntil:0},emotionExpression:'guarded',commitments:[{id:'promise',text:'Call tomorrow',status:'pending',dueAt:now+1000}],lifeRuntime:{activities:state},continuityRuntime:{conversation:engine.normalize()}};}
const messages=[{id:'u',role:'user',text:'Can you stay a little longer?',timestamp:now-1,readAt:now-1,awaitingReply:true}];
const situation={source:'activity',availability:'busy'};
const c=person();
const before=engine.decisionContext(c,messages,now,situation);
assert(before.candidates.some(m=>m.id==='company'));assert(before.candidates.some(m=>m.id==='promise:promise'));assert(before.canMakeTime);
const choice={motiveId:'company',action:'make_time',evidence:'stay a little longer'};
assert(engine.enactChoice(c,choice,messages,now,situation,activities));
assert.equal(c.lifeRuntime.activities.goals[0].status,'paused');assert.equal(c.lifeRuntime.activities.goals[0].steps[0].progressMs,250);
const until=c.lifeRuntime.activities.conversationUntil;const serialized=JSON.stringify(c);
assert.equal(engine.enactChoice(c,choice,messages,now+1,situation,activities),null);assert.equal(c.lifeRuntime.activities.conversationUntil,until);
const reload=JSON.parse(serialized);reload.continuityRuntime.conversation=engine.normalize(reload.continuityRuntime.conversation);
assert.equal(engine.enactChoice(reload,choice,messages,now+2,situation,activities),null);
assert.equal(c.commitments[0].status,'pending');
for(const blocked of [{source:'schedule',availability:'busy'},{source:'activity',availability:'asleep'},{source:'activity',availability:'private'}])assert.equal(engine.enactChoice(person(),choice,messages,now,blocked,activities),null);
assert.equal(engine.enactChoice(person(),{...choice,evidence:'invented quote'},messages,now,situation,activities),null);
assert.equal(engine.enactChoice(person(),{...choice,motiveId:'invented-secret'},messages,now,situation,activities),null);
assert.equal(engine.enactChoice(person(),choice,[{...messages[0],readAt:0}],now,situation,activities),null);
const tired=person();tired.humanDynamics.energy=10;tired.humanDynamics.socialNeed=0;
const tiredContext=engine.decisionContext(tired,messages,now,situation);assert(tiredContext.candidates.some(m=>m.id==='rest'));assert(!tiredContext.candidates.some(m=>m.id==='company'));assert(!tiredContext.canMakeTime);
const cooled=person();cooled.humanDynamics.cooldownUntil=now+10000;assert(!engine.decisionContext(cooled,messages,now,situation).canMakeTime);
console.log('PASS same message produces different grounded motives with different life state; actual solo task pause, progress, promise and reload dedupe');
console.log('PASS sleep, protected schedules, private time, cooldown, unread input and invented evidence cannot authorize actions');
const {functionSource}=require('./app_source');
for(const f of ['buildCompanionContextPacket','buildCompanionSystemPrompt'])assert(functionSource(f).includes('decisionContext'));
assert(functionSource('companionCompactPrompt').includes('decisionBrief'));
assert(functionSource('scheduleCompanionTurnObservation').includes('enactChoice'));
assert(functionSource('sendCompanionMessage').includes('enactChoice'));
console.log('PASS full, compact, foreground and observer path wiring');
