'use strict';
const {spawn}=require('node:child_process'),assert=require('node:assert/strict'),fs=require('node:fs');
const { chromium, launchOptions } = require('./browser_runtime').browserRuntime();
(async()=>{const server=spawn('python3',['scratch/vh2_browser_server.py'],{stdio:['ignore','pipe','pipe']});let browser;
try{const port=await new Promise((resolve,reject)=>{server.stdout.once('data',d=>resolve(+String(d).trim()));server.stderr.on('data',d=>process.stderr.write(d));server.once('exit',c=>reject(Error('server '+c)));});const base=`http://127.0.0.1:${port}`;
browser=await chromium.launch(launchOptions);const page=await browser.newPage({viewport:{width:1440,height:1000}});const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.route('**/*',r=>r.request().url().startsWith(base)?r.continue():r.abort());await page.goto(base+'/index.html');await page.addStyleTag({content:'*,*::before,*::after{animation:none!important;transition:none!important;scroll-behavior:auto!important}'});await page.waitForFunction(()=>typeof companionAgencyTimer!=='undefined'&&!!companionAgencyTimer);
await page.evaluate(base=>{clearInterval(companionAgencyTimer);clearInterval(companionAlwaysOnTimer);mcpBridgeBase=()=>base;state.globalSettings.localBaseUrl=base+'/test';state.globalSettings.localApiKey='LOCAL_TEST_KEY';state.globalSettings.apiProvider='local';state.globalSettings.defaultModel='browser-fixture';const c=normalizeCompanion({id:'ux-alex',name:'Alex Morgan',age:28,personality:'Reserved and curious',textProvider:'local',model:'browser-fixture',lifeProfile:{world:{gifts:{enabled:true,mailAllowed:true,cashAllowed:true,minTrust:-100}},places:[{id:'home',label:'Apartment',kind:'home'},{id:'cafe',label:'Corner Cafe',kind:'social'}],weeklySchedule:[],sleepPolicy:{enabled:false}}});state.companions=[c];state.activeCompanionId=c.id;state.companionTimelines={};state.companionThreads={};ensureCompanionTimelineStore(c.id);hideGlobalSettings();switchView('companionChat');renderCompanionThread();},base);
await page.evaluate(()=>vh2CreateTimeline(getCompanion('ux-alex')));await page.waitForFunction(()=>!!getActiveCompanionTimeline('ux-alex')?.vh2?.worldId);const world=await page.evaluate(()=>getActiveCompanionTimeline('ux-alex').vh2.worldId);

// Exercise the reviewed builder contract through the actual browser and service.
await page.evaluate(()=>vhReviewLifeProposal(getCompanion('ux-alex'),{sleepPolicy:{sleepNeedHours:9},rooms:[{id:'builder_room',placeId:'home',label:'Reading room',description:'A quiet room with a window'}],referencePlan:[{id:'builder_ref',role:'zone',entityId:'builder_room',view:'establishing',label:'Reading room view',description:'Quiet room, soft daylight'}]}));
await page.locator('#vh-life-proposal [data-apply]').click();await page.locator('#vh-life-proposal [data-apply]').filter({hasText:'Applied'}).waitFor();await page.locator('#vh-life-proposal [data-close]').click();
await page.evaluate(()=>vhOpenWorkspace('references'));await page.getByRole('heading',{name:'Reading room view',exact:true}).waitFor();
assert.equal(await page.evaluate(()=>getActiveCompanionTimeline('ux-alex').vh2.setupProfile.sleepPolicy.sleepNeedHours),9);
await page.evaluate(()=>{const host=document.createElement('div');host.id='meaningful-fixture';host.innerHTML='<label>Willingness to trust (0–100)<input type="number" value="50"></label>';document.body.append(host);vhMeaningfulControls(host);});
await page.locator('#meaningful-fixture select').selectOption('80');assert.equal(await page.locator('#meaningful-fixture input').inputValue(),'80');assert.equal(await page.locator('#meaningful-fixture input').isVisible(),false);await page.evaluate(()=>document.getElementById('meaningful-fixture').remove());

const out='docs/vh2/master-ux-20260910';fs.mkdirSync(out,{recursive:true});
await page.evaluate(()=>{openCompanionStudio('ux-alex');switchView('companionStudio');});await page.locator('[data-tab="cs-life"]').click();await page.screenshot({path:out+'/life-desktop.png'});assert.equal(await page.locator('#cs-legacy-place-references').isVisible(),false);assert.equal(await page.locator('.vh-life-source-map').isVisible(),false);
await page.locator('[data-destination=closet]').click();await page.getByRole('button',{name:'Add outfit preset',exact:true}).click();let d=page.getByRole('dialog',{name:'Add outfit preset'});await d.locator('[name=label]').fill('Favourite café look');await d.locator('[name=items]').fill('Blue linen shirt, cream trousers and white trainers');await d.getByRole('button',{name:'Save preset',exact:true}).click();await page.waitForFunction(()=>[...document.querySelectorAll('dialog [role=status]')].some(e=>e.textContent==='Outfit preset saved.'));await d.locator('[name=notes]').fill('Updated after the first save');await d.getByRole('button',{name:'Save changes',exact:true}).click();await d.getByRole('button',{name:'Saved',exact:true}).waitFor();await d.getByRole('button',{name:'Close',exact:true}).click();assert.equal(await page.getByRole('heading',{name:'Favourite café look',exact:true}).count(),1);await page.screenshot({path:out+'/outfit-presets.png'});
await page.getByRole('tab',{name:/Style preferences/}).click();await page.getByRole('button',{name:/Everyday casual/}).click();d=page.getByRole('dialog',{name:'Create a style preference'});await d.locator('[name=name]').fill('Alex’s everyday style');await d.getByRole('button',{name:'Save style preference',exact:true}).click();await page.waitForFunction(()=>[...document.querySelectorAll('dialog [role=status]')].some(e=>e.textContent==='Style preference saved.'));await d.getByRole('button',{name:'Close',exact:true}).click();assert.equal(await page.getByRole('heading',{name:'Alex’s everyday style'}).count(),1);await page.screenshot({path:out+'/style-preferences.png'});await page.getByRole('combobox',{name:'How they choose clothes',exact:true}).selectOption('presets');await page.waitForFunction(()=>getActiveCompanionTimeline('ux-alex').vh2.closet.enabled===false);await page.evaluate(async()=>vhUiCommand(getActiveCompanionTimeline('ux-alex'),'add_owned_item',{name:'Test shirt',category:'top',tags:[],photo:''}));await page.getByRole('tab',{name:/Clothing items/}).click();await page.getByRole('button',{name:'Edit item',exact:true}).click();d=page.getByRole('dialog',{name:'Edit clothing item'});await d.locator('[name=name]').fill('Blue linen shirt');await d.getByRole('button',{name:'Save item',exact:true}).click();await page.getByRole('heading',{name:'Blue linen shirt',exact:true}).waitFor();await page.getByRole('button',{name:'Edit item',exact:true}).click();await page.getByRole('button',{name:'Remove from rotation',exact:true}).click();await page.waitForFunction(()=>!document.querySelector('dialog[aria-label="Edit clothing item"]'));assert.equal(await page.getByRole('heading',{name:'Blue linen shirt',exact:true}).count(),0);

await page.evaluate(()=>vhOpenWorkspace('places'));assert.equal(await page.locator('#vh2-chat-controls>details:visible').count(),0);await page.getByRole('button',{name:'Add place',exact:true}).click();d=page.getByRole('dialog',{name:'Add place'});await d.locator('[name=label]').fill('Riverside café');await d.locator('[name=kind]').selectOption('social');await d.getByRole('button',{name:'Create place',exact:true}).click();await page.locator('#vh-place-editor').waitFor();await page.locator('#vh-place-editor [data-room-form] [name=label]').fill('Main room');await page.locator('#vh-place-editor [data-room-form] button').click();await page.getByRole('button',{name:'Edit room',exact:true}).click();d=page.getByRole('dialog',{name:'Edit room',exact:true});await d.locator('[name=label]').fill('Dining room');await d.getByRole('button',{name:'Save room',exact:true}).click();await page.locator('#vh-place-editor').getByRole('heading',{name:'Dining room',exact:true}).waitFor();await page.locator('#vh-place-editor [data-close]').click();await page.getByRole('searchbox',{name:'Find a place',exact:true}).fill('Riverside');assert.equal(await page.locator('#vh-workspace-special .vh-entity-grid>.vh-entity-card:visible').count(),1);await page.screenshot({path:out+'/places-filter.png'});
const projection=await(await fetch(base+'/vh2/projection?worldId='+world)).json();const c=projection.state.truth.companion;assert(c.lifeProfile.wardrobe.some(p=>p.label==='Favourite café look'));assert(c.vh2Closet.styles.some(s=>s.name==='Alex’s everyday style'));assert(c.lifeProfile.places.some(p=>p.label==='Riverside café'));
await page.evaluate(()=>vhOpenWorkspace('people'));await page.getByRole('button',{name:'Add person',exact:true}).click();d=page.getByRole('dialog',{name:'Add person'});await d.locator('[name=name]').fill('Sam Rivera');await d.locator('[name=relationship]').fill('Old friend');await d.getByRole('button',{name:'Save person',exact:true}).click();await page.getByRole('heading',{name:'Sam Rivera',exact:true}).waitFor();await page.screenshot({path:out+'/people.png'});
await page.evaluate(()=>vhOpenWorkspace('life'));await page.getByRole('button',{name:'Add commitment',exact:true}).click();d=page.getByRole('dialog',{name:'Add commitment'});await d.locator('[name=label]').fill('Morning shift');await d.getByRole('button',{name:'Save commitment',exact:true}).click();await page.getByRole('heading',{name:'Morning shift',exact:true}).waitFor();await page.getByRole('button',{name:'Add activity',exact:true}).click();d=page.getByRole('dialog',{name:'Add activity'});await d.locator('[name=label]').fill('Practice guitar');await d.getByRole('button',{name:'Save activity',exact:true}).click();await page.getByRole('heading',{name:'Practice guitar',exact:true}).waitFor();await page.screenshot({path:out+'/routine.png'});
const failure=await page.evaluate(async()=>{const t=getActiveCompanionTimeline('ux-alex');try{await vhUiCommand(t,'configure_person_network',{enabled:'invalid',policy:{}});}catch(e){return {message:e.message,queued:t.vh2.outbox.length};}return {unexpectedSuccess:true};});assert.equal(failure.queued,0,'invalid newly supported commands cannot poison the queue');
let conflictInjected=false;await page.route('**/vh2/command',async route=>{const body=route.request().postDataJSON();if(body.type==='upsert_place'&&!conflictInjected){conflictInjected=true;return route.fulfill({status:409,contentType:'application/json',body:JSON.stringify({error:'World changed; reload revision'})});}return route.continue();});await page.evaluate(async()=>vhUiCommand(getActiveCompanionTimeline('ux-alex'),'upsert_place',{place:{id:'retry_test',label:'Retry test place',kind:'other'}}));assert(conflictInjected);await page.unroute('**/vh2/command');const latest=await(await fetch(base+'/vh2/projection?worldId='+world)).json();assert(latest.state.truth.companion.lifeProfile.socialCircle.some(p=>p.name==='Sam Rivera'));assert(latest.state.truth.companion.lifeProfile.weeklySchedule.some(p=>p.activity==='Morning shift'));assert(latest.state.truth.companion.lifeProfile.activityOptions.some(p=>p.label==='Practice guitar'));assert(latest.state.truth.companion.lifeProfile.places.some(p=>p.id==='retry_test'));
await page.evaluate(()=>vhOpenWorkspace('connections'));await page.screenshot({path:out+'/providers.png'});await page.getByRole('button',{name:'Configure background images',exact:true}).click();await page.getByRole('dialog',{name:'Background photos',exact:true}).waitFor();await page.getByRole('dialog',{name:'Background photos',exact:true}).getByRole('button',{name:'Close',exact:true}).click();
await page.route('**/vh2/flight-provider?*',r=>r.fulfill({status:503,contentType:'application/json',body:JSON.stringify({error:'Fixture flight outage'})}));await page.evaluate(async()=>{await vhUiCommand(getActiveCompanionTimeline('ux-alex'),'upsert_place',{place:{id:'outage_place',label:'Place during flight outage',kind:'other'}});vhOpenWorkspace('places');});await page.getByRole('heading',{name:'Place during flight outage',exact:true}).waitFor();assert(await page.evaluate(()=>getActiveCompanionTimeline('ux-alex').vh2.optionalProviderErrors.some(e=>e.capability==='Flights')));await page.unroute('**/vh2/flight-provider?*');
await page.setViewportSize({width:390,height:844});await page.evaluate(()=>vhOpenWorkspace('closet'));await page.getByRole('tab',{name:/Outfit presets/}).click();await page.screenshot({path:out+'/wardrobe-mobile.png'});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
await page.reload();await page.waitForFunction(()=>typeof vhOpenWorkspace==='function'&&state.companions.some(c=>c.id==='ux-alex'));await page.evaluate(()=>{state.activeCompanionId='ux-alex';vhOpenWorkspace('closet');});await page.waitForFunction(()=>!!getActiveCompanionTimeline('ux-alex').vh2.legacyPresets?.some(p=>p.label==='Favourite café look'));assert.deepEqual(errors,[]);fs.writeFileSync(out+'/results.json',JSON.stringify({passed:true,peopleSaved:true,commitmentsSaved:true,activitiesSaved:true,rejectedQueueCleared:true,revisionRetryPassed:true,optionalProviderIsolation:true,presetSaved:true,saveAgainWithoutDuplicate:true,garmentEditAndArchive:true,roomRename:true,styleSaved:true,placeSaved:true,reloadPersists:true,mobileNoOverflow:true,pageErrors:errors},null,2));console.log('PASS master flows: people, routine, providers, wardrobe, places, terminal rejection, revision retry, mobile and reload');
}finally{if(browser)await browser.close();server.kill();}})().catch(e=>{console.error(e);process.exitCode=1;});
