'use strict';
const {spawn}=require('node:child_process'),assert=require('node:assert/strict'),fs=require('node:fs');
const {chromium,launchOptions}=require('./browser_runtime').browserRuntime();
(async()=>{const server=spawn(process.env.HORDE_PYTHON_EXECUTABLE||'python3',['scratch/vh2_browser_server.py'],{stdio:['ignore','pipe','pipe']});let browser;
try{
 const port=await new Promise((resolve,reject)=>{server.stdout.once('data',d=>resolve(+String(d).trim()));server.stderr.on('data',d=>process.stderr.write(d));server.once('exit',c=>reject(Error('server '+c)));});const base=`http://127.0.0.1:${port}`;
 browser=await chromium.launch(launchOptions);const page=await browser.newPage({viewport:{width:1440,height:1000}}),errors=[],calls=[];let failOccupation=true,delay=false;
 page.on('pageerror',e=>errors.push(e.message));
 await page.route('**/*',async r=>{const url=r.request().url();if(url===base+'/test/chat/completions'){
  const body=r.request().postDataJSON(),data=JSON.parse(body.messages[1].content);if(data.field)calls.push({body,data});
  if(delay)await new Promise(resolve=>setTimeout(resolve,1200));
  if(data.field==='occupation'&&failOccupation){failOccupation=false;return r.fulfill({status:503,body:'fixture failure'});}
  return r.fulfill({status:200,contentType:'application/json',body:JSON.stringify({choices:[{finish_reason:'stop',message:{content:'Reviewed '+data.field+' fixture'}}]})});
 }return url.startsWith(base)?r.continue():r.abort();});
 await page.goto(base+'/index.html');await page.addStyleTag({content:'*,*::before,*::after{animation:none!important;transition:none!important;scroll-behavior:auto!important}'});await page.waitForFunction(()=>typeof companionAgencyTimer!=='undefined'&&!!companionAgencyTimer);
 await page.evaluate(base=>{clearInterval(companionAgencyTimer);clearInterval(companionAlwaysOnTimer);mcpBridgeBase=()=>base;state.globalSettings.localBaseUrl=base+'/test';state.globalSettings.localApiKey='LOCAL_TEST_KEY';state.globalSettings.apiProvider='local';state.globalSettings.defaultModel='browser-fixture';
 const c=normalizeCompanion({id:'page-draft-fixture',name:'Alex',age:28,personality:'An isolated fantasy archivist.',backstory:'Preserve this authored history.',appearance:'',occupation:'',textProvider:'local',model:'browser-fixture'});state.companions=[c];state.activeCompanionId=c.id;state.companionTimelines={};state.companionThreads={};ensureCompanionTimelineStore(c.id);hideGlobalSettings();openCompanionStudio(c.id);switchView('companionStudio');},base);
 for(const tab of ['identity','mind','chat-style','social','voice','video'])assert.equal(await page.locator(`[data-vh-page-builder="cs-${tab}"]`).count(),1,tab+' CTA mounted');
 await page.evaluate(()=>vhOpenPageBuilder('cs-identity'));let dialog=page.getByRole('dialog',{name:'Draft identity',exact:true});await dialog.waitFor();assert.equal(await dialog.locator('section textarea:visible').count(),0,'Undrafted review editors stay hidden');assert.equal(await dialog.getByRole('button',{name:'Retry this field'}).count(),0,'Retry appears only after an attempt');assert.equal(calls.length,0,'Opening builder cannot spend credits');
 const row=label=>dialog.locator('section').filter({has:page.getByText(new RegExp('^(Draft|Replace) '+label+'$'))});
 for(const check of await dialog.locator('section > label:first-child input').all())await check.uncheck();
 await row('Appearance').locator('input').first().check();await row('Occupation').locator('input').first().check();
 await dialog.getByRole('button',{name:/Draft 2 selected fields/,exact:true}).click();await row('Occupation').getByText(/HTTP 503/).waitFor();
 assert.equal(await row('Appearance').locator('textarea').inputValue(),'Reviewed appearance fixture');
 await row('Occupation').getByRole('button',{name:'Retry this field'}).click();await row('Occupation').getByText('Ready to review.',{exact:true}).waitFor();
 assert.equal(await row('Appearance').locator('textarea').inputValue(),'Reviewed appearance fixture','Retry retains successful field');
 assert.deepEqual(calls.map(c=>c.data.field),['appearance','occupation','occupation']);assert.equal(calls[1].data.provisionalDrafts.appearance,'Reviewed appearance fixture');assert(calls.every(c=>c.body.messages.length===2&&!c.body.tools&&!JSON.stringify(c.data).includes('LOCAL_TEST_KEY')));
 await row('Occupation').locator('input').nth(1).uncheck();await dialog.getByRole('button',{name:'Apply selected drafts to editor'}).click();await dialog.getByText(/1 reviewed field copied/).waitFor();
 await dialog.getByRole('button',{name:'Close',exact:true}).click();
 assert.equal(await page.locator('#cs-appearance').inputValue(),'Reviewed appearance fixture');assert.equal(await page.locator('#cs-occupation').inputValue(),'');
 assert.equal(await page.locator('#cs-backstory').inputValue(),'Preserve this authored history.');
 await page.locator('#save-companion-btn').click();await page.waitForFunction(()=>document.getElementById('vh-save-status').textContent.startsWith('Saved'));
 await page.reload();await page.addStyleTag({content:'*,*::before,*::after{animation:none!important;transition:none!important;scroll-behavior:auto!important}'});await page.waitForFunction(()=>typeof companionAgencyTimer!=='undefined'&&!!companionAgencyTimer);
 await page.evaluate(()=>{clearInterval(companionAgencyTimer);clearInterval(companionAlwaysOnTimer);openCompanionStudio('page-draft-fixture');switchView('companionStudio');});
 assert.equal(await page.locator('#cs-appearance').inputValue(),'Reviewed appearance fixture');assert.equal(await page.locator('#cs-occupation').inputValue(),'');assert.equal(await page.locator('#cs-backstory').inputValue(),'Preserve this authored history.');
 await page.evaluate(()=>vhOpenPageBuilder('cs-identity'));dialog=page.getByRole('dialog',{name:'Draft identity',exact:true});
 for(const check of await dialog.locator('section > label:first-child input').all())await check.uncheck();await row('Appearance').locator('input').first().check();
 await dialog.getByRole('button',{name:/Draft 1 selected field/,exact:true}).click();await row('Appearance').getByText('Ready to review.',{exact:true}).waitFor();
 await page.evaluate(()=>{getCompanion('page-draft-fixture').appearance='User edit preserved';document.getElementById('cs-appearance').value='User edit preserved';});
 await dialog.getByRole('button',{name:'Apply selected drafts to editor'}).click();await dialog.getByText(/Character fields changed while/).waitFor();assert.equal(await page.locator('#cs-appearance').inputValue(),'User edit preserved');await dialog.getByRole('button',{name:'Close',exact:true}).click();
 await page.evaluate(()=>vhOpenPageBuilder('cs-identity'));dialog=page.getByRole('dialog',{name:'Draft identity',exact:true});
 for(const check of await dialog.locator('section > label:first-child input').all())await check.uncheck();await row('Occupation').locator('input').first().check();delay=true;
 await dialog.getByRole('button',{name:/Draft 1 selected field/,exact:true}).click();await row('Occupation').getByText('Drafting…',{exact:true}).waitFor();await dialog.getByRole('button',{name:'Stop generating'}).click();await dialog.getByText('Stopped. Finished drafts are kept for review.',{exact:true}).waitFor();assert.equal(await page.locator('#cs-occupation').inputValue(),'');
 await page.setViewportSize({width:390,height:844});const overflow=await dialog.evaluate(d=>({width:d.getBoundingClientRect().width,scroll:d.scrollWidth,client:d.clientWidth,body:document.documentElement.scrollWidth,viewport:innerWidth}));assert(overflow.width<=390&&overflow.scroll<=overflow.client+1&&overflow.body<=390,'Mobile overflow '+JSON.stringify(overflow));
 const out='docs/vh2/page-builder-20260920';fs.mkdirSync(out,{recursive:true});await page.screenshot({path:out+'/mobile-identity-draft.png',fullPage:true});
 await dialog.getByRole('button',{name:'Close',exact:true}).click();await page.setViewportSize({width:1440,height:1000});await page.evaluate(()=>activateCompanionStudioTab('cs-identity'));await page.locator('#tab-cs-identity').waitFor({state:'visible'});await page.screenshot({path:out+'/desktop-identity.png',fullPage:true});
 const fieldGeometry=await page.evaluate(()=>{const age=document.getElementById('cs-age').getBoundingClientRect(),pronouns=document.getElementById('cs-pronouns').getBoundingClientRect(),ai=document.querySelector('[data-vh-field-builder=pronouns]').getBoundingClientRect();return {age:[age.y,age.width],pronouns:[pronouns.y,pronouns.width],aiHeight:ai.height,appearanceLimit:document.getElementById('cs-appearance-limit').textContent};});
 assert(Math.abs(fieldGeometry.age[0]-fieldGeometry.pronouns[0])<1&&Math.abs(fieldGeometry.age[1]-fieldGeometry.pronouns[1])<1,'Age and pronouns share a stable grid');assert(fieldGeometry.aiHeight>=44,'Field AI action keeps an accessible touch target');assert.equal(fieldGeometry.appearanceLimit.includes('characters'),false,'Field counters stay visually quiet');
 assert.equal(await page.locator('[data-field-guide]').count(),0,'No detached field guide remains');assert.equal(await page.locator('#tab-cs-identity [data-vh-field-help]').count(),9,'Identity help is attached to each relevant field, including age');assert.equal(await page.locator('#tab-cs-identity .vh-field-heading>.form-label[data-help]').count(),0,'The global help system cannot add a duplicate field icon');const appearanceHelp=page.locator('[data-vh-field-help=appearance]');await appearanceHelp.focus();await page.locator('#horde-context-tooltip.visible').waitFor();assert.match(await page.locator('#horde-context-tooltip').innerText(),/Physical identity used in visual descriptions/);assert.match(await page.locator('#cs-appearance').getAttribute('aria-describedby'),/cs-appearance-help/);await page.keyboard.press('Escape');assert.equal(await page.locator('#horde-context-tooltip').isVisible(),false,'Tooltip closes with Escape');
 const studioTabs=['cs-overview','cs-identity','cs-mind','cs-chat-style','cs-life','cs-social','cs-voice','cs-video','cs-models'];const nativeControls=[];for(const tab of studioTabs){await page.evaluate(tab=>activateCompanionStudioTab(tab),tab);nativeControls.push(...await page.evaluate(tab=>[...document.querySelectorAll('#companion-studio-view button')].filter(button=>{const style=getComputedStyle(button),box=button.getBoundingClientRect();return box.width>0&&box.height>0&&style.visibility!=='hidden'&&style.display!=='none'&&style.color==='rgb(0, 0, 0)'&&['rgb(239, 239, 239)','rgb(240, 240, 240)'].includes(style.backgroundColor);}).map(button=>tab+': '+button.textContent.trim()),tab));}
 assert.deepEqual(nativeControls,[],'No visible Studio action may fall back to a native white browser button');
 await page.evaluate(()=>activateCompanionStudioTab('cs-life'));const lifeActions=await page.locator('.vh-studio-action-card').evaluate(card=>{const copy=card.querySelector('.vh-studio-action-copy').getBoundingClientRect(),cardBox=card.getBoundingClientRect(),buttons=[...card.querySelectorAll('button')].map(button=>({text:button.textContent.trim(),width:button.getBoundingClientRect().width,background:getComputedStyle(button).backgroundColor,color:getComputedStyle(button).color}));return {copyWidth:copy.width,cardWidth:cardBox.width,buttons};});assert(lifeActions.copyWidth>lifeActions.cardWidth*.7,'Supporting-cast copy stays readable');assert.deepEqual(lifeActions.buttons.map(button=>button.text),['Manage people manually','Draft routines with AI']);assert(lifeActions.buttons.every(button=>button.width<260&&button.color!=='rgb(0, 0, 0)'),'Supporting-cast actions use compact product controls');
 delay=false;await page.evaluate(()=>{activateCompanionStudioTab('cs-chat-style');vhOpenPageBuilder('cs-chat-style');});dialog=page.getByRole('dialog',{name:'Draft chat style',exact:true});for(const check of await dialog.locator('section > label:first-child input').all())await check.uncheck();await row('Writing voice').locator('input').first().check();await dialog.getByRole('button',{name:/Draft 1 selected field/,exact:true}).click();await row('Writing voice').getByText('Ready to review.',{exact:true}).waitFor();await page.screenshot({path:out+'/desktop-writing-draft.png',fullPage:true});await dialog.getByRole('button',{name:'Close',exact:true}).click();
 await page.evaluate(()=>vhOpenWorkspace('connections','page-draft-fixture'));await page.locator('.vh-life-onboarding').waitFor({state:'visible'});assert.equal(await page.locator('#vh-workspace-title').innerText(),'Start a persistent life');assert.equal(await page.locator('#vh-workspace-nav').isVisible(),false,'A draft cannot enter unavailable live settings');assert.equal(await page.locator('[data-open-blueprint]').innerText(),'Review starting world');
 assert.deepEqual(errors,[]);fs.writeFileSync(out+'/browser-results.json',JSON.stringify({passed:true,checks:['six mounted page actions','identity entry without whole-character call','per-field selected requests','failure and isolated retry','selected review only','saved reload preserves text','filled field unchanged','stale edit blocked','cancellation','mobile no overflow'],requests:calls.map(c=>c.data.field),overflow},null,2));console.log('PASS integrated page builder browser acceptance.');
}finally{if(browser)await browser.close();server.kill();}
})().catch(e=>{console.error(e);process.exitCode=1;});
