'use strict';
const assert=require('node:assert/strict');
const {fixture,advance}=require('./vh_goal_outing_audit');
const core=require('../vh-simulation-core');
const engine=global.VHWorldEngine,minute=60000;
const c=advance(fixture(),3),j=c.lifeRuntime.world.journey,t=j.departedAt;
const geometry=[[0,51],[0,51.01],[.01,51.01]];
assert.equal(engine.position(c,t+minute).source,'duration_only');
assert.equal(engine.position(c,t+minute).coordinates,null,'no invented straight-line street route');
assert(engine.applyRoute(c,j.id,{provider:'openrouteservice',routes:[{duration:'600s',geometry}]},t));
assert.equal(engine.position(c,t+5*minute).segmentIndex,0,'distance-weighted progress, not vertex count');
const before=engine.position(c,t+4*minute);
engine.interrupt(c,t+4*minute,3);
assert.deepEqual(engine.position(c,t+6*minute).coordinates,before.coordinates,'pause freezes physical position');
assert.equal(engine.position(c,t+6*minute).progress,before.progress);
engine.interrupt(c,t+5*minute,2);
assert.equal(engine.position(c,t+8*minute).progress,before.progress,'repeated pauses extend without rewind');
assert(engine.position(c,t+10*minute).progress>before.progress);
const reloaded=JSON.parse(JSON.stringify(c));reloaded.lifeRuntime=core.normalizeCompanionLifeRuntime(reloaded.lifeRuntime);
assert.deepEqual(engine.position(reloaded,t+10*minute),engine.position(c,t+10*minute),'reload keeps route, pauses and progress');
const snapshot=JSON.stringify(c);engine.position(c,t+11*minute);assert.equal(JSON.stringify(c),snapshot,'projection is read-only');
assert.equal(engine.position(c,j.arrivesAt).progress,1);
assert.throws(()=>engine.interrupt(c,j.arrivesAt,2),/arrival time/);
assert.deepEqual(engine.routeGeometry('_p~iF~ps|U_ulLnnqC_mqNvxq`@'),[[-120.2,38.5],[-120.95,40.7],[-126.453,43.252]]);
for(const invalid of ['?', '_', 'x'.repeat(200001),[[0,0],[999,0]],[[0,0],[NaN,1]],[[0,0]]])assert.equal(engine.routeGeometry(invalid),null);
const durationOnly=advance(fixture(),3),dj=durationOnly.lifeRuntime.world.journey;
assert(engine.applyRoute(durationOnly,dj.id,{routes:[{duration:'600s',geometry:'broken'}]},dj.departedAt));
assert.equal(engine.position(durationOnly,dj.departedAt+minute).source,'duration_only');
assert(!engine.applyRoute(durationOnly,dj.id,{routes:[{duration:'100s'}]},dj.arrivesAt),'late response cannot revive a journey');
const dateline=JSON.parse(JSON.stringify(c));dateline.lifeRuntime.world.journey={...j,departedAt:0,arrivesAt:1000,motion:null,pausedUntil:0,geometry:[[179,0],[-179,0]]};
assert.equal(Math.abs(engine.position(dateline,500).coordinates[0]),180,'take short segment across date line');
const arrived=advance(c,60);assert.equal(engine.position(arrived,arrived.lifeRuntime.lastSimulatedAt).status,'at_place');
assert.equal(engine.position(arrived,arrived.lifeRuntime.lastSimulatedAt).placeId,arrived.lifeRuntime.world.placeId);
console.log('PASS route arclength progress, pauses, reload, read-only projection, encoded geometry, invalid geometry fallback and arrival');
