'use strict';
const {spawn}=require('node:child_process'),assert=require('node:assert/strict'),fs=require('node:fs');
const {chromium,launchOptions}=require('./browser_runtime').browserRuntime();
(async()=>{const server=spawn('python3',['scratch/vh2_browser_server.py'],{stdio:['ignore','pipe','pipe']});let browser;
try{
 const port=await new Promise((resolve,reject)=>{server.stdout.once('data',d=>resolve(+String(d).trim()));server.stderr.on('data',d=>process.stderr.write(d));server.once('exit',c=>reject(Error('server '+c)));}),base=`http://127.0.0.1:${port}`;
 browser=await chromium.launch(launchOptions);const page=await browser.newPage({viewport:{width:1440,height:1000}}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.route('**/*',r=>r.request().url().startsWith(base)||r.request().url().startsWith('blob:')?r.continue():r.abort());await page.goto(base+'/index.html');await page.waitForFunction(()=>typeof companionAgencyTimer!=='undefined'&&!!companionAgencyTimer);
 await page.evaluate(base=>{clearInterval(companionAgencyTimer);clearInterval(companionAlwaysOnTimer);mcpBridgeBase=()=>base;Object.assign(state.globalSettings,{localBaseUrl:base+'/test',localApiKey:'LOCAL_TEST_KEY',apiProvider:'local',defaultModel:'browser-fixture'});const c=normalizeCompanion({id:'save-alex',name:'Alex Morgan',age:28,personality:'Curious',textProvider:'local',model:'browser-fixture',lifeProfile:{initializedAt:Date.now(),places:[{id:'home',label:'Personal apartment',kind:'home',detail:'Green sofa and oak shelves.'}],wardrobe:[{id:'original',label:'Original outfit',items:'Red linen shirt and dark trousers',context:'home'}],socialCircle:[{id:'sam',name:'Sam',role:'friend',description:'Original friend',contactWindows:[{days:[1],startMinute:1000,endMinute:1100}]}],weeklySchedule:[]}});state.companions=[c];state.activeCompanionId=c.id;state.companionTimelines={};state.companionThreads={};ensureCompanionTimelineStore(c.id);hideGlobalSettings();openCompanionStudio(c.id);switchView('companionStudio');},base);
 await page.locator('[data-tab="cs-life"]').click();await page.locator('[data-destination="closet"]').click();
 const wardrobe=page.getByRole('dialog',{name:'Starting wardrobe',exact:true});await wardrobe.getByRole('button',{name:'Add outfit preset',exact:true}).click();
 let d=page.getByRole('dialog',{name:'Add outfit preset',exact:true});await d.locator('[name=label]').fill('New saved outfit');await d.locator('[name=items]').fill('Blue linen shirt and cream trousers');await d.getByRole('button',{name:'Save preset',exact:true}).click();await d.getByRole('button',{name:'Saved',exact:true}).waitFor();
 await d.locator('[name=context]').selectOption('social');await d.getByRole('button',{name:'Save changes',exact:true}).click();await d.getByRole('button',{name:'Saved',exact:true}).waitFor();await d.getByRole('button',{name:'Close',exact:true}).click();
 await wardrobe.getByRole('heading',{name:'New saved outfit',exact:true}).waitFor();assert.equal(await wardrobe.getByRole('heading',{name:'Original outfit',exact:true}).count(),1);
 await wardrobe.getByRole('button',{name:'Create a style',exact:true}).click();d=page.getByRole('dialog',{name:'Create a style preference',exact:true});await d.locator('[name=name]').fill('Blue linen style');await d.locator('[name=top]').fill('Blue linen shirt');await d.locator('[name=bottom]').fill('Cream trousers');await d.getByRole('button',{name:'Save style preference',exact:true}).click();await d.getByRole('button',{name:'Saved',exact:true}).waitFor();await d.getByRole('button',{name:'Close',exact:true}).click();await wardrobe.getByRole('heading',{name:'Blue linen style',exact:true}).waitFor();await wardrobe.getByRole('button',{name:'Close',exact:true}).click();
 const before=await page.evaluate(()=>JSON.stringify(getCompanion('save-alex').lifeProfile));
 await page.locator('[data-destination="people"]').click();const people=page.getByRole('dialog',{name:'Starting people',exact:true});await people.getByRole('heading',{name:'Sam',exact:true}).waitFor();assert.equal(await page.evaluate(()=>JSON.stringify(getCompanion('save-alex').lifeProfile)),before,'opening People must not rebuild the life');
 await people.getByRole('button',{name:'Edit',exact:true}).click();d=page.getByRole('dialog',{name:'Edit person',exact:true});await d.locator('[name=description]').fill('Updated friend background');await d.getByRole('button',{name:'Save person',exact:true}).click();await page.waitForFunction(()=>!document.querySelector('dialog[aria-label="Edit person"]'));await people.getByText('Updated friend background',{exact:true}).waitFor();assert.equal(await page.evaluate(()=>getCompanion('save-alex').lifeProfile.socialCircle[0].contactWindows.length),1);await people.getByRole('button',{name:'Close',exact:true}).click();
 await page.locator('[data-destination="life"]').click();const routine=page.getByRole('dialog',{name:'Starting routine',exact:true});await routine.getByRole('button',{name:'Add commitment',exact:true}).click();d=page.getByRole('dialog',{name:'Add commitment',exact:true});await d.locator('[name=label]').fill('Design workshop');await d.getByRole('button',{name:'Save commitment',exact:true}).click();await routine.getByRole('heading',{name:'Design workshop',exact:true}).waitFor();await routine.getByRole('button',{name:'Close',exact:true}).click();
 // Storage failure must keep the editor usable and leave the committed data intact.
 await page.evaluate(()=>{window.realSetMultiple=HordeDB.setMultiple;HordeDB.setMultiple=async()=>{throw new Error('Injected storage failure');};vhOutfitEditor(getCompanion('save-alex'),getCompanion('save-alex').lifeProfile.wardrobe[0]);});
 d=page.getByRole('dialog',{name:'Edit outfit preset',exact:true});await d.locator('[name=label]').fill('Must not be saved');await d.getByRole('button',{name:'Save preset',exact:true}).click();await d.getByText('Injected storage failure',{exact:true}).waitFor();assert.equal(await page.evaluate(()=>getCompanion('save-alex').lifeProfile.wardrobe[0].label),'Original outfit');await page.evaluate(()=>{HordeDB.setMultiple=window.realSetMultiple;});await d.getByRole('button',{name:'Close',exact:true}).click();
 await page.reload();await page.waitForFunction(()=>typeof state!=='undefined'&&state.companions.some(c=>c.id==='save-alex'));
 const restored=await page.evaluate(()=>{clearInterval(companionAgencyTimer);clearInterval(companionAlwaysOnTimer);const c=getCompanion('save-alex');return {wardrobe:c.lifeProfile.wardrobe,styles:c.lifeStyleProfiles,people:c.lifeProfile.socialCircle,schedule:c.lifeProfile.weeklySchedule,places:c.lifeProfile.places};});
 assert.equal(restored.wardrobe.length,2);assert.equal(restored.wardrobe.find(x=>x.label==='New saved outfit').context,'social');assert.equal(restored.styles[0].name,'Blue linen style');assert.equal(restored.people[0].description,'Updated friend background');assert.equal(restored.schedule[0].activity,'Design workshop');assert.equal(restored.places[0].label,'Personal apartment');
 const merged=await page.evaluate(async()=>{const c=getCompanion('save-alex');await vhSaveBlueprintProposal(c,{wardrobe:[{id:'original',label:'Reviewed original',items:'Red linen shirt and dark trousers',context:'home'}]});return c.lifeProfile.wardrobe;});assert.equal(merged.length,2);assert(merged.some(x=>x.label==='New saved outfit'));
 // Live save waits for an older poll, then refreshes the acknowledged result.
 await page.evaluate(base=>{mcpBridgeBase=()=>base;state.activeCompanionId='save-alex';},base);await page.evaluate(()=>vh2CreateTimeline(getCompanion('save-alex')));await page.waitForFunction(()=>!!getActiveCompanionTimeline('save-alex')?.vh2?.worldId);
 const failedQueue=await page.evaluate(async()=>{const original=HordeDB.setMultiple,t=getActiveCompanionTimeline('save-alex'),before=t.vh2.outbox.length;HordeDB.setMultiple=async()=>{throw Error('Injected enqueue failure');};try{await vh2Enqueue(t,'apply_life_proposal',{version:2,proposal:{wardrobe:[]}});return {unexpected:true};}catch(error){return {before,after:t.vh2.outbox.length,message:error.message};}finally{HordeDB.setMultiple=original;}});assert.equal(failedQueue.after,failedQueue.before);assert.equal(failedQueue.message,'Injected enqueue failure');
 let release,stalledResolve;const stalled=new Promise(r=>stalledResolve=r),gate=new Promise(r=>release=r);let hold=true;
 await page.route('**/vh2/provider-jobs?*',async route=>{if(hold){hold=false;stalledResolve();await gate;}await route.continue();});await page.evaluate(()=>{window.oldPoll=vh2Poll(getCompanion('save-alex'));});await stalled;
 await page.evaluate(()=>{window.liveSaveDone=false;window.liveSave=vhSaveAuthorSection(getCompanion('save-alex'),'wardrobe',[{id:'live_saved',label:'Saved during poll',context:'home',items:'Green cotton tee and charcoal shorts'}]).then(()=>window.liveSaveDone=true);});
 assert.equal(await page.evaluate(()=>window.liveSaveDone),false);release();await page.evaluate(()=>window.liveSave);assert(await page.evaluate(()=>getActiveCompanionTimeline('save-alex').vh2.legacyPresets.some(x=>x.id==='live_saved')));await page.unroute('**/vh2/provider-jobs?*');
 await page.evaluate(()=>{const c=getCompanion('save-alex');vhReviewChatStyle(c,getActiveCompanionTimeline(c.id),vhValidateChatStyle({textingStyle:'Short warm messages.',conversationStyle:'Plain words.',chatExamples:'Player: Hi\nCharacter: Hey, good to hear from you.',chatAvoid:'No stock catchphrases.',chatLength:'brief'},c));});
 d=page.getByRole('dialog',{name:'Review chat style',exact:true});await d.getByRole('button',{name:'Apply selected style',exact:true}).click();await d.getByRole('button',{name:'Applied',exact:true}).waitFor();await d.locator('[data-style="textingStyle"]').fill('Brief and direct messages.');await d.getByRole('button',{name:'Apply selected style',exact:true}).click();await d.getByRole('button',{name:'Applied',exact:true}).waitFor();assert.equal(await page.evaluate(()=>getCompanion('save-alex').textingStyle),'Brief and direct messages.');await d.getByRole('button',{name:'Close',exact:true}).click();
 // An editor opened for a previous timeline cannot save into a different life.
 await page.evaluate(()=>{vhOutfitEditor(getCompanion('save-alex'));const store=ensureCompanionTimelineStore('save-alex'),t=safeJsonClone(getActiveCompanionTimeline('save-alex'));t.id='other-fixture-timeline';store.sessions.unshift(t);store.activeSessionId=t.id;});
 d=page.getByRole('dialog',{name:'Add outfit preset',exact:true});await d.locator('[name=label]').fill('Wrong timeline');await d.locator('[name=items]').fill('Must never save here');await d.getByRole('button',{name:'Save preset',exact:true}).click();await d.getByText('The selected life changed. Close this editor and reopen it for the intended life.',{exact:true}).waitFor();
 await d.getByRole('button',{name:'Close',exact:true}).click();
 // Reopening and saving the complete author form must not erase chat style.
 await page.evaluate(async()=>{const c=getCompanion('save-alex');c.appearance='Detailed appearance '.repeat(180);await saveState();openCompanionStudio(c.id);switchView('companionStudio');});
 await page.locator('[data-tab="cs-identity"]').click();await page.locator('[data-tab="cs-chat-style"]').click();await page.locator('#save-companion-btn').click();await page.waitForFunction(()=>/Saved/.test(document.getElementById('vh-save-status')?.textContent||''));
 await page.reload();await page.waitForFunction(()=>typeof state!=='undefined'&&state.companions.some(c=>c.id==='save-alex'));
 const style=await page.evaluate(()=>{clearInterval(companionAgencyTimer);clearInterval(companionAlwaysOnTimer);const c=getCompanion('save-alex');return {textingStyle:c.textingStyle,chatExamples:c.chatExamples,appearance:c.appearance};});
 assert.equal(style.textingStyle,'Brief and direct messages.');assert.match(style.chatExamples,/good to hear from you/);assert(style.appearance.length>800);
 await page.evaluate(()=>{hideGlobalSettings();exportCompanionArchive('save-alex');});
	 let download;
	 try{
	  [download]=await Promise.all([page.waitForEvent('download',{timeout:45000}),page.locator('#export-companion-json-btn').click()]);
	 }catch(error){
	  const diagnostic=await page.evaluate(()=>({progress:document.getElementById('companion-export-progress')?.textContent,progressHidden:document.getElementById('companion-export-progress')?.classList.contains('hidden'),buttonDisabled:document.getElementById('export-companion-json-btn')?.disabled,target:companionExportTargetId,pollLocks:[...vh2PollLocks.keys()],flushLocks:[...vh2FlushLocks.keys()],activeTimeline:getActiveCompanionTimeline('save-alex')?.id,issues:[...vhRecentIssues],toasts:[...document.querySelectorAll('.toast')].map(node=>node.textContent)}));
	  console.error('Export timeout diagnostic',diagnostic);throw error;
	 }
 assert.match(download.suggestedFilename(),/\.json$/);const raw=JSON.parse(fs.readFileSync(await download.path(),'utf8'));
 assert.equal(raw._kind,'character-template');assert.equal(raw.companion.textingStyle,style.textingStyle);assert.equal(raw.companion.appearance,style.appearance);
 raw.companion.name='Edited JSON copy';raw.companion.textingStyle='Manually edited without a checksum.';
 await page.locator('#import-companion-input').setInputFiles({name:'edited-character.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(raw,null,2))});
 await page.waitForFunction(()=>state.companions.some(c=>c.name==='Edited JSON copy'));
 const imported=await page.evaluate(()=>{const c=state.companions.find(c=>c.name==='Edited JSON copy');return {id:c.id,textingStyle:c.textingStyle,appearance:c.appearance};});
 assert.notEqual(imported.id,'save-alex');assert.equal(imported.textingStyle,raw.companion.textingStyle);assert.equal(imported.appearance,style.appearance);
 assert.deepEqual(errors,[]);console.log('PASS: blueprint outfit/style/person/routine saves, refreshed lists, repeat save, preserved metadata, no navigation reset, quota failure, reload persistence, concurrent live poll, timeline isolation, chat-style reload, long appearance, editable JSON UI export/manual edit/import');
}finally{if(browser)await browser.close();server.kill();}})().catch(e=>{console.error(e);process.exitCode=1;});
