'use strict';
const {spawn}=require('node:child_process'),assert=require('node:assert/strict'),fs=require('node:fs');
const { chromium, launchOptions } = require('./browser_runtime').browserRuntime();
(async()=>{const server=spawn('python3',['scratch/vh2_browser_server.py'],{stdio:['ignore','pipe','pipe']});let browser;
try{const port=await new Promise((resolve,reject)=>{server.stdout.once('data',d=>resolve(+String(d).trim()));server.stderr.on('data',d=>process.stderr.write(d));server.once('exit',c=>reject(Error('server '+c)));});const base=`http://127.0.0.1:${port}`;
browser=await chromium.launch(launchOptions);const page=await browser.newPage({viewport:{width:1440,height:1000}});const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.route('**/*',r=>r.request().url().startsWith(base)?r.continue():r.abort());await page.goto(base+'/index.html');await page.addStyleTag({content:'*,*::before,*::after{animation:none!important;transition:none!important;scroll-behavior:auto!important}'});await page.waitForFunction(()=>typeof companionAgencyTimer!=='undefined'&&!!companionAgencyTimer);
await page.evaluate(base=>{clearInterval(companionAgencyTimer);clearInterval(companionAlwaysOnTimer);mcpBridgeBase=()=>base;state.globalSettings.localBaseUrl=base+'/test';state.globalSettings.localApiKey='LOCAL_TEST_KEY';state.globalSettings.apiProvider='local';state.globalSettings.defaultModel='browser-fixture';const c=normalizeCompanion({id:'ux-alex',name:'Alex Morgan',age:28,personality:'Reserved and curious',textProvider:'local',model:'browser-fixture',lifeProfile:{world:{gifts:{enabled:true,mailAllowed:true,cashAllowed:true,minTrust:-100}},places:[{id:'home',label:'Apartment',kind:'home'},{id:'cafe',label:'Corner Cafe',kind:'social'}],weeklySchedule:[],sleepPolicy:{enabled:false}}});state.companions=[c];state.activeCompanionId=c.id;state.companionTimelines={};state.companionThreads={};ensureCompanionTimelineStore(c.id);hideGlobalSettings();switchView('companionChat');renderCompanionThread();},base);
await page.evaluate(()=>vh2CreateTimeline(getCompanion('ux-alex')));await page.waitForFunction(()=>!!getActiveCompanionTimeline('ux-alex')?.vh2?.worldId);const world=await page.evaluate(()=>getActiveCompanionTimeline('ux-alex').vh2.worldId);
await page.evaluate(()=>{openCompanionStudio('ux-alex');switchView('companionStudio');});await page.locator('[data-tab="cs-chat-style"]').click();await page.locator('#cs-texting-style').fill('Concise and dry. No stock catchphrases.');await page.locator('#save-companion-btn').click();await page.waitForFunction(()=>document.getElementById('vh-save-status').textContent.includes('Expression active'));
let projection=await (await fetch(base+'/vh2/projection?worldId='+world)).json();assert.equal(projection.state.truth.companion.textingStyle,'Concise and dry. No stock catchphrases.');
await page.locator('#vh-save-scope').selectOption('template');await page.locator('#cs-texting-style').fill('Template-only change');await page.locator('#save-companion-btn').click();await page.waitForFunction(()=>document.getElementById('vh-save-status').textContent.startsWith('Saved to character template'));
projection=await (await fetch(base+'/vh2/projection?worldId='+world)).json();assert.equal(projection.state.truth.companion.textingStyle,'Concise and dry. No stock catchphrases.');
// A transport failure must retain the draft and never claim the active life saved.
await page.locator('#vh-save-scope').selectOption('active');await page.route('**/vh2/command',r=>r.abort());await page.locator('#cs-texting-style').fill('Retain this unsent edit');await page.locator('#save-companion-btn').click();await page.waitForFunction(()=>document.getElementById('vh-save-status').hasAttribute('data-error'));assert.equal(await page.locator('#cs-texting-style').inputValue(),'Retain this unsent edit');await page.unroute('**/vh2/command');await page.locator('#save-companion-btn').click();await page.waitForFunction(()=>document.getElementById('vh-save-status').textContent.includes('Expression active'));


await page.evaluate(()=>vhOpenWorkspace('inspector'));
await page.evaluate(()=>vhOpenPanel('Experience and memory'));
await page.locator('[data-experience-policy=learningRate]').fill('0.42');
await page.locator('#vh-workspace-title').click();
await page.evaluate(()=>{vhRenderWorkspace();vhRenderWorkspace();});
assert.equal(await page.locator('[data-experience-policy=learningRate]').inputValue(),'0.42','refresh preserves blurred draft');
await page.evaluate(()=>{const c=getCompanion('ux-alex');c.imageSource='local';c.imageModel='offline-image';const canvas=document.createElement('canvas');canvas.width=canvas.height=2;c.basePhoto=canvas.toDataURL();window.imageCalls=0;requestCompanionPhoto=async()=>{window.imageCalls++;return canvas.toDataURL();};vhOpenWorkspace('media');vhOpenPanel('Photo capture preview');});
await page.locator('[data-vh2-photo-scene]').fill('A relaxed close-up at home');
await page.getByRole('button',{name:'Review current moment',exact:true}).click();
await page.locator('[data-submit-render]').waitFor();
assert.equal(await page.evaluate(()=>window.imageCalls),0,'review does not generate');
await page.screenshot({path:'/tmp/vh-photo-review.png'});
await page.locator('[data-submit-render]').click();
await page.waitForFunction(()=>document.querySelector('[data-review-status]').textContent.includes('Imported successfully'));
assert.equal(await page.evaluate(()=>window.imageCalls),1,'single reviewed generation');
await page.locator('#vh-photo-review [data-close]').click();
await page.evaluate(()=>vhOpenWorkspace('places'));
await page.locator('#vh-workspace-title').filter({hasText:'Places'}).waitFor();
await page.screenshot({path:'/tmp/vh-workspace-desktop.png'});
await page.evaluate(()=>vhOpenGiftSheet(getCompanion('ux-alex')));
await page.locator('[data-gift-choice="cash"]').click();
await page.locator('[data-send-gift] [name=value]').fill('25');
await page.locator('[data-send-gift] button').click();
await page.waitForFunction(()=>!document.querySelector('[data-send-gift] button').disabled);console.log('Gift result:',await page.locator('[data-gift-feedback]').innerText());assert.match(await page.locator('[data-gift-feedback]').innerText(),/Recorded in this life/);
assert.match(await page.locator('[data-gift-receipts]').innerText(),/25/);
await page.screenshot({path:'/tmp/vh-gifts-desktop.png'});
await page.locator('#cc-gift-close').click();
await page.evaluate(()=>switchView('companionChat'));
await page.setViewportSize({width:390,height:844});
await page.screenshot({path:'/tmp/vh-chat-mobile.png'});
const bounds=await page.locator('.companion-chat-identity').boundingBox();assert.ok(bounds.width>60,'mobile identity remains visible');
await page.evaluate(()=>vhOpenWorkspace('references'));
await page.screenshot({path:'/tmp/vh-references-mobile.png'});
assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+2),false,'no document horizontal overflow');
await page.setViewportSize({width:320,height:720});await page.evaluate(()=>switchView('companionChat'));assert.ok((await page.locator('.companion-chat-identity').boundingBox()).width>50,'320px identity');assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+2),false);await page.evaluate(()=>vhOpenWorkspace('media'));assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+2),false);
await page.locator('#vh-workspace-search').fill('no_such_setting_927');await page.locator('#vh-search-result').filter({hasText:'No matching settings'}).waitFor();await page.locator('#vh-workspace-search').fill('memory');assert.match(await page.locator('#vh-search-result').innerText(),/matching sections/);
await page.evaluate(()=>{openCompanionStudio('ux-alex');switchView('companionStudio');});await page.locator('#vh-studio-section').selectOption('cs-chat-style');await page.locator('#cs-texting-style').waitFor();assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+2),false,'Studio has no horizontal overflow');await page.locator('#cs-texting-style').scrollIntoViewIfNeeded();await page.screenshot({path:'/tmp/vh-studio-polished-mobile.png'});
await page.locator('.vh-studio-more summary').click();await page.locator('#export-companion-btn').waitFor();await page.keyboard.press('Escape');assert.equal(await page.locator('.vh-studio-more').evaluate(e=>e.open),false);
await page.setViewportSize({width:1440,height:1000});await page.evaluate(()=>{vhOpenWorkspace('inspector');vhOpenPanel('Experience and memory');});await page.locator('[data-experience-policy=learningRate]').scrollIntoViewIfNeeded();await page.screenshot({path:'/tmp/vh-editor-polished.png'});assert.equal(await page.locator('.vh-mobile-section').isVisible(),false,'mobile picker hidden on desktop');
assert.deepEqual(errors,[]);console.log('PASS active/template saves, failed-save retry, blurred drafts, photo review/mock import, money receipt, 390px/320px layouts; no page errors.');
}finally{if(browser)await browser.close();server.kill();}})().catch(e=>{console.error(e);process.exitCode=1;});
