const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const {buildContext}=require('./app_source'),worker=require('../vh-host-worker');
const ctx={console,state:{globalSettings:{},personas:[],companions:[],companionTimelines:{},companionThreads:{}}};
buildContext(vm,['normalizeCompanion','advanceCompanionLife','advanceCompanionHumanDynamics','advanceCompanionEmotionState','companionSituationAt','advanceCompanionMessageAttention'],ctx);
const minute=60000,start=Date.UTC(2026,8,7,7),clone=x=>JSON.parse(JSON.stringify(x));
function person(name,policy){return ctx.normalizeCompanion({id:name,name,age:28,locationMode:'custom',timezoneOffsetMinutes:0,sleepArchetype:'normal',libidoEnabled:false,lifeWildcardsEnabled:false,lifeWeatherEnabled:false,lifeProfile:{initializedAt:start,seed:name,decisionPolicy:policy,socialCircle:[{id:'friend',name:'Sam',role:'friend',contactFrequency:'daily',contactWindows:[{days:[0,1,2,3,4,5,6],startMinute:1080,endMinute:1380}]}],activityOptions:[{id:'focus',kind:'focus',label:'Work on a personal project',startMinute:1080,endMinute:1320,priority:45},{id:'friend-chat',kind:'contact',participantId:'friend',label:'Catch up with Sam',startMinute:1080,endMinute:1320,priority:40}],places:[{id:'home',label:'Home',kind:'home'},{id:'work',label:'Work',kind:'work'}],weeklySchedule:[{id:'work',activity:'Work',days:[1,2,3,4,5],startMinute:540,endMinute:1020,placeId:'work',availability:'busy'},{id:'home',activity:'Evening at home',days:[1,2,3,4,5],startMinute:1080,endMinute:1320,placeId:'home',availability:'available'}],travelLegs:[{from:'home',to:'work',mode:'WALK',minutes:25},{from:'work',to:'home',mode:'WALK',minutes:25}],world:{transport:{enabled:true,delayChance:0}},sleepPolicy:{enabled:true}},lifeRuntime:{lastSimulatedAt:start,activities:{lastAdvancedAt:start}},humanDynamics:{energy:80,stress:15,hunger:20,lastUpdated:start},mood:{lastUpdated:start},emotionState:{lastUpdated:start}});}
function run(name,policy,host=false,reload=false){let c=person(name,policy);const trace=[],counts={},seen=new Set(),messages=[],experience={realTimeLife:true,replyDelays:true,allowNoReply:true};let prior='',maxHunger=0,maxDebt=0;for(let n=0;n<=7*1440;n+=5){const now=start+n*minute;
 // Two late conversations and one delayed departure are identical external inputs in every replay.
 if([930,2370,90].includes(n))c.lifeRuntime.activities.conversationUntil=now+90*minute;
 if([60,360,930].includes(n%1440))messages.push({id:`incoming-${n}`,role:'user',type:'text',text:'How is your day going?',timestamp:now,deliveredAt:now,awaitingReply:true});
 if(host){const snapshot=worker.run({companion:c,messages,now,experience});c=snapshot.companion;} else{ctx.advanceCompanionLife(c,now);ctx.advanceCompanionHumanDynamics(c,now);ctx.advanceCompanionEmotionState(c,now);messages.forEach(m=>ctx.advanceCompanionMessageAttention(c,m,now,experience,messages));}
 const ready=messages.filter(m=>m.role==='user'&&m.awaitingReply&&m.replyDueAt>0&&m.replyDueAt<=now);if(ready.length){assert.notEqual(ctx.companionSituationAt(c,now).availability,'asleep','no reply becomes due during sleep');for(const m of ready){trace.push({at:new Date(now).toISOString(),event:'reply_ready',reason:'Offline inbox became eligible; synthetic acknowledgement applied.',latencyMinutes:(now-m.timestamp)/minute});m.awaitingReply=false;m.replyDueAt=0;}messages.push({id:`ack-${n}`,role:'companion',type:'text',text:'[Offline acknowledgement]',timestamp:now});c.continuityRuntime.lastExchangeAt=now;}
 const d=c.humanDynamics,s=d.sleep?.stage||'uninitialized',a=c.lifeRuntime.activities,world=c.lifeRuntime.world;
 counts[s]=(counts[s]||0)+5;maxHunger=Math.max(maxHunger,d.hunger);maxDebt=Math.max(maxDebt,d.sleep?.debtHours||0);
 for(const value of [d.energy,d.hunger,d.stress,d.sleep?.pressure??0])assert(Number.isFinite(value)&&value>=0&&value<=100);
 const key=[s,world.placeId,world.journey?.id||'',a.decision?.goalId].join('|');
 if(key!==prior){trace.push({at:new Date(now).toISOString(),stage:s,place:world.placeId,journey:world.journey?.toLabel||'',energy:Math.round(d.energy),hunger:Math.round(d.hunger),stress:Math.round(d.stress),activity:a.goals.find(g=>g.id===a.decision?.goalId)?.label||'',scores:a.decision?.components||{},reason:a.decision?.reason||''});prior=key;}
 for(const e of [...a.events,...world.events])if(!seen.has(e.id)){seen.add(e.id);trace.push({at:new Date(e.at).toISOString(),event:e.kind,reason:e.summary,lateMinutes:e.lateMinutes||0});}
 if(reload&&n%60===0)c=ctx.normalizeCompanion(clone(c));
 }
 return {c,trace,summary:{name,stageMinutes:counts,maxHunger,maxDebt,events:trace.filter(x=>x.event).reduce((a,e)=>(a[e.event]=(a[e.event]||0)+1,a),{})}};
}
const results=[];for(const [name,policy] of [['steady',{conscientiousness:90,sociability:35}],['social',{conscientiousness:40,sociability:90}],['variable',{variation:30,conscientiousness:30}]]){const a=run(name,policy),b=run(name,policy,true,true);assert.deepEqual(clone(a.c.humanDynamics),clone(b.c.humanDynamics),name+' body parity');assert.deepEqual(clone(a.c.lifeRuntime.activities),clone(b.c.lifeRuntime.activities),name+' activity parity');assert(a.summary.stageMinutes.asleep>0);assert(a.summary.events.completed>0);assert.equal(a.summary.events.reply_ready,21,'every synthetic incoming message reaches a reply opportunity');assert(a.summary.stageMinutes.winding_down<=100,'no repeated evening nap loop');assert(a.trace.some(x=>x.event==='arrival'&&x.lateMinutes>0),'chat delay must produce actual lateness');results.push(a);}
if(process.env.VH_WEEK_REPORT){fs.writeFileSync(process.env.VH_WEEK_REPORT,JSON.stringify(results.map(({summary,trace})=>({summary,trace})),null,2));}
console.log(JSON.stringify(results.map(x=>x.summary),null,2));console.log('PASS three seven-day lives, bounded physiology and background/reload parity');
