const assert=require('node:assert/strict'),engine=require('../virtual_humans/engine/vh-world-engine');
global.VHActivityEngine=require('../virtual_humans/engine/vh-activity-engine');const core=require('../virtual_humans/engine/vh-simulation-core');
const base=Date.UTC(2026,8,8),at=m=>base+m*60000;
function fixture(){return {id:'person',name:'Ada',locationMode:'custom',timezoneOffsetMinutes:0,currentOutfit:'Old clothes',mood:{relationship:60},relationshipDynamics:{trust:60},humanDynamics:{stress:20,energy:80},lifeProfile:core.normalizeCompanionLifeProfile({initializedAt:1,places:[{id:'home',label:'Home',kind:'home'},{id:'gym',label:'Gym'},{id:'work',label:'Work'}],weeklySchedule:[{id:'a',days:[2],startMinute:480,endMinute:540,placeId:'home',activity:'Breakfast'},{id:'b',days:[2],startMinute:550,endMinute:610,placeId:'gym',activity:'Workout'}],travelLegs:[{from:'home',to:'gym',mode:'DRIVE',minutes:5,cost:2},{from:'home',to:'gym',mode:'WALK',minutes:20,cost:0}],socialCircle:[{id:'jo',name:'Jo'}],world:{transport:{enabled:true,budget:20},gifts:{enabled:true,mailAllowed:true,cashAllowed:true,minTrust:20,deliveryHours:1,likes:['cozy']},closet:{mode:'items'},items:[{id:'pants',name:'Blue pants',category:'bottom',owned:true},{id:'top',name:'White shirt',category:'top',owned:true},{id:'gift',name:'Green hoodie',category:'top',owned:false,tags:['cozy'],photo:'data:image/png;base64,AA=='}],people:[{personId:'jo',placeId:'gym',days:[2],start:540,end:610,activity:'training'}]}}),lifeRuntime:core.normalizeCompanionLifeRuntime({}),lifeEvents:[]};}
const advance=(c,m)=>engine.advance(c,at(m),core.companionLocalMinuteInfo,(c,t)=>core.companionBaseSituationAt(c,t,true));
let c=fixture();advance(c,539);advance(c,550);assert.equal(c.lifeRuntime.world.journey.mode,'WALK','no car access means no driving');assert.equal(c.lifeRuntime.world.placeId,'home');
engine.interrupt(c,at(550),5);const copy=JSON.parse(JSON.stringify(c));copy.lifeRuntime.world=engine.runtime(copy.lifeRuntime.world);
advance(c,565);advance(copy,565);assert.deepEqual(c.lifeRuntime.world,copy.lifeRuntime.world);assert.equal(c.lifeRuntime.world.placeId,'gym');assert.equal(c.lifeRuntime.world.journey,null);
assert.equal(c.lifeRuntime.world.events.filter(e=>e.kind==='arrival').length,1);assert.equal(c.lifeRuntime.world.events.find(e=>e.kind==='arrival').lateMinutes,15);advance(c,565);assert.equal(c.lifeRuntime.world.events.filter(e=>e.kind==='arrival').length,1);
assert.equal(c.lifeRuntime.world.events.filter(e=>e.kind==='encounter').length,1);assert(c.lifeRuntime.world.people.jo.energy<80);
let gift=fixture();assert(engine.offerGift(gift,{id:'g1',kind:'digital',itemId:'gift',value:20},at(500)));assert.equal(gift.lifeRuntime.world.inventory.length,0);advance(gift,500);advance(gift,560);assert(gift.lifeRuntime.world.inventory.includes('gift'));assert.equal(gift.lifeRuntime.world.events.filter(e=>e.id==='gift-received:g1').length,1);advance(gift,561);assert.equal(gift.lifeRuntime.world.events.filter(e=>e.id==='gift-received:g1').length,1);
const look=engine.chooseOutfit(gift,at(565),{activity:'cozy'},'gift');assert(look.ids.includes('gift')&&look.ids.includes('pants'));assert(!look.ids.includes('top'));
assert.equal(engine.offerGift(gift,{id:'g1',kind:'digital',itemId:'gift',value:20},at(566)),false);
let rejected=fixture();rejected.lifeProfile.world.gifts.mailAllowed=false;assert.throws(()=>engine.offerGift(rejected,{id:'x',itemId:'gift',value:10},at(500)),/agreed/);assert.equal(rejected.lifeRuntime.world.gifts.length,0);
const msg={id:'u',role:'user',text:'May I send you a gift?',timestamp:at(500),readAt:at(500)};assert(engine.consent(rejected,{kind:'mail',allow:true,evidence:'send you a gift'},[msg],at(501)));assert(engine.offerGift(rejected,{id:'x',itemId:'gift',value:10},at(501)));
const revoke={...msg,id:'u2',timestamp:at(502),readAt:at(502)};assert(engine.consent(rejected,{kind:'mail',allow:false,evidence:'send you a gift'},[revoke],at(503)));assert.throws(()=>engine.offerGift(rejected,{id:'y',itemId:'gift',value:10},at(503)),/agreed/);
let framed=fixture();framed.lifeProfile.world.frame=engine.config({frame:{mode:'dating',requestMinutes:0}}).frame;assert(!engine.connected(framed));engine.requestConnection(framed,at(500));advance(framed,500);assert(engine.connected(framed));
let cash=fixture();engine.offerGift(cash,{id:'money',kind:'cash',value:25},at(500));advance(cash,500);assert.equal(cash.lifeRuntime.world.balance,45);advance(cash,501);assert.equal(cash.lifeRuntime.world.balance,45);
let unavailable=fixture();unavailable.lifeProfile.travelLegs=unavailable.lifeProfile.travelLegs.filter(l=>l.mode==='DRIVE');advance(unavailable,549);advance(unavailable,551);assert.equal(unavailable.lifeRuntime.world.placeId,'home');assert(unavailable.lifeRuntime.world.events.some(e=>e.kind==='missed'));
console.log('PASS connected world: permission, gifting, delayed receipt, cash, outfit, match, travel, interruption, lateness, encounters and reload');

let routed=fixture();routed.lifeProfile.world.transport.liveRouting=true;routed.lifeProfile.places[0].googlePlaceId='origin';routed.lifeProfile.places[1].googlePlaceId='destination';advance(routed,539);advance(routed,540);const req=engine.routeRequest(routed,at(540));assert(req);assert(!engine.applyRoute(routed,'stale',{routes:[{duration:'600s'}]},at(540)));assert(engine.applyRoute(routed,req.id,{routes:[{duration:'600s'}]},at(540)));assert.equal(routed.lifeRuntime.world.journey.arrivesAt,at(550));assert.equal(engine.routeRequest(routed,at(541)),null);
let midnight=fixture();midnight.lifeProfile.weeklySchedule=[core.normalizeCompanionScheduleBlock({id:'night',days:[2],startMinute:1430,endMinute:30,placeId:'gym',activity:'Late visit'})];advance(midnight,1420);advance(midnight,1450);assert.equal(midnight.lifeRuntime.world.placeId,'gym');assert.equal(midnight.lifeRuntime.world.events.filter(e=>e.kind==='arrival').length,1);
console.log('PASS live route response identity, once-only application, and cross-midnight commitment');

assert.equal(gift.lifeRuntime.world.wear.pants,undefined,'unchanged trousers are still being worn, not in laundry');
let digital=fixture();digital.lifeProfile.world.gifts.mailAllowed=false;assert(engine.offerGift(digital,{id:'digital',kind:'digital',itemId:'gift',value:5},at(500)));advance(digital,500);assert(digital.lifeRuntime.world.inventory.includes('gift'));assert.equal(digital.lifeRuntime.world.playerBalance,995);
let laundry=fixture();laundry.lifeProfile.world.transport.enabled=false;laundry.lifeProfile.world.closet.laundryHours=1;laundry.lifeProfile.world.closet.laundryMinutes=5;laundry.lifeRuntime.world=engine.runtime({lastAt:at(480),started:true,placeId:'home',wear:{top:{dirtyAt:at(400)}}});engine.advance(laundry,at(486),core.companionLocalMinuteInfo,()=>({placeId:'home',availability:'available',activity:'home'}));assert(!laundry.lifeRuntime.world.wear.top);assert(laundry.lifeRuntime.world.events.some(e=>e.kind==='laundry'));
console.log('PASS digital gift wallet and completed laundry restore availability without laundering worn pieces');
function replay(reload){let c=fixture(),stress=0,energy=0;for(let m=470;m<470+2880;m++){const result=advance(c,m);stress+=result.stress;energy+=result.energy;if(reload)c.lifeRuntime.world=engine.runtime(JSON.parse(JSON.stringify(c.lifeRuntime.world)));}return {state:c.lifeRuntime.world,stress,energy};}
assert.deepEqual(replay(true),replay(false));console.log('PASS two-day replay is identical across per-minute reloads');
const vm=require('node:vm'),{buildContext}=require('./app_source');const context={console,state:{globalSettings:{},personas:[]}};buildContext(vm,['normalizeCompanion','companionAlwaysOnSnapshot','companionPhotoReferences','buildCompanionPhotoPrompt'],context);
const migrated=context.normalizeCompanion({id:'migration',name:'Ada',age:30,photoLocations:[{id:'bedroom',label:'Bedroom',description:'Blue walls',photo:'data:image/png;base64,AAA='}],lifeProfile:{world:{items:[{id:'top',name:'Top',category:'top',photo:'data:image/png;base64,BBB='}]}}});
assert.equal(migrated.lifeProfile.places[0].photo,'data:image/png;base64,AAA=');assert.equal(migrated.photoLocations.length,0);
const snapshot=context.companionAlwaysOnSnapshot(migrated,{experience:{},messages:[]});assert.equal(snapshot.companion.lifeProfile.places[0].photo,undefined);assert.equal(snapshot.companion.lifeProfile.world.items[0].photo,undefined);assert(migrated.lifeProfile.places[0].photo);
console.log('PASS place reference migration and media-free host snapshots preserve source assets');

assert.equal(engine.config(null).frame.mode,'direct');assert.equal(engine.runtime(null).connection.state,'none');assert.equal(engine.config({items:[null,1],people:[null]}).items.length,0);
const dst=fixture();dst.locationMode='real';dst.timezone='America/New_York';dst.lifeProfile.weeklySchedule=[core.normalizeCompanionScheduleBlock({id:'dst',days:[0],startMinute:540,endMinute:600,placeId:'gym',activity:'Morning visit'})];
const tickDst=t=>engine.advance(dst,t,core.companionLocalMinuteInfo,(c,t)=>core.companionBaseSituationAt(c,t,true));tickDst(Date.UTC(2026,10,1,4));tickDst(Date.UTC(2026,10,1,13,40));assert.equal(dst.lifeRuntime.world.journey.targetStart,Date.UTC(2026,10,1,14));console.log('PASS appointment departure across daylight-saving fallback');

const ors=fixture();ors.lifeProfile.world.transport.liveRouting=true;ors.lifeProfile.places[0].mapCoordinates=[8.6,49.4];ors.lifeProfile.places[1].mapCoordinates=[8.7,49.5];advance(ors,539);advance(ors,540);const orsRequest=engine.routeRequest(ors,at(540));assert.deepEqual(orsRequest.originCoordinates,[8.6,49.4]);assert.deepEqual(orsRequest.destinationCoordinates,[8.7,49.5]);assert(engine.applyRoute(ors,orsRequest.id,{provider:'openrouteservice',routes:[{duration:'800s'}]},at(540)));assert.match(ors.lifeRuntime.world.events.at(-1).summary,/openrouteservice/);assert.equal(core.normalizeCompanionLifePlace({mapCoordinates:[1,100]}).mapCoordinates,null);assert.deepEqual(core.normalizeCompanionLifePlace({mapCoordinates:[0,0]}).mapCoordinates,[0,0]);
// A saved provider estimate drives planning before departure, not only arrival repair.
const planned=fixture();planned.lifeProfile.weeklySchedule[0].endMinute=500;
planned.lifeProfile.travelLegs=[{from:'home',to:'gym',mode:'WALK',minutes:35,source:'openrouteservice'}];
advance(planned,514);assert.equal(planned.lifeRuntime.world.journey,null);
advance(planned,515);assert.equal(planned.lifeRuntime.world.journey.departedAt,at(515));
assert.equal(planned.lifeRuntime.world.journey.arrivesAt,at(550));
planned.lifeProfile.world.transport.liveRouting=true;
planned.lifeRuntime.world.journey.routeSource='Manual override';
assert.equal(engine.routeRequest(planned,at(515)),null,'live routing must respect an explicit duration override');
console.log('PASS saved route estimate schedules departure and explicit overrides bypass live refresh');
